core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java, core/src/test/java/org/apache/calcite/test/ReflectiveSchemaTest.java, core/src/test/resources/sql/conditions.oq
The PR seems to fix null semantics handling for OR and AND.
For `not (c='a' and c='b')` it generates the following code:
```java
/* 113 */ while (inputEnumerator.moveNext()) {
/* 114 */   final String current = inputEnumerator.current() == null ? (String) null
: inputEnumerator.current().toString();
/* 115 */   if (!(current == null || org.apache.calcite.runtime.SqlFunctions.eq(current, "a")
|| (current == null || org.apache.calcite.runtime.SqlFunctions.eq(current, "b")))) {
/* 116 */     return true;
/* 117 */   }
/* 118 */ }
```
=> [CALCITE-980] Fix AND and OR implementation in Enumerable convention

avatica/core/src/main/java/org/apache/calcite/avatica/BuiltInConnectionProperty.java, avatica/core/src/main/java/org/apache/calcite/avatica/ConnectionConfig.java, avatica/core/src/main/java/org/apache/calcite/avatica/ConnectionConfigImpl.java, avatica/core/src/main/java/org/apache/calcite/avatica/remote/AuthenticationType.java, avatica/core/src/main/java/org/apache/calcite/avatica/remote/AvaticaCommonsHttpClientImpl.java, avatica/core/src/main/java/org/apache/calcite/avatica/remote/AvaticaHttpClientFactoryImpl.java, avatica/core/src/main/java/org/apache/calcite/avatica/remote/Service.java, avatica/core/src/main/java/org/apache/calcite/avatica/remote/UsernamePasswordAuthenticateable.java, avatica/server/src/main/java/org/apache/calcite/avatica/server/AbstractAvaticaHandler.java, avatica/server/src/main/java/org/apache/calcite/avatica/server/AvaticaServerConfiguration.java, avatica/server/src/main/java/org/apache/calcite/avatica/server/HttpServer.java, avatica/server/src/test/java/org/apache/calcite/avatica/server/AbstractAvaticaHandlerTest.java, avatica/server/src/test/java/org/apache/calcite/avatica/server/BasicAuthHttpServerTest.java, avatica/server/src/test/java/org/apache/calcite/avatica/server/DigestAuthHttpServerTest.java, avatica/server/src/test/java/org/apache/calcite/avatica/server/HttpAuthBase.java, avatica/server/src/test/resources/auth-users.properties, avatica/site/_docs/client_reference.md, avatica/site/_docs/security.md, avatica/src/main/config/checkstyle/suppressions.xml
Adds support for HTTP basic and digest auth. New builder
methods on HttpServer, and new client implementations.
Additional docs outlining use.
=> [CALCITE-1173] HTTP Basic and Digest authentication support

site/.gitignore, site/README.md, site/docker-compose.yml
I am currently looking into publishing the website for calcite-avatica-go 3.0.0 once its released.
I use Windows as my main environment and didn't want to install ruby and a bunch of dependencies in my Linux VMs.
I added a docker-compose file to automate most of the site authoring steps and to make it easier for contributors to update the site.
I also made the following changes:
- bumped the ruby version.
- bumped the `github-pages` gem to version `182`.
- `jerkyll_oembed` was failing, because it was quite old, so I followed the new instructions from https://github.com/18F/jekyll-oembed
- For the manual (old instructions), I remove the `gem install` command because I think `bundle install` will install the gems from the gemfile. I am not too familiar with ruby, so please let me know if …
=> Add option to use docker to build the website

core/src/main/java/org/apache/calcite/rex/RexSimplify.java, core/src/test/java/org/apache/calcite/test/RexProgramTest.java
`x AND NOT(x) ==> FALSE AND x IS NULL`
closes #707
=> [CALCITE-2327] Avoid simplification of x AND NOT(x) to false for nullable x

babel/pom.xml, core/pom.xml, pom.xml, server/pom.xml
https://issues.apache.org/jira/browse/CALCITE-2558
fmpp-maven-plugin updated SqlParserImpl.java on each build even in case
the file was not modified. It causes maven-compiler-plugin to re-compile everything
New behavior is update SqlParserImpl.java only in case it is modified,
and it significantly improves repeated compilations.
=> [CALCITE-2558] Improve re-compilation times by skipping parser.java update on each build

elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/PredicateAnalyzer.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/BooleanLogicTest.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/ElasticSearchAdapterTest.java
Fix boolean conditions with negation (`NOT`). The following queries are now supported:
```sql
select * from elastic where not foo = 1
select * from elastic where not foo in (1, 2, 3)
```
Extend existing Expression interface with `not()` method.
=> [CALCITE-2585] Support NOT Operator in ElasticSearch Adapter

core/src/main/java/org/apache/calcite/plan/volcano/RuleQueue.java, core/src/main/java/org/apache/calcite/util/Bug.java, pom.xml
https://issues.apache.org/jira/browse/CALCITE-2518
Missing tags like @param, @return are excluded from warnings list.
=> [CALCITE-2518] Add failOnWarnings to maven-javadoc-plugin configuration

core/pom.xml, druid/pom.xml, pom.xml
It is not required at runtime, so the dependency should not be transitive
=> Make findbugs:jsr305 dependency optional

.travis.yml, cassandra/src/test/java/org/apache/calcite/test/CassandraAdapterTest.java, pom.xml, ubenchmark/pom.xml
* Made ubenchmark use the same JDK source/target as the parent pom to avoid 1.6 and JDK 12 issues.
* Cassandra Adapter test fails with JDK12.
* Added JDK12 to version check like JDK11.
=> CALCITE-2655 - Enable Travis to test against JDK 12

elasticsearch/pom.xml, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchJson.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchSchema.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchTable.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchTransport.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/Scrolling.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/ElasticSearchAdapterTest.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/EmbeddedElasticsearchPolicy.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/ScrollingTest.java
The only efficient way to fetch full (large) result set in elastic is to use [scrolling](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html).
Scrolling is to be used for all non-aggregate queries.
For more context [read discussion](https://lists.apache.org/thread.html/ffb971f60ce8e0b0dbac4e1a5cbbf33017d97f69ca5f234fd7ca71ba@%3Cdev.calcite.apache.org%3E) on calcite dev list.
=> [CALCITE-2651] Enable scrolling in ElasticSearch adapter

core/src/main/java/org/apache/calcite/rel/rules/ReduceExpressionsRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
- Update the reduction rule to use an options object to control behavior.
- Update existing methods so they use options object
- Deprecate methods that accept booleans instead of options object
- Expose ability to avoid special handling for dynamic calls
=> [CALCITE-2736] Update the ReduceExpressionsRule to better expose options

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableCorrelate.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableCorrelateRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableJoin.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableJoinRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableSemiJoin.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableThetaJoin.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMdCollation.java, core/src/test/java/org/apache/calcite/rel/rules/SortRemoveRuleTest.java, core/src/test/java/org/apache/calcite/schemas/HrClusteredSchema.java, core/src/test/java/org/apache/calcite/test/CalciteSuite.java, core/src/test/java/org/apache/calcite/tools/PlannerTest.java, core/src/test/resources/sql/join.iq, core/src/test/resources/sql/sub-query.iq, linq4j/src/test/java/org/apache/calcite/linq4j/test/JoinPreserveOrderTest.java, linq4j/src/test/java/org/apache/calcite/linq4j/test/Linq4jSuite.java
1. Introduce collation metadata information for EnumerableJoin, EnumerableThetaJoin, EnumerableSemiJoin, and EnumerableCorrelate.
2. Modify static factory create methods to obtain the collation information from the metadata.
2. Change EnumerableJoinRule, EnumerableCorrelateRule to use the static factory method to create the operators.
3. Add SortRemoveRuleTest, exploiting the preserved collation of various enumerable join operatrs to remove a sort.
4. Adapt sql/join.iq removing redundant sort operators.
5. Add tests verifying the order preserving properties of the join algorithms in EnumerableDefautls.
6. Adapt sub-query.iq quidem test due to CALCITE-2582.
=> [CALCITE-2554] Enrich enumerable join operators with order preserving information (Stamatis Zampetakis)

site/develop/index.md
Add guidelines for commit messages proposed by Julian Hyde in various discussions in the dev list.
=> Site: Add commit message guidelines for contributors (Stamatis Zampetakis)

elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchAggregate.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchTable.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchTableScan.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/AggregationTest.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/ElasticSearchAdapterTest.java
Jira: [CALCITE-2797](https://issues.apache.org/jira/browse/CALCITE-2797)
Convert approximate count (on distinct values) `APPROX_COUNT_DISTINCT` into elastic [cardinality](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html) single-value metrics aggregation.
Remove `AggregateExpandDistinctAggregatesRule` from elastic planner so `APPROX_COUNT_DISTINCT` function can be correctly identified.
=> [CALCITE-2797] Support APPROX_COUNT_DISTINCT aggregate function in ElasticSearch adapter

cassandra/pom.xml
SLF4J initialization was failing due to `NoClassDefFoundError`.
For more info see [CALCITE-2734](https://issues.apache.org/jira/browse/CALCITE-2734)
=> Fix sqlline by excluding redundant slf4j dependency (log4j-over-slf4j) from cassandra-all

elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchAggregate.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchEnumerators.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchMethod.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchRel.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchSort.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchTable.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchToEnumerableConverter.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/ElasticSearchAdapterTest.java
The following queries are currently failing:
```sql
select max(_MAP['a']), _MAP['b'] from elastic group by _MAP['b']
```
=> [CALCITE-2814] ElasticSearch adapter. Fix "group by" when using raw item access

elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchSchemaFactory.java
`userConfig` is not used since migration to ES RestClient (it is ignored by ElasticsearchSchemaFactory)
=> Remove usage of 'userConfig' attribute in ElasticSearch adapter

core/src/main/java/org/apache/calcite/plan/volcano/RelSubset.java, core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java, core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleCall.java
https://issues.apache.org/jira/browse/CALCITE-2817
This adds VolcanoPlanner#toDot() method to dump planner state in a Graphviz-compatible format.
The state includes sets, subsets, rels. It prints active rule with references to the matched rels.
Color coding:
red subset means it has no rels (besides AbstractConverter) yet
blue (subset, rel) means it is best for its subset
dashed lines connect VolcanoRule with its operands
=> [CALCITE-2817] Make CannotPlanException great

geode/src/main/java/org/apache/calcite/adapter/geode/rel/GeodeFilter.java, geode/src/main/java/org/apache/calcite/adapter/geode/rel/GeodeRules.java, geode/src/test/java/org/apache/calcite/adapter/geode/rel/GeodeAllDataTypesTest.java
Earlier when a boolean column was supplied as a filter, the adapter have thrown Exception.
=> [CALCITE-2850] Geode adapter: support boolean column as filter operand

core/src/main/java/org/apache/calcite/rel/rules/FilterProjectTransposeRule.java, core/src/test/resources/sql/misc.iq, core/src/test/resources/sql/sub-query.iq, geode/src/test/java/org/apache/calcite/adapter/geode/rel/GeodeAllDataTypesTest.java, geode/src/test/java/org/apache/calcite/adapter/geode/rel/GeodeZipsTest.java
1. Use a conservative simplifier before passing the condition to the filter copy.
2. Update expected physical plans in sub-query.iq to reflect the applied simplifications.
=> [CALCITE-2582] FilterProjectTransposeRule does not always simplify the new filter condition (Stamatis Zampetakis)

core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java, core/src/main/java/org/apache/calcite/sql/SqlDialect.java, core/src/main/java/org/apache/calcite/sql/SqlDialectFactoryImpl.java, core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Printing CROSS JOIN for the cartesian product instead of COMMA for SparkSqlDialect.
=> CALCITE-2856-Emulating Cross Join For SparkSqlDialect

core/src/main/java/org/apache/calcite/jdbc/JavaTypeFactoryImpl.java, core/src/main/java/org/apache/calcite/rel/type/RelDataTypeFactoryImpl.java, core/src/main/java/org/apache/calcite/rel/type/RelRecordType.java, core/src/test/java/org/apache/calcite/sql/type/SqlTypeFactoryTest.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java, server/src/main/java/org/apache/calcite/sql/ddl/SqlCreateTable.java, server/src/test/java/org/apache/calcite/test/ServerTest.java, server/src/test/resources/sql/type.iq
RelRecordType nullable if all its fields are nullable.
Some unit tests' expected results needed to be updated after this modification.
=> [CALCITE-2464] Allow to set nullability for columns of structured types (Ruben Quesada Lopez)

core/src/main/java/org/apache/calcite/rex/RexSimplify.java, core/src/test/java/org/apache/calcite/test/RexProgramTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml, core/src/test/resources/sql/sub-query.iq, geode/src/test/java/org/apache/calcite/adapter/geode/rel/GeodeAllDataTypesTest.java
This patch enables to simplify x=true to x and x=false to not(x)
It also handles inequalities which are probably less frequent.
=> [CALCITE-2839] Simplify comparisions against boolean literals

elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchConstants.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchEnumerators.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchJson.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchProject.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/ElasticSearchAdapterTest.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/Projection2Test.java
In some circumstances (eg. order by clause) `select *` would return `{}`.
=> [CALCITE-2863] ElasticSearch Adapter. "select *" may return empty tionary

babel/src/main/codegen/config.fmpp, core/custom-schema-model.json, core/src/main/codegen/config.fmpp, core/src/main/codegen/templates/Parser.jj, core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/CalciteResource.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/fun/SqlJsonDepthFunction.java, core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/main/resources/org/apache/calcite/runtime/CalciteResource.properties, core/src/test/codegen/config.fmpp, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java, core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java, core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java, core/src/test/java/org/apache/calcite/test/SqlJsonFunctionsTest.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java, server/src/main/codegen/config.fmpp, site/_docs/reference.md
Returns the maximum depth of a JSON document. Returns NULL if the argument is NULL. An error occurs if the argument is not a valid JSON document.
An empty array, empty object, or scalar value has depth 1. A nonempty array containing only elements of depth 1 or nonempty object containing only member values of depth 1 has depth 2. Otherwise, a JSON document has depth greater than 2.
Example Sql:
```sql
SELECT JSON_DEPTH(v) AS c1
,JSON_DEPTH(JSON_VALUE(v, 'lax $.b' ERROR ON ERROR)) AS c2
,JSON_DEPTH(JSON_VALUE(v, 'strict $.a[0]' ERROR ON ERROR)) AS c3
,JSON_DEPTH(JSON_VALUE(v, 'strict $.a[1]' ERROR ON ERROR)) AS c4
FROM (VALUES ('{"a": [10, true],"b": "[10, true]"}')) AS t(v)
limit 10;
```
Result:
| c1   | c2   | c3   | c4   |
| ---- | ---- | ---- | ---- |
| 3    | 2    | 1    | 1    |
=> [CALCITE-2864]Add the JSON_DEPTH function

core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java, core/src/test/java/org/apache/calcite/plan/volcano/VolcanoPlannerTraitTest.java
By default, cost for Convention.NONE is infinity.
- Add option to allow Convention.None planning with VolcanoPlanner
- Add a unit test
Change-Id: Idcee2ca923c9b10b58cc9352a390a87f899b64ee
=> [CALCITE-2827] Allow Convention.NONE planning with VolcanoPlanner

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableInterpretable.java, core/src/main/java/org/apache/calcite/config/CalciteSystemProperty.java, linq4j/src/main/java/org/apache/calcite/linq4j/tree/VisitorImpl.java, ubenchmark/pom.xml, ubenchmark/src/main/java/org/apache/calcite/adapter/enumerable/CodeGenerationBenchmark.java, ubenchmark/src/main/java/org/apache/calcite/adapter/enumerable/package-info.java
1. Add a configurable Guava cache in EnumerableInterpretable#getBindable to re-use Bindable instances.
2. Avoid caching instances of classes with static fields.
3. Add JMH benchmark for the expensive part of EnumerableInterpretable#getBindable method.
4. Add utility method for obtaining integer runtime properties.
5. NPE in VisitorImpl when visiting a FieldDeclaration without an initializer.
=> [CALCITE-2703] Reduce code generation and class loading overhead when executing queries in the EnumerableConvention (Stamatis Zampetakis)

core/src/main/java/org/apache/calcite/rel/metadata/RelMdPredicates.java, core/src/main/java/org/apache/calcite/rex/RexSimplify.java, core/src/main/java/org/apache/calcite/rex/RexUtil.java, core/src/main/java/org/apache/calcite/tools/RelBuilder.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Deprecated simplifyOr/simplitfyAnd methods as alternate entry points may not get that much attention during development.
Before this, some simplification opportunities were missed during predicate processing.
From now on in RelBuilder all Rex simplifications are postponed until Rel creation time - which makes it more consistent and it also obeys the simplification setting.
=> [CALCITE-2338] Make Simplification API more conservative

elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchJson.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/AggregationTest.java
Replace `anyMatch` with `allMatch`...
=> [CALCITE-2890] Elasticsearch adapter. combine "any_value" with other aggs failed

core/src/main/java/org/apache/calcite/rex/RexLiteral.java, core/src/main/java/org/apache/calcite/util/Unsafe.java, core/src/main/java/org/apache/calcite/util/Util.java, ubenchmark/src/main/java/org/apache/calcite/benchmarks/StringConstructBenchmark.java
1. Replace combination of PrintWriter/StringWriter with StringBuilder.
2. Add JMH benchmark showing a 10X improvement when choosing StringBuilder.
=> [CALCITE-2887] Improve performance of RexLiteral#toJavaString

core/src/main/java/org/apache/calcite/plan/volcano/RuleQueue.java, example/csv/src/main/java/org/apache/calcite/adapter/csv/CsvFieldType.java, file/src/main/java/org/apache/calcite/adapter/file/FileFieldType.java, linq4j/src/main/java/org/apache/calcite/linq4j/tree/ConstantExpression.java, linq4j/src/main/java/org/apache/calcite/linq4j/tree/FunctionExpression.java, linq4j/src/main/java/org/apache/calcite/linq4j/tree/Primitive.java, linq4j/src/main/java/org/apache/calcite/linq4j/tree/Types.java
1. Replace rule.getClass().getSimpleName() with rule.toString():
(i) It conforms to the API VolcanoPlannerPhaseRuleMappingInitializer;
(ii) It is safer to use when the same rule class has many instances;
(iii) It is much more efficient.
2. Precompute the class name for Boxed primitives and use where necessary.
3. Remove Types#boxClassName since it is slightly redundant.
=> [CALCITE-2897] Reduce expensive calls to Class#getSimpleName

core/src/main/java/org/apache/calcite/rel/metadata/RelMdPercentageOriginalRows.java, core/src/test/java/org/apache/calcite/test/RelMdPercentageOriginalRowsTest.java
Fixes NullPointerException thrown by RelMdPercentageOriginalRows when explaining plan with all attributes
=> [CALCITE-2894] NullPointerException thrown by RelMdPercentageOriginalRows when explaining plan with all attributes (Ruben Quesada Lopez)

core/src/main/java/org/apache/calcite/plan/RelOptRule.java, core/src/main/java/org/apache/calcite/plan/RelTraitPropagationVisitor.java, core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleCall.java
The class is deprecated for the following reasons:
1. The contract and behavior of RelTraitPropagationVisitor are not consistent.
2. It traverses RelNode subtrees after every rule transformation affecting performance.
3. It exists only for debugging purposes and we have no proof that helps discover issues.
4. It not modified for the past five years.
5. It is unlikely to be used in the future.
=> [CALCITE-2899] Deprecate RelTraitPropagationVisitor and remove its usages

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumUtils.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableAggregate.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableCollect.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableScan.java, core/src/main/java/org/apache/calcite/adapter/enumerable/PhysType.java, core/src/main/java/org/apache/calcite/adapter/enumerable/PhysTypeImpl.java, core/src/main/java/org/apache/calcite/jdbc/JavaTypeFactoryImpl.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/util/Bug.java, core/src/test/java/org/apache/calcite/adapter/enumerable/PhysTypeTest.java, core/src/test/java/org/apache/calcite/jdbc/JavaTypeFactoryTest.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java, core/src/test/java/org/apache/calcite/test/QuidemTest.java, core/src/test/resources/sql/struct.iq
1. Remove wrong unnesting of single field struct types from JavaTypeFactoryImpl and EnumUtils.
2. Refactor and move EnumUtils#javaRowClass method in PhysTypeImpl since it is used in only one place.
3. Add tests for JavaTypeFactoryImpl#getJavaClass and PhysType#fieldClass methods.
4. Modify EnumerableCollect to work always with rows represented as Object[], necessary for having MULTISET working after fixing CALCITE-2776.
5. Modify PhysType#convertTo to use JavaRowFormat instead of PhysType since the conversion is meant to only change the representation of rows in Java.
6. Disallow optimizations of the row format in the PhysType#convertTo method.
7. Implement SqlFunctions.slice method according to the specification in StdSqlOperatorTable.SLICE.
8. Add struct.iq test for reproducing …
=> [CALCITE-2677] Struct types with one field are not mapped correctly to Java Classes (Stamatis Zampetakis)

core/src/main/java/org/apache/calcite/rel/AbstractRelNode.java, core/src/main/java/org/apache/calcite/rel/RelWriter.java, core/src/main/java/org/apache/calcite/rel/externalize/RelJsonWriter.java, core/src/main/java/org/apache/calcite/rel/externalize/RelWriterImpl.java, ubenchmark/src/main/java/org/apache/calcite/benchmarks/AbstractRelNodeGetRelTypeNameBenchmark.java
1. Use StringBuilder instead of PrintWriter for building the digest, which is more efficient to initialize and append to.
2. Improve (sligthly) the performance of AbstractRelNode#getRelTypeName (used in the digest) by performing:
a. one lastIndexOf operation instead of potentially two;
b. char instead of char[] array comparison.
3. Add micro benchmark with different implementations of AbstractRelNode#getRelTypeName showing the benefit of the adopted implementation.
4. Improve RelWriter interface with default methods and refactor respective classes.
=> [CALCITE-2902] Improve performance of AbstractRelNode#computeDigest

src/main/config/assemblies/source-assembly.xml
Performed dryrun release steps to ensure that maven-wrapper.jar is not in the source distribution.
```bash
./mvnw -DdryRun=true -DskipTests -DreleaseVersion=1.19.0 -DdevelopmentVersion=1.20.0-SNAPSHOT -Papache-release -Darguments=-DskipTests release:prepare 2>&1 | tee /tmp/prepare-dry.log
```
=> [CALCITE-2925] - Exclude maven-wrapper.jar from source distribution

geode/src/main/java/org/apache/calcite/adapter/geode/rel/GeodeSchema.java, geode/src/main/java/org/apache/calcite/adapter/geode/rel/GeodeSchemaFactory.java, geode/src/main/java/org/apache/calcite/adapter/geode/util/GeodeUtils.java
[CALCITE-2877] Make GeodeSchema constructor public to pass client cache object
=> [CALCITE-2877] Make GeodeSchema constructor public to pass client cache object

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableLimitRule.java, core/src/test/java/org/apache/calcite/rel/rules/EnumerableLimitRuleTest.java
EnumerableLimitRule "converst a Sort that has offset or fetch set to an EnumerableLimit on top of a 'pure' Sort that has no offset or fetch". This is the "normal" scenario, and there is no issue with that.
However, there is another scenario, where the EnumerableLimitRule is applied on an "empty" Sort (with no field collations) with offset / fetch. In that case, the EnumerableLimit's input will not be the Sort (because it will disappear, since it was empty), but the Sort's input. The problem comes in this case, because the EnumerableLimit will be created with the Sort's traitSet and cluster; instead of the Sort's input (which is the actual EnumerableLimit input) traitSet and cluster.
The bug can be easily fixed by using EnumerableLimit#create method, instead of EnumerableLimit's …
=> [CALCITE-2941] EnumerableLimitRule on Sort with no collation creates EnumerableLimit with wrong traitSet and cluster

site/develop/index.md
Add guidelines for setting correctly the fix version field in JIRA, as proposed by Francis Chuang in a discussion on the dev list.
=> Site: Add guidelines for JIRA's fix version field

core/src/main/java/org/apache/calcite/plan/RelOptRuleCall.java, core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleCall.java, core/src/main/java/org/apache/calcite/rel/rules/PruneEmptyRules.java, core/src/test/java/org/apache/calcite/plan/volcano/VolcanoPlannerTest.java, core/src/test/java/org/apache/calcite/rel/rules/SortRemoveRuleTest.java, core/src/test/java/org/apache/calcite/tools/PlannerTest.java
This PR fixes the bug described in https://issues.apache.org/jira/browse/CALCITE-2456, where the `unordered` child operand type is not handled properly in VolcanoRuleCall.
=> [CALCITE-2456] fix VolcanoRuleCall#match for unordered child operand

core/src/test/resources/sql/struct.iq, linq4j/src/main/java/org/apache/calcite/linq4j/function/Functions.java, linq4j/src/test/java/org/apache/calcite/linq4j/test/Linq4jTest.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-3021
=> [CALCITE-3021] ArrayEqualityComparer should use Arrays#deepEquals/deepHashCode instead of Arrays#equals/hashCode (Ruben Quesada Lopez)

elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchRules.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/AggregationTest.java
Fix queries of type (with elastic adapter):
```sql
select max(cast(_MAP['foo'] as integer)) from elastic
```
=> [CALCITE-3056] Elasticsearch adapter. Invalid result with cast function on raw queries

core/src/main/java/org/apache/calcite/plan/RelOptUtil.java, core/src/main/java/org/apache/calcite/rel/rules/ProjectJoinTransposeRule.java, core/src/test/java/org/apache/calcite/plan/RelOptUtilTest.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
ProjectTransposeJoinRule does not identify expanded versions of IS NOT
DISTINCT FROM expressions in the join filter, and might push them below
the join operator in a way which makes impossible for
RelOptUtil#splitJoinCondition() to identify the INDF condition and mis-
categorize the join as not being an equi-join.
Fix the issue by collapsing INDF expressions before invoking PushProjector.
Also add support for expanded form CASE(WHEN A IS NULL THEN B IS NULL
WHEN B IS NULL THEN A IS NULL ELSE A = B).
=> [CALCITE-2803] ProjectTransposeJoinRule messes INDF expressions

core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java, core/src/main/java/org/apache/calcite/util/BlackholeMap.java, core/src/main/java/org/apache/calcite/util/Util.java, core/src/test/java/org/apache/calcite/util/UtilTest.java
VolcanoPlanner.provenanceMap captures provenance of all rel nodes added
to the planner but the information is only printed out if planner log
level is debug or finer.  As the map can get quite big with complex
queries, the memory usage can increase significantly.
Detect if planner log level is debug when creating a new volcano planner
and use a blackhole map so that the map is not populated by default.
=> [CALCITE-3062] Do not populate provenanceMap if not debug

elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchJson.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchMapping.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchSchema.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchSchemaFactory.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchTable.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchTransport.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchVersion.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/AggregationTest.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/ElasticSearchAdapterTest.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/EmbeddedElasticsearchNode.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/EmbeddedElasticsearchPolicy.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/ScrollingTest.java, pom.xml, site/_docs/elasticsearch_adapter.md, sqlline, sqlline.bat
Types are deprecated in APIs in 7.0, with breaking changes to the index creation, put mapping, get mapping, put template, get template and get field mappings APIs.
https://www.elastic.co/guide/en/elasticsearch/reference/7.0/removal-of-types.html
In this PR, I propose that the name of the tables corresponds to indices in Elasticsearch.
JIRA: https://issues.apache.org/jira/browse/CALCITE-3023
=> [CALCITE-3023] Upgrade to Elasticsearch 7.0.0

core/src/main/java/org/apache/calcite/plan/RelOptUtil.java, core/src/main/java/org/apache/calcite/tools/RelBuilder.java, core/src/test/java/org/apache/calcite/plan/RelOptUtilTest.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
RelOptUtil#pushDownJoinConditions do not identify and preserve
expanded versions of `IS NOT DISTINCT FROM` expressions, causing
equi-joins to be miscategorized as inequality joins.
Modify the function to try to collapse the expression back to a
canonical `IS NOT DISTINCT FROM` expression if possible before
visiting the expression and pushing it below the join.
=> [CALCITE-2807] Fix `IS NOT DISTINCT FROM` expression identification in RelOptUtil#pushDownJoinConditions()

core/src/main/java/org/apache/calcite/sql/SqlJdbcFunctionCall.java, core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
Fix [ISSUE #3048](https://issues.apache.org/jira/browse/CALCITE-3084)
Implement JDBC string functions:
```doc
{fn ASCII(string)}
{fn DIFFERENCE(string, string)}
{fn REPEAT(string, integer)}
{fn SOUNDEX(string)}
{fn SPACE(integer)}
```
=> [CALCITE-3084] Implement JDBC string functions: ASCII, REPEAT, SPACE, SOUNDEX, DIFFERENCE

kafka/pom.xml, kafka/src/main/java/org/apache/calcite/adapter/kafka/KafkaMessageEnumerator.java, kafka/src/main/java/org/apache/calcite/adapter/kafka/KafkaRowConverter.java, kafka/src/main/java/org/apache/calcite/adapter/kafka/KafkaRowConverterImpl.java, kafka/src/main/java/org/apache/calcite/adapter/kafka/KafkaStreamTable.java, kafka/src/main/java/org/apache/calcite/adapter/kafka/KafkaTableConstants.java, kafka/src/main/java/org/apache/calcite/adapter/kafka/KafkaTableFactory.java, kafka/src/main/java/org/apache/calcite/adapter/kafka/KafkaTableOptions.java, kafka/src/main/java/org/apache/calcite/adapter/kafka/package-info.java, kafka/src/test/java/org/apache/calcite/adapter/kafka/KafkaAdapterTest.java, kafka/src/test/java/org/apache/calcite/adapter/kafka/KafkaMockConsumer.java, kafka/src/test/java/org/apache/calcite/adapter/kafka/KafkaRowConverterTest.java, kafka/src/test/resources/kafka.model.json, pom.xml, site/_docs/adapter.md, site/_docs/kafka_adapter.md, sqlline
Add an adapter to expose Kafka topics as STREAM tables.
`KafkaTableFactory` is used here so end users need to specify table-topic mapping one-by-one.
JIRA: https://issues.apache.org/jira/browse/CALCITE-2913
CC: @danny0405
=> [CALCITE-2913] Adapter for Apache Kafka

core/src/main/java/org/apache/calcite/sql/SqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java, core/src/main/java/org/apache/calcite/sql/fun/SqlRollupOperator.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
As described in [CALCITE-3077](https://issues.apache.org/jira/browse/CALCITE-3077), we need to rewrite CUBE(...)&ROLLUP(...) clauses as WITH CUBE and WITH ROLLUP in Spark SQL.
=> [CALCITE-3077] Rewrite CUBE&ROLLUP queries in SparkSqlDialect

core/src/main/java/org/apache/calcite/sql/SqlUtil.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
Queries similar to `SELECT 1 UNION SELECT 2, 3` might cause Calcite
validator to throw an NPE exception instead of a proper error message.
When validating operands of a set operation, if operands don't have
matching schema, and if one of the operand doesn't have a FROM clause,
SqlUtil#getSelectListItem throws NPE.
Fixing by adding a proper check.
=> [CALCITE-3082] Fix NPE in SqlUtil#getSelectListItem

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableAggregate.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableAggregateRule.java, core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcRules.java, core/src/main/java/org/apache/calcite/interpreter/AggregateNode.java, core/src/main/java/org/apache/calcite/interpreter/Bindables.java, core/src/main/java/org/apache/calcite/rel/core/Aggregate.java, core/src/main/java/org/apache/calcite/rel/logical/LogicalAggregate.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnOrigins.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMdUtil.java, core/src/main/java/org/apache/calcite/rel/rules/AbstractMaterializedViewRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateExpandDistinctAggregatesRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateFilterTransposeRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateJoinRemoveRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateJoinTransposeRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateMergeRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateProjectMergeRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateProjectPullUpConstantsRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateReduceFunctionsRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateStarTableRule.java, core/src/main/java/org/apache/calcite/rel/stream/StreamRules.java, core/src/main/java/org/apache/calcite/rex/RexBuilder.java, core/src/main/java/org/apache/calcite/sql2rel/RelFieldTrimmer.java, core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/test/java/org/apache/calcite/plan/volcano/TraitPropagationTest.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-2944
=> [CALCITE-2944] Deprecate Aggregate indicator and remove fields where possible

core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java, core/src/main/java/org/apache/calcite/rel/mutable/MutableAggregate.java, core/src/main/java/org/apache/calcite/rel/mutable/MutableRels.java, core/src/main/java/org/apache/calcite/util/mapping/Mappings.java, core/src/test/java/org/apache/calcite/test/MaterializationTest.java
As described in [CALCITE-3087](https://issues.apache.org/jira/browse/CALCITE-3087), AggregateOnProjectToAggregateUnifyRule cannot ignore Project when its Mapping breaks ordering.
This PR: (1) adds validation in MutableAggreagte, as that in Aggregate, (2) adds a Project after UnifyAggregate to recover the field order and ensure the result's rowtype when the mapping breaks ordering.
=> [CALCITE-3087] AggregateOnProjectToAggregateUnifyRule ignores Project incorrectly when its Mapping breaks ordering

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumUtils.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableCorrelate.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableNestedLoopJoin.java, core/src/main/java/org/apache/calcite/rel/core/JoinRelType.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, linq4j/src/main/java/org/apache/calcite/linq4j/CorrelateJoinType.java, linq4j/src/main/java/org/apache/calcite/linq4j/DefaultEnumerable.java, linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java, linq4j/src/main/java/org/apache/calcite/linq4j/ExtendedEnumerable.java, linq4j/src/test/java/org/apache/calcite/linq4j/test/CorrelateJoinTest.java, linq4j/src/test/java/org/apache/calcite/linq4j/test/JoinPreserveOrderTest.java
Jira ticket: [CALCITE-3119](https://issues.apache.org/jira/browse/CALCITE-3119)
=> [CALCITE-3119] Deprecate Linq4j CorrelateJoinType (in favor of JoinType)

core/src/main/java/org/apache/calcite/rel/mutable/MutableRels.java, core/src/test/java/org/apache/calcite/test/MaterializationTest.java
As discussed in CALCITE-3060, mapping beheavior should be fixed.
=> [CALCITE-3060] MutableProject should be generated based on INVERSE_SURJECTION mapping

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
This PR for issue(https://issues.apache.org/jira/browse/CALCITE-3146)
=> [CALCITE-3146] Support the detection of nested aggregations for JdbcAggregate in SqlImplementor

core/src/main/codegen/templates/Parser.jj, core/src/main/java/org/apache/calcite/runtime/CalciteResource.java, core/src/main/resources/org/apache/calcite/runtime/CalciteResource.properties, core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
Replace generateParseException() and new ParseExecption to
SqlUtil.newContextException, this makes the error message more user
friendly.
=> [CALCITE-3152] Unify throws in sql parser

core/src/main/java/org/apache/calcite/tools/RelBuilder.java, core/src/test/java/org/apache/calcite/test/RelBuilderTest.java
Jira ticket: [CALCITE-3172](https://issues.apache.org/jira/browse/CALCITE-3172)
=> [CALCITE-3172] RelBuilder#empty does not keep aliases

pom.xml
To harmonize the versions of Jackson among the different projects.
=> CALCITE-3179: Bump Jackson from 2.9.8 to 2.9.9

core/src/main/java/org/apache/calcite/plan/RelOptUtil.java, core/src/main/java/org/apache/calcite/rel/rules/FilterCorrelateRule.java, core/src/main/java/org/apache/calcite/rel/rules/FilterJoinRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableJoinTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Antijoin on conditions should not be pushed down to either left or right hand
side.
This also fix the RelDecorrelator#decorrelate(LogicalJoin), before this
patch, the semi/anti decorrelation returns nothing.
=> [CALCITE-3170] ANTI join on conditions push down generates wrong plan

core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java, core/src/test/java/org/apache/calcite/test/MaterializationTest.java
As illustrated in [CALCITE-3160](https://issues.apache.org/jira/browse/CALCITE-3160), TrivialRule should conduct the replacement.
=> [CALCITE-3160] Failed to materialize when the aggregate function uses group key

mongodb/src/main/java/org/apache/calcite/adapter/mongodb/MongoSchema.java, mongodb/src/main/java/org/apache/calcite/adapter/mongodb/MongoSchemaFactory.java, mongodb/src/test/java/org/apache/calcite/adapter/mongodb/MongoAdapterTest.java
Some methods were deprecated after client upgrade to 3.10.2 (see [CALCITE-3157])
=> Fix complitation warnings after mongo java driver upgrade

core/src/main/java/org/apache/calcite/rel/RelNode.java, core/src/main/java/org/apache/calcite/rel/core/Project.java, core/src/test/java/org/apache/calcite/test/CalciteSuite.java, core/src/test/java/org/apache/calcite/test/RexShuttleTest.java
Jira ticket: [CALCITE-3165](https://issues.apache.org/jira/browse/CALCITE-3165) 
Project#accept(RexShuttle shuttle) can return a copy of the original Project, if the list of expressions is modified by the shuttle. However, this Project copy will maintain the original rowType, which might be wrong because this type is based on the expressions list (which was modified by the shuttle).
=> [CALCITE-3165] Project#accept(RexShuttle shuttle) does not update rowType

core/src/main/java/org/apache/calcite/prepare/CalciteMaterializer.java, core/src/test/java/org/apache/calcite/test/MaterializationTest.java
In current code, before matching query with materialized-view, unused fields of query is trimmed but materialized-view is not. Thus below simple SQL fails to be matched though query and materialized-
view are exactly the same:
```
@Test public void testMaterializationAfterTrimingOfUnusedFields() {
String sql =
"select \"y\".\"deptno\", \"y\".\"name\", \"x\".\"sum_salary\"\n" +
"from\n" +
" (select \"deptno\", sum(\"salary\") \"sum_salary\" from \"emps\" group by \"deptno\") \"x\"\n" +
" join\n" +
" \"depts\" \"y\"\n" +
" on \"x\".\"deptno\"=\"y\".\"deptno\"\n";
checkMaterialize(sql, sql);
}
```
Checking `CalciteMaterializer` https://github.com/apache/calcite/blob/master/core/src/main/java/org/apache/calcite/prepare/CalciteMaterializer.java#L83 , I think the code intends to do the …
=> [CALCITE-3182] Trim unused fields for plan of materialized-view before matching.

core/src/main/java/org/apache/calcite/adapter/enumerable/ReflectiveCallNotNullImplementor.java, core/src/main/java/org/apache/calcite/adapter/enumerable/RexToLixTranslator.java, core/src/test/java/org/apache/calcite/test/UdfTest.java, core/src/test/java/org/apache/calcite/util/Smalls.java, linq4j/src/main/java/org/apache/calcite/linq4j/tree/Shuttle.java, linq4j/src/main/java/org/apache/calcite/linq4j/tree/TryStatement.java, linq4j/src/test/java/org/apache/calcite/linq4j/test/InlinerTest.java
Details are described in [JIRA](https://issues.apache.org/jira/browse/CALCITE-3195).
This PR handles checked exceptions declared in method.
(1) Wrap a method call in a `try...catch...` block;
(2) Enable BlockBuilder to inline variables in `TryStatement`.
=> [CALCITE-3195] Handle UDF that throws checked exceptions in enumerable code generator

core/src/main/java/org/apache/calcite/rel/mutable/MutableMultiRel.java, core/src/test/java/org/apache/calcite/test/MutableRelTest.java
When digging code of materialization matching. I found the current implementation of `MutableMultiRel::inputs` is by an `ImmutableList`, thus impossible to be changed by
https://github.com/apache/calcite/blob/master/core/src/main/java/org/apache/calcite/rel/mutable/MutableMultiRel.java#L42
```
@Override public void setInput(int ordinalInParent, MutableRel input)
```
Seems a mistake.
This PR propose to store inputs of MutableMultiRel by ArrayList rather than ImmutableList
=> [CALCITE-3209] When calling MutableMultiRel::setInput, exception thrown

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableRepeatUnion.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableRepeatUnionRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableSpool.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableSpoolRule.java, core/src/main/java/org/apache/calcite/rel/core/RelFactories.java, core/src/main/java/org/apache/calcite/rel/core/RepeatUnion.java, core/src/main/java/org/apache/calcite/rel/core/TableSpool.java, core/src/main/java/org/apache/calcite/rel/logical/LogicalRepeatUnion.java, core/src/main/java/org/apache/calcite/rel/logical/LogicalTableSpool.java, core/src/main/java/org/apache/calcite/tools/RelBuilder.java, core/src/test/java/org/apache/calcite/test/RelBuilderTest.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableRepeatUnionHierarchyTest.java, linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Jira ticket: [CALCITE-3109](https://issues.apache.org/jira/browse/CALCITE-3109) 
Pending details from [CALCITE-2812](https://issues.apache.org/jira/browse/CALCITE-2812) to make the RepeatUnion and TableSpool more consistent:
TableSpool:
- Replace `String tableName` with `RelOptTable table`.
RepeatUnion:
- Rename `maxRep` as `iterationLimit`. Change this field to allow all integer values, and treat all negative values as "no limit".
- EnumerableDefaults#repeatUnionAll: make close method idempotent
=> [CALCITE-3109] Improvements on algebraic operators to express recursive queries (RepeatUnion & TableSpool)

plus/src/test/java/org/apache/calcite/adapter/tpcds/TpcdsTest.java
It's a little improve  to use `assertEqual`  instead of just printing result in TpcdsTest#testQuery27Builder.
=> [CALCITE-3153] Improve testing in TpcdsTest using assertEqual instead of printing results

core/src/main/java/org/apache/calcite/rel/mutable/MutableRels.java, core/src/test/java/org/apache/calcite/test/MutableRelTest.java
Current implementation of MutableRels::toMutables is as below:
```
private static List<MutableRel> toMutables(List<RelNode> nodes) {
return Lists.transform(nodes, MutableRels::toMutable);
}
```
Thus every time we get from the result list, a new `MutableRel` will be created:
```
private static class TransformingRandomAccessList<F, T> extends AbstractList<T>
implements RandomAccess, Serializable {
final List<F> fromList;
final Function<? super F, ? extends T> function;
TransformingRandomAccessList(List<F> fromList, Function<? super F, ? extends T> function) {
this.fromList = checkNotNull(fromList);
this.function = checkNotNull(function);
}
@Override
public T get(int index) {
return function.apply(fromList.get(index));
}
......
```
As a result, …
=> [CALCITE-3211] List of MutableRel may fail to be identified by SubstitutionVisitor during matching

core/src/main/java/org/apache/calcite/rel/rules/ReduceDecimalsRule.java, core/src/main/java/org/apache/calcite/rel/rules/SubQueryRemoveRule.java, core/src/main/java/org/apache/calcite/rel/type/RelDataTypeFactoryImpl.java, pom.xml
Fix compiler warnings introduced by patches for issues CALCITE-3031 and
CALCITE-3187.
Also force compiler to stop if such warnings are detected.
=> Fix compiler warnings

core/src/main/java/org/apache/calcite/rex/RexSimplify.java, core/src/test/java/org/apache/calcite/test/RexProgramTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
For expressions like: (1 < x or ( x < 3 and c ))
simplification was made to ( 1 < x or c )
=> [CALCITE-3192] Simplify OR incorrectly weaks condition

core/src/main/java/org/apache/calcite/rel/externalize/RelJson.java, core/src/main/java/org/apache/calcite/rel/externalize/RelJsonReader.java, core/src/test/java/org/apache/calcite/plan/RelWriterTest.java
When deserialize from json string, in some cases, different SqlOperators may have the same name, for example, "PLUS" and "PLUS_PREFIX". So the kind of SqlOperator should also be used for searching.
=> [CALCITE-3177]Ensure correct deserialization of relational algebra.

core/src/main/java/org/apache/calcite/rex/RexSimplify.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/java/org/apache/calcite/test/RexProgramTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Jira ticket: [CALCITE-3198](https://issues.apache.org/jira/browse/CALCITE-3198)
RexSimplify is able to simplify expressions like:
`x = a AND x = b => FALSE`
However, it is not able to simplify the negation of that expression:
```
NOT(x = a AND x = b) => (x <> a OR x <> b) 
=> TRUE (if unknownas.TRUE or x's type is not nullable)
=>  x IS NOT NULL (otherwise)
```
The current change aims to carry out this simplification.
=> [CALCITE-3198] Enhance RexSimplify to handle (x<>a or x<>b)

core/src/main/java/org/apache/calcite/tools/RelBuilder.java, core/src/test/java/org/apache/calcite/test/RelBuilderTest.java
In current implementation of `RelBuilder::scan ` (https://github.com/apache/calcite/blob/master/core/src/main/java/org/apache/calcite/tools/RelBuilder.java#L1048), the alias can be derived and recorded into `Frame` only when the `RelNode` is a `TableScan` (https://github.com/apache/calcite/blob/master/core/src/main/java/org/apache/calcite/tools/RelBuilder.java#L2754).
But when `RelBuilder::scan` from an expanded view, the node is not a `TableScan` and the alias is not kept.  Below test failed - we cannot reference a field by alias "MYVIEW".
```
@Test public void testExpandViewShouldKeepAlias() throws SQLException {
try (Connection connection = DriverManager.getConnection("jdbc:calcite:")) {
final Frameworks.ConfigBuilder configBuilder =
expandingConfig(connection);
final …
```
=> [CALCITE-3226] Expand view should keep the alias expanded view 

core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/java/org/apache/calcite/test/RexProgramTest.java
Use `&lt;&gt;` (i.e. escaped<>) instead of `!=` in javadoc
=> [CALCITE-3198] Enhance RexSimplify to handle '(x<>a or x<>b)' (fix javadoc)

core/src/main/codegen/templates/Parser.jj, core/src/main/java/org/apache/calcite/sql/SqlBasicTypeNameSpec.java, core/src/main/java/org/apache/calcite/sql/SqlCollectionTypeNameSpec.java, core/src/main/java/org/apache/calcite/sql/SqlDataTypeSpec.java, core/src/main/java/org/apache/calcite/sql/SqlRowTypeNameSpec.java, core/src/main/java/org/apache/calcite/sql/SqlTypeNameSpec.java, core/src/main/java/org/apache/calcite/sql/SqlUserDefinedTypeNameSpec.java, core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java, core/src/test/java/org/apache/calcite/test/catalog/Fixture.java, core/src/test/java/org/apache/calcite/test/catalog/MockCatalogReaderExtended.java, site/_docs/reference.md
Changes:
* Add a new SqlTypeNameSpec SqlCollectionTypeNameSpec to describe nested
collections type
* Refactor SqlDataTypeSpec to only keep SqlTypeNameSpec, TimeZone and
nullble.
* Add a new method SqlTypeNameSpec#deriveType(SqlValidator) to support
derive type for UDT(throws exception when we can't deduce any type).
=> [CALCITE-3250] Support nested collection type for  SqlDataTypeSpec

core/src/main/java/org/apache/calcite/rel/externalize/RelJson.java, core/src/main/java/org/apache/calcite/rel/externalize/RelJsonReader.java, core/src/test/java/org/apache/calcite/plan/RelWriterTest.java
The class of udf was lost in the pr [CALCITE-3177](https://github.com/apache/calcite/pull/1305), causing an NullPointerException  when deserializing of udf operator. In this pr, add class info to the map parameter for deserializing operator, and remove unused function parameter.
=> [CALCITE-3246] NullPointerException while deserializing udf operator.

core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java, core/src/test/java/org/apache/calcite/test/MaterializationTest.java
Current `Substitution#getRexShuttle` does not take `RexLiteral` into consideration.
Thus below query & mv fails matching:
```
MV:
select deptno, sum(salary), sum(commission), sum(k)
from
(select deptno, salary, commission, 100 as k
from emps)
group by deptno
Query:
select deptno, sum(salary), sum(k)
from
(select deptno, salary, 100 as k
from emps)
group by deptno
```
The root cause is that `ProjectToProjectUnifyRule` compensates a `Project` which contains `RexLiteral`, but `AggregateOnProjectToAggregateUnifyRule` works only when the `Project` in query is a mapping
https://github.com/apache/calcite/blob/master/core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java#L1357
=> [CALCITE-3249] Substitution#getRexShuttle does not consider RexLiteral

core/src/main/java/org/apache/calcite/plan/MaterializedViewSubstitutionVisitor.java, core/src/test/java/org/apache/calcite/test/MaterializationTest.java
Below materialization matching fails now
```
@Test public void testDEV() {
String sql0 = "select * from \"emps\" where \"empid\" < 300";
String sql1 = "select * from \"emps\" where \"empid\" > 200";
checkMaterialize(sql0 + " union all " + sql1, sql1 + " union all " + sql0);
}
```
This PR proposes to add a rule for Union matching
=> [CALCITE-3214] Add UnionToUnionRule for materialization matching.

core/src/main/java/org/apache/calcite/plan/MaterializedViewSubstitutionVisitor.java
https://github.com/apache/calcite/pull/1333 merged a materialization matching rule.
But the naming style of UnionToUnionRule is inconsistent with other rules like `ScanToProjectUnifyRule`, `ProjectToProjectUnifyRule`, `FilterToProjectUnifyRule`.
This PR propose to refine the name as `UnionToUnionUnifyRule`, and sorry for my carelessness in my previous PR.
=> [CALCITE-3214] Add UnionToUnionRule for materialization matching (refine rule name)

core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java
Current doc of `SubstitutionVisitor.java` says the supported core relational operators are `@link org.apache.calcite.rel.logical.LogicalTableScan`, and so on.
But with `convertTableAccess=true` (https://github.com/apache/calcite/blob/master/core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java#L5636), it's a `EnumerableTableScan` under `MutableScan`, which is inconsistent with the doc. 
And what's more, `MutableRels` and `SubstitutionVisitor` supporting scope doesn't limit to be `org.apache.calcite.rel.logical.LogicalXXX`.
So I think it might make sense to update/refine the doc to say that the supported core relational operators are
```
* {@link org.apache.calcite.rel.core.TableScan},
* {@link org.apache.calcite.rel.core.Filter},
* {@link …
```
=> [CALCITE-3262] Refine doc of SubstitutionVisitor.java

piglet/src/test/java/org/apache/calcite/test/PigRelTestBase.java
Jira: [CALCITE-3307](https://issues.apache.org/jira/browse/CALCITE-3307)
=> [CALCITE-3307] PigRelExTest, PigRelOpTest and PigScriptTest fail on Windows

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumUtils.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableBatchNestedLoopJoin.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableHashJoin.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableNestedLoopJoin.java
Jira ticket:  [CALCITE-3309](https://issues.apache.org/jira/browse/CALCITE-3309) 
The method `EnumerableNestedLoopJoin#predicate` (that generates a predicate Expression based on a RexNode condition) has been copied-pasted as `EnumerableBatchNestedLoopJoin#generatePredicate` due to [CALCITE-2979](https://issues.apache.org/jira/browse/CALCITE-2979), and `EnumerableHashJoin#generatePredicate` due to [CALCITE-2973](https://issues.apache.org/jira/browse/CALCITE-2973).
The goal of this PR is to refactor that method into a single location (e.g. EnumUtils) where it can be accessible by all 3 Enumerable Joins.
=> [CALCITE-3309] Refactor generatePredicate method from EnumerableNestedLoopJoin/EnumerableHashJoin/EnumerableBatchNestedLoopJoin into a single location

druid/src/test/java/org/apache/calcite/test/DruidAdapter2IT.java, druid/src/test/java/org/apache/calcite/test/DruidAdapterIT.java, druid/src/test/java/org/apache/calcite/test/DruidChecker.java
1. Update stale tests in DruidAdapterIT and DruidAdapter2IT following the implementation of implicit casts in CALCITE-2302.
2. Refactor common druidChecker code in DruidAdapterIT and DruidAdapter2IT in a separate class.
Co-authored-by: yuzhao.cyz <yuzhao.cyz@alibaba-inc.com>
=> [CALCITE-3315] Multiple failures in Druid IT tests due to implicit casts

pig/pom.xml, piglet/pom.xml, spark/pom.xml
Disable OWASP dependency-check for pig, piglet, and spark modules.
=> [CALCITE-3314] CVSS dependency-check-maven fails for calcite-pig, calcite-piglet, calcite-spark

core/src/main/java/org/apache/calcite/plan/volcano/RelSet.java, core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
In current code of `RelSet#addAbstractConverters`, null checking of `curRelTrait` happens after clause of assert `curRelTrait.getTraitDef() == traitDef`;
It makes more sense to adjust the order;
In my understanding, this issue was not found previously for two reasons:
1. `AbstractConverter` is not enabled by default (https://github.com/apache/calcite/blob/master/core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableConvention.java#L65)
2. It rarely happens that two algebra expression operators have identical semantics but different `RelTraitDef`
I found this issue when working on https://issues.apache.org/jira/browse/CALCITE-2970
=> [CALCITE-3357] Trivial null checking in RelSet#addAbstractConverters

core/src/main/java/org/apache/calcite/sql/type/ComparableOperandTypeChecker.java, core/src/main/java/org/apache/calcite/sql/validate/implicit/AbstractTypeCoercion.java, core/src/main/java/org/apache/calcite/sql/validate/implicit/TypeCoercion.java, core/src/main/java/org/apache/calcite/sql/validate/implicit/TypeCoercionImpl.java, core/src/test/java/org/apache/calcite/test/TypeCoercionConverterTest.java, core/src/test/java/org/apache/calcite/test/TypeCoercionTest.java, core/src/test/resources/org/apache/calcite/test/TypeCoercionConverterTest.xml, core/src/test/resources/sql/misc.iq
* Add implicit type coercion rules for BETWEEN operator and add test
cases
* For comparison of NUMERIC and CHARACTER, we coerce the CHARACTER to
NUMERIC type which is breaking change.(Before this patch, CHARACTER would
be coerced to INT during sql-to-rel conversion)
* For "DATETIME and CHARACTER" comparison and equality, add coercion rules during sql
node validation, before this patch, the coercion happens during sql-to-rel conversion
* Some code refactoring for TypeCoercionConverterTest
=> [CALCITE-1178] Allow SqlBetweenOperator to compare DATE and TIMESTAMP

README, README.md, site/_docs/howto.md
1. Add more info about Calcite in README.md.
2. Improve release publishing instructions.
3. Add junk files check before launching the actual release process.
=> Improve READMEs and release howto instructions

core/src/main/java/org/apache/calcite/sql/SqlExplain.java, core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
The format check result of explain plan as json is incorrect.
This PR tries to fix it.
=> [CALCITE-3374] Error format check result for explain plan as json

core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
This PR tries to re-enable some ignored tests in RelOptRuleTests.
=> [CALCITE-3346] Enable some ignored tests in RelOptRuleTests

core/src/main/java/org/apache/calcite/rel/rules/FilterJoinRule.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java
Exception may occur when using semi-join, please refer to [CALCITE-3347](https://issues.apache.org/jira/browse/CALCITE-3347) for more details.
This PR use the test case contributed by @LiShuMing
=> [CALCITE-3347] IndexOutOfBoundsException in FixNullabilityShuttle when using FilterIntoJoinRule

linq4j/src/main/java/org/apache/calcite/linq4j/tree/ConstantExpression.java, linq4j/src/test/java/org/apache/calcite/linq4j/test/ExpressionTest.java
As illustrated in [CALCITE-3411](https://issues.apache.org/jira/browse/CALCITE-3411), we need to call `java.math.BigDecimal.valueOf(long exact, int scale)` rather than `new java.math.BigDecimal(long exact, int scale)` to get `BigDecimal`.
=> [CALCITE-3411] Incorrect code generated for BigDecimal ConstantExpression

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableCalc.java, core/src/main/java/org/apache/calcite/plan/AbstractRelOptPlanner.java, core/src/main/java/org/apache/calcite/rel/AbstractRelNode.java, core/src/main/java/org/apache/calcite/rel/core/Filter.java, core/src/main/java/org/apache/calcite/rel/core/Join.java, core/src/main/java/org/apache/calcite/rel/core/Union.java, core/src/main/java/org/apache/calcite/rel/rules/ReduceExpressionsRule.java
Reuse RelMetadataQuery instance as much as possible, rather than create a fresh one without any data cache.
=> [CALCITE-3403] RelMetadataQuery reuse

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java, core/src/test/java/org/apache/calcite/test/JdbcAdapterTest.java
SqlCall AND, OR require exactly 2 operands, instead of creating left-deep
binary tree, which may cause stack overflow for large number of OR operands,
we create balanced binary tree to reduce the recursive call depth.
=> [CALCITE-2792] Stackoverflow while evaluating filter with large number of OR conditions

core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/test/resources/sql/struct.iq
Jira ticket: [CALCITE-3482](https://issues.apache.org/jira/browse/CALCITE-3482)
=> [CALCITE-3482] Equality of nested ROWs returns false for identical literal value

geode/src/main/java/org/apache/calcite/adapter/geode/util/GeodeUtils.java, pom.xml
Remove `ClientCacheFactory.setPdxPersistent` which is deprecated for client caches.
Release notes: https://cwiki.apache.org/confluence/display/GEODE/Release+Notes
=> [CALCITE-3502] Upgrade Geode dependency 1.6.0 -> 1.9.2

core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
When planner root is null, we should skip the validation since the memo is empty at that moment.
=> [CALCITE-3503] NPE at VolcanoPlanner#isValid when DEBUG is enabled

core/src/main/java/org/apache/calcite/interpreter/AggregateNode.java, core/src/main/java/org/apache/calcite/interpreter/Interpreter.java, core/src/test/java/org/apache/calcite/test/InterpreterTest.java
Using decimal type aggregate in Interpreter cause exception.
Please refer to [CALCITE-3494](https://issues.apache.org/jira/browse/CALCITE-3494) for details.
This PR tries to add support for decimal type aggregate in Interpreter.
=> [CALCITE-3494] Support decimal type aggregate in Interpreter

core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java
As illustrated in [CALCITE-3498](https://issues.apache.org/jira/browse/CALCITE-3498), the ordinality's compution should be in `moveNext() `method rather than in `current()` method.
=> [CALCITE-3498] Unnest operation's ordinality should be deterministic

core/src/main/java/org/apache/calcite/rex/RexUtil.java
https://issues.apache.org/jira/browse/CALCITE-3492
=> [CALCITE-3492] RexUtil.simplifyOrs() throws exception if terms has 1 RexNode

core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java
JIRA: [CALCITE-3567](https://issues.apache.org/jira/browse/CALCITE-3567)
Currently, UNNEST(RECORDTYPE(ARRAY)) and UNNEST(RECORDTYPE(MULTISET)) works well, but UNNEST(RECORDTYPE(MAP)) is not supported.
Because `SqlUnnestOperator` use [SCALAR_OR_RECORD_COLLECTION_OR_MAP](https://github.com/apache/calcite/blob/master/core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java#L581), and it just checks `MULTISET` and `ARRAY` in `RecordType`.
This PR tries to add check for `MAP` in `RecordType` for `SqlUnnestOperator` too.
=> [CALCITE-3567] Unnest support Map wrapped with RecordType

linq4j/src/main/java/org/apache/calcite/linq4j/tree/BinaryExpression.java, linq4j/src/test/java/org/apache/calcite/linq4j/test/ExpressionTest.java
Currently, the value of [expression0 and expression1](https://github.com/apache/calcite/blob/master/linq4j/src/main/java/org/apache/calcite/linq4j/tree/BinaryExpression.java#L26) must be the same type. Otherwise we might a ClassCastException, as shown in JIRA [CALCITE-3281](https://issues.apache.org/jira/browse/CALCITE-3281).
This PR is an improvement to support using different primitive types for expression0 and expression1 of BinaryExpression, so that, make it suite for evaluate in more cases.
=>  [CALCITE-3281] Support mixed Primitive types for BinaryExpression evaluate method.

core/build.gradle.kts, core/src/main/java/org/apache/calcite/util/Sources.java, core/src/test/java/org/apache/calcite/util/SourceTest.java, example/csv/src/main/java/org/apache/calcite/adapter/csv/CsvEnumerator.java, example/csv/src/main/java/org/apache/calcite/adapter/csv/JsonEnumerator.java, file/src/main/java/org/apache/calcite/adapter/file/FileReader.java
Currently calcite `calcite.util.Source` interface can be built only from File or URL. This forces data to be stored on disk or accessed remotely using URL api.
This proposal adds another Source implementation on the top of [CharSource](https://guava.dev/releases/23.0/api/docs/com/google/common/io/CharSource.html) so calcite adapters can operate on in-memory elements like String or generic text sources.
=> [CALCITE-3560] Additional calcite.util.Source implementation for generic text source (eg. CharSource)

core/src/main/java/org/apache/calcite/rel/externalize/RelJson.java, core/src/main/java/org/apache/calcite/rel/externalize/RelJsonReader.java, core/src/test/java/org/apache/calcite/plan/RelWriterTest.java
The class of udf was lost in the pr [CALCITE-3177](https://github.com/apache/calcite/pull/1305), causing an NullPointerException when deserializing of udf operator. In this pr, add class info to the map parameter for deserializing operator, and remove unused function parameter.
This is a re-create PR of https://github.com/apache/calcite/pull/1372,  and please see more discussion in jira [CALCITE-3246](https://issues.apache.org/jira/browse/CALCITE-3246)
=> [CALCITE-3246] NullPointerException while deserializing udf operator

core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java, core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterStructsTest.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Currently, converting `TableFunctionScan` to sql is not supported, doing this will cause exception.
Please refer to [CALCITE-3481](https://issues.apache.org/jira/browse/CALCITE-3481) for more details.
This PR tries to implement the function, adding support to convert `TableFunctionScan` to `SqlNode`.
=> [CALCITE-3481] Support convert TableFunctionScan to SqlNode

core/src/main/java/org/apache/calcite/plan/RelOptUtil.java, core/src/main/java/org/apache/calcite/rel/hint/Hintable.java, core/src/main/java/org/apache/calcite/rel/logical/LogicalJoin.java, core/src/main/java/org/apache/calcite/rel/logical/LogicalProject.java, core/src/main/java/org/apache/calcite/rel/logical/LogicalTableScan.java, core/src/main/java/org/apache/calcite/sql2rel/RelDecorrelator.java, core/src/main/java/org/apache/calcite/sql2rel/RelStructuredTypeFlattener.java, core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/test/java/org/apache/calcite/test/SqlHintsConverterTest.java, core/src/test/resources/org/apache/calcite/test/SqlHintsConverterTest.xml
* Add a new interface Hintable#setHints(List) to set up the rel node
hists;
* Move RelHintPropagateShuttle from SqlToRelConverter to RelOptUtils;
* Add a new method RelOptUtil#propagateRelHints(RelNode, boolean) to
support hints for sql-to-rel conversion and decorrelation;
* Copy the hints for flattened projection in RelStructuredTypeFlattener;
* Add test cases for hints propagation with decorrelation.
=> [CALCITE-3584] Support SQL hints propagation for decorrelation

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableJoinRule.java, core/src/test/java/org/apache/calcite/test/JdbcAdapterTest.java, core/src/test/java/org/apache/calcite/test/JdbcFrontJdbcBackLinqMiddleTest.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java, core/src/test/java/org/apache/calcite/test/MaterializationTest.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableHashJoinTest.java, core/src/test/java/org/apache/calcite/tools/PlannerTest.java, core/src/test/resources/sql/join.iq, core/src/test/resources/sql/misc.iq, core/src/test/resources/sql/some.iq, core/src/test/resources/sql/sub-query.iq, linq4j/src/main/java/org/apache/calcite/linq4j/Linq4j.java, plus/src/test/java/org/apache/calcite/adapter/tpch/TpchTest.java
Jira ticket: [CALCITE-3535](https://issues.apache.org/jira/browse/CALCITE-3535)
With the implementation of [CALCITE-2973](https://issues.apache.org/jira/browse/CALCITE-2973), now EnumerableHashJoin supports all type of conditions (not just equi joins). However, there is still one TODO in EnumerableHashJoinRule that, in case of an INNER Join, creates a Filter with the non-equi conditions on top of the EnumerableHashJoin (created only with the equi-conditions), this filter is not really needed, since now EnumerableHashJoinRule can support the full condition: equi and non-equi items.
=> [CALCITE-3535] EnumerableJoinRule: remove unnecessary Filter on top of INNER Join

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableScan.java, core/src/test/java/org/apache/calcite/test/MaterializationTest.java
Credits to @DonnyZone who pointed me in the right direction.
Jira ticket: [CALCITE-3598](https://issues.apache.org/jira/browse/CALCITE-3598)
=> [CALCITE-3598] EnumerableTableScan: wrong JavaRowFormat for elementType String

core/src/main/codegen/templates/Parser.jj, core/src/main/java/org/apache/calcite/sql/SqlLateralOperator.java, core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java, core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
* Remove the SqlLateralOperator instantiation for temporal table join;
* Remove SNAPSHOT node match for SqlLateralOperator;
* In SqlValidatorImpl, fix the scope of SNAPSHOT node.
=> [CALCITE-3620] Remove implicit lateral operator for temporal table join

core/src/main/java/org/apache/calcite/rel/rules/ReduceExpressionsRule.java
JIRA: https://issues.apache.org/jira/projects/CALCITE/issues/CALCITE-3630
=> [CALCITE-3630] Improve ReduceExpressionsRule

core/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnUniqueness.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMdUniqueKeys.java, core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
https://issues.apache.org/jira/browse/CALCITE-3666
This is required for better join cardinality estimation when EnumerableCalc is involved
=> [CALCITE-3666] Refine RelMdColumnUniqueness and RelMdUniqueKeys for Calc

core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
See full stack trace in jira[CALCITE-3651](https://issues.apache.org/jira/browse/CALCITE-3651)
The reason for NPE coms from the null value for `neededAlias` attribute when create Result object for TableFunctionScan.
=> [CALCITE-3651] NPE when convert relational algebra that correlates TableFunctionScan 

core/src/main/java/org/apache/calcite/rex/RexBuilder.java, core/src/test/java/org/apache/calcite/rex/RexBuilderTest.java
DECIMAL is fixed point type, when creating RexLiteral with DECIMAL type,
should not only use the integer part, need the decimal fraction part as well
=> [CALCITE-3587] RexBuilder may lose decimal fraction for creating literal with DECIMAL type

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
In current Calcite implementation for query : SELECT TRIM('ABC') for  big-query Dialect it translated into SELECT TRIM(BOTH ' ' FROM 'ABC') .
But the appropriate query for BigQuery is  :: SELECT TRIM('ABC')
Similarly below query
SELECT TRIM(BOTH 'a' from 'ABC') 
SELECT TRIM(LEADING ' ' from 'ABC') 
SELECT TRIM(TRAILING ' ' from 'ABC') are translated into invalid BigQuery query.
Unparse logic for the trim has been handle in BigQuery dialect to convert the source Trim query into valid bigQuery query.
=> [Calcite 3663] Support for TRIM function in BigQuery dialect

core/src/main/java/org/apache/calcite/plan/RelOptTable.java, core/src/main/java/org/apache/calcite/plan/ViewExpanders.java, core/src/main/java/org/apache/calcite/prepare/CalciteMaterializer.java, core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
* In RelOptTable, add an interface ToRelContextSupplier to allow
customize the ToRelContext
* Add ToRelContext#getTableHints to fetch hints when translating table
to relational node
* Add a new method ViewExpanders#toRelContext(ViewExpander,
RelOptCluster, List<RelHint>) to allow passing the hints to the ToRelContext
* Remove the old `viewExpander instanceOf ToRelContext` logic because it
is never used in Calcite, and we should not cast a superclass to child
class
=> [CALCITE-3715] Add an interface to pass the table hints to RelOptTable

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableRelImplementor.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableScan.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableScanRule.java, core/src/main/java/org/apache/calcite/config/CalciteSystemProperty.java, core/src/main/java/org/apache/calcite/prepare/RelOptTableImpl.java, core/src/test/java/org/apache/calcite/plan/volcano/TraitPropagationTest.java, core/src/test/java/org/apache/calcite/sql/validate/LexEscapeTest.java, core/src/test/java/org/apache/calcite/test/ScannableTableTest.java
This is a workaround for CALCITE-3673.
TransientTable can only be implemented with interpreter,
so EnumerableTableScan should not be created for those tables.
=> [CALCITE-3677] Add assertion to EnumerableTableScan constructor to validate if the table is suitable for enumerable scan

core/src/main/java/org/apache/calcite/config/CalciteSystemProperty.java, core/src/main/java/org/apache/calcite/rel/RelWriter.java, core/src/main/java/org/apache/calcite/rel/externalize/RelJsonWriter.java, core/src/main/java/org/apache/calcite/rel/externalize/RelWriterImpl.java, core/src/main/java/org/apache/calcite/rex/RexCall.java, core/src/main/java/org/apache/calcite/rex/RexNode.java, core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/test/java/org/apache/calcite/materialize/LatticeSuggesterTest.java, core/src/test/java/org/apache/calcite/rel/rules/DateRangeRulesTest.java, core/src/test/java/org/apache/calcite/rex/RexCallNormalizationTest.java, core/src/test/java/org/apache/calcite/rex/RexProgramBuilderBase.java, core/src/test/java/org/apache/calcite/rex/RexProgramTest.java, core/src/test/java/org/apache/calcite/rex/RexProgramTestBase.java, core/src/test/java/org/apache/calcite/test/MaterializationTest.java, core/src/test/java/org/apache/calcite/test/RelMetadataTest.java, core/src/test/java/org/apache/calcite/test/RexTransformerTest.java, core/src/test/java/org/apache/calcite/tools/FrameworksTest.java, core/src/test/java/org/apache/calcite/tools/PlannerTest.java
`$0=$1` and `$1=$0` have the same semantics, so it is worth normalizing them to reduce the planning time.
See https://issues.apache.org/jira/browse/CALCITE-2450
=> [CALCITE-2450] Normalize RexCall predicates when computing digest

build.gradle.kts, cassandra/build.gradle.kts, cassandra/src/test/java/org/apache/calcite/test/CassandraAdapterTest.java, core/build.gradle.kts, core/src/main/java/org/apache/calcite/runtime/Hook.java, core/src/test/java/org/apache/calcite/jdbc/CalciteRemoteDriverTest.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableRepeatUnionHierarchyTest.java, redis/src/test/java/org/apache/calcite/adapter/redis/RedisCaseBase.java
This switches test execution to the concurrent mode by default. In other words, both test classes and test methods could be executed concurrently.
Note: `Hook#add` should not be used in test code as it adds global hooks
which become shared across threads.
Use `Hook#addThread` if you need to add a hook.
=> Use concurrent test execution by default

core/src/main/java/org/apache/calcite/rel/rules/AbstractMaterializedViewRule.java, core/src/main/java/org/apache/calcite/rel/rules/UnionMergeRule.java, core/src/main/java/org/apache/calcite/rel/rules/UnionPullUpConstantsRule.java, core/src/main/java/org/apache/calcite/rel/rules/UnionToDistinctRule.java
UnionMergeRule produced lots of unrelated matches because it matched only the top operand as SetOp.
Bottom operand classes were compared in onMatch method only, so
it resulted in lots of false positives for the optimizer.
Not it does not get added to the optimizer queue at all.
=> Refine rules to avoid producing matches that are known to be no-op

core/src/main/java/org/apache/calcite/rex/RexCallBinding.java, core/src/main/java/org/apache/calcite/sql/fun/SqlCaseOperator.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java, core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml, core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
The issue is introduced by [CALCITE-3355](https://issues.apache.org/jira/browse/CALCITE-3355), in which type deducing is only conducted in validation phase. 
However, when converting to RexNode, a new `SqlOperatorBinding` (i.e., `RexCallBinding`) is used. Consequently, it fails type preservation check.
This PR tries to fill the gap.
=> [CALCITE-3675] SQL to Rel conversion is broken for coalesce on nullable field

core/src/main/java/org/apache/calcite/rel/rules/FilterJoinRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
https://issues.apache.org/jira/browse/CALCITE-3727
We need to check if `aboveFilters` gets changed from `origAboveFilters` in `FilterJoinRule#perform`
=> [CALCITE-3729] Filters failed to be pushed down when it's identical to join condition (Jin Xing)

core/src/main/java/org/apache/calcite/plan/volcano/RuleQueue.java, core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleMatch.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-3744
Some times RelSet can get merged. e.g.:
Each number represet Rel id, and they are in different RelSet.
```
1            4
\         /
2      /
\   /
3
```
Assume in the rulequeue, we have rule match with name of 12, 23, 43. For
simplicity, omit the rule name, first digit represent the parent RelNode,
second represent the child.
If after some rule, we merged the set of 3 into the set of 2, and RelNode 4's
input is replaced by RelSubset of 2. We will retrigger rules and try to add
rulematch 12, 42, 43 into rule queue.
12 will be filtered out, because there is duplicate in the RuleMatch names set.
But for 43, it now has different rulematch digest with previous match, because
RelNode # 4's input RelSubset changed, its digest also …
=> [CALCITE-3744] Duplicate rule matches when RelSet gets merged

core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleCall.java, core/src/test/java/org/apache/calcite/plan/volcano/PlannerTests.java, core/src/test/java/org/apache/calcite/plan/volcano/VolcanoPlannerTest.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-3668
The change was introduced by https://github.com/apache/calcite/pull/784, which I think is wrong.
=> [CALCITE-3668] VolcanoPlanner does not match all the RelSubSet in matchRecursive

core/src/main/java/org/apache/calcite/plan/AbstractRelOptPlanner.java, core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleCall.java, core/src/test/java/org/apache/calcite/test/JdbcAdapterTest.java
Even RelSubset is a subclass of RelNode, but they are quite different. RelNode
already fires these rules, it is not necessary to fire for RelSubset. More
importantly, it never worked due to CALCITE-3755.  In addition, it will waste
time to try to iterate class operands of RelSubset and try to match pattern
operand(RelNode), given that it never matches when ascending.
=> [CALCITE-3756] RelSubset should not match operand(RelNode.class)

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java, core/src/test/resources/sql/functions.iq, site/_docs/reference.md
As illustrated in [CALCITE-3695](https://issues.apache.org/jira/browse/CALCITE-3695)
TANH   returns the hyperbolic cosine of a number.
select tanh(1);
+--------------------+
| EXPR$0             |
+--------------------+
| 0.7615941559557649 |
+--------------------+
(1 row)
!ok
=> [CALCITE-3695] Implement TANH function

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoin.java
Minor change.
Jira ticket: [CALCITE-3773](https://issues.apache.org/jira/browse/CALCITE-3773)
The public EnumerableMergeJoin::create method takes a RexLiteral condition as parameter. However, in the actual (package-private) constructor (and in the parent Join class), the condition is defined as a RexNode. Therefore, the create method parameter must be fixed.
Also, this EnumerableMergeJoin::create method calls a deprecated constructor, it should call the non-deprecated one.
=> [CALCITE-3773] Wrong parameter in EnumerableMergeJoin::create method

core/src/main/java/org/apache/calcite/plan/AbstractRelOptPlanner.java, core/src/main/java/org/apache/calcite/plan/RelOptRuleCall.java, core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleCall.java, core/src/main/java/org/apache/calcite/rel/hint/HintStrategies.java, core/src/main/java/org/apache/calcite/rel/hint/HintStrategyTable.java, core/src/test/java/org/apache/calcite/test/SqlHintsConverterTest.java, core/src/test/resources/org/apache/calcite/test/SqlHintsConverterTest.xml
It is efficient to support exclude rules explicitly for some hints, i.e.
USE_MERGE, NO_USE_HASH.
=> [CALCITE-3781] HintStrategy can specify excluded rules for planner

core/src/main/java/org/apache/calcite/rel/rules/PruneEmptyRules.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Jira ticket: [CALCITE-3783](https://issues.apache.org/jira/browse/CALCITE-3783)
=> [CALCITE-3783] PruneEmptyRules#JOIN_RIGHT_INSTANCE wrong behavior for JoinRelType.ANTI

core/src/main/java/org/apache/calcite/plan/RelOptCluster.java, core/src/main/java/org/apache/calcite/plan/RelOptRuleCall.java, core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
* The type inference of Scala code 'val mq = cluster.getMetadataQuery'
is failed if we have that generic type declaration for the Java method
* After this change, we need a explicit cast for RelMetadataQuery
sub-class
* Fix the RelMetadataTest to reset the RelMetadataQuery instance as
default after a test
* Also rename RelOptCluster#withHintStrategies to setHintStrategies
because it does not really return a new copy
=> [CALCITE-3792] Remove the generic type declaration of method

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableScanRule.java, core/src/main/java/org/apache/calcite/plan/RelOptAbstractTable.java, core/src/main/java/org/apache/calcite/plan/RelOptRules.java, core/src/main/java/org/apache/calcite/plan/RelOptTable.java, core/src/main/java/org/apache/calcite/plan/RelOptUtil.java, core/src/main/java/org/apache/calcite/plan/ViewExpanders.java, core/src/main/java/org/apache/calcite/prepare/Prepare.java, core/src/main/java/org/apache/calcite/prepare/RelOptTableImpl.java, core/src/main/java/org/apache/calcite/rel/core/RelFactories.java, core/src/main/java/org/apache/calcite/rel/rules/TableScanRule.java, core/src/main/java/org/apache/calcite/tools/Programs.java, core/src/main/java/org/apache/calcite/tools/RelRunners.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java, core/src/test/java/org/apache/calcite/test/RelBuilderTest.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableJoinTest.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableRepeatUnionHierarchyTest.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableRepeatUnionTest.java, core/src/test/java/org/apache/calcite/tools/FrameworksTest.java, core/src/test/java/org/apache/calcite/tools/PlannerTest.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/MatchTest.java
* Deprecate TableScanRule and always invoke RelOptTable#toRel for
RelBuilder#scan
* RelOptTableImpl#toRel does not translate to EnumerableTableScan
anymore, the EnumerableTableScan conversion logic has been moved to
EnumerableTableScan
* Remove the BindableTableScanRule from the default prepare ruleset, we
only add it where we really need that
* Fix the plan change
=> [CALCITE-3769] Deprecate TableScanRule

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableScanRule.java, core/src/main/java/org/apache/calcite/plan/RelOptMaterialization.java, core/src/test/java/org/apache/calcite/test/LatticeTest.java
* Fix the RelOptMaterialization to always expand the StartTable
* Simplify the logic in EnumerableTableScanRule
* Also fix the plan diff introduced by other patches
=> [CALCITE-3799] Following CALCITE-3769, fix the slow tests

core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcRules.java, core/src/main/java/org/apache/calcite/rel/core/RelFactories.java, core/src/main/java/org/apache/calcite/tools/RelBuilder.java, core/src/test/java/org/apache/calcite/test/RelBuilderTest.java, pig/src/main/java/org/apache/calcite/adapter/pig/PigRelFactories.java, piglet/src/main/java/org/apache/calcite/piglet/PigRelBuilder.java
User can config a view expander directly when constructing the
RelBuilder.
Deprecate RelFactories#expandingScanFactory, we already called
TranslatableTable#toRel in RelOptTable#toRel.
=> [CALCITE-3798] Make RelBuilder view expander pluggable

core/src/main/java/org/apache/calcite/plan/hep/HepPlanner.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMdUtil.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMetadataQueryBase.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-3791.
=> [CALCITE-3791] HepPlanner does not clear metadata cache for the ancestors of discarded node when a transformation happens

core/src/main/java/org/apache/calcite/prepare/CalcitePrepareImpl.java, core/src/main/java/org/apache/calcite/prepare/PlannerImpl.java, core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/test/java/org/apache/calcite/rel/logical/ToLogicalConverterTest.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Because of CALCITE-3769, this config option is actually useless now,
we always return logical rel with method RelOptTable#toRel.
=> [CALCITE-3801] Deprecate SqlToRelConverter.Config#isConvertTableAccess

core/src/main/java/org/apache/calcite/plan/volcano/RelSet.java, core/src/main/java/org/apache/calcite/plan/volcano/RelSubset.java, core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
When VolcanoPlanner registers an abstract converter, it adds the converter into set.abstractConverters list, then calls checkSatisfiedConverter() to see if any converter is satisfied and can be remove from the list. But for every abstract converter, it always satisfies itself (changeTraitsUsingConverters() returns itself). Basically the converter would be removed from the list right after it's added. So this check is completely unnecessary and it slows down the planner.
=> [CALCITE-3807] checkForSatisfiedConverters() is unnecessary

core/src/main/java/org/apache/calcite/rel/rules/PruneEmptyRules.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Jira: [CALCITE-3837](https://issues.apache.org/jira/browse/CALCITE-3837)
=> [CALCITE-3837] AntiJoin with empty right input can always be transformed as its left input

core/src/test/java/org/apache/calcite/test/enumerable/EnumerableJoinTest.java, linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Jira ticket: [CALCITE-3820](https://issues.apache.org/jira/browse/CALCITE-3820)
The current implementation of EnumerableDefaults#orderBy has the following disadvantages:
1) The TreeMap that performs the actual sorting is eagerly computed. This operation can be quite heavy if we have a very big source. The fact that it is eagerly computed might lead to bad performance in situations where the sort is executed, but it is actually not needed. For example, in a NestedLoopJoin, if the outer enumerator returns no results, the inner one is not even accessed. If we had a huge orderBy as inner, today it would be computed in that scenario, even though it is not actually required. For this reason, in terms of performance it seems clearly preferable to delay the sort operation as much as possible.
2) …
=> [CALCITE-3820] EnumerableDefaults#orderBy should be lazily computed + support enumerator re-initialization

core/src/test/java/org/apache/calcite/runtime/EnumerablesTest.java, linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Jira ticket: [CALCITE-3828](https://issues.apache.org/jira/browse/CALCITE-3828)
EnumerableDefaults#MergeJoinEnumerator throws a NPE in case of null keys.
MergeJoin algorithm assumes that inputs sorted in ascending order, with nulls last (see EnumerableMergeJoinRule), so when reaching a null key on the left / right side means that we are done.
=> [CALCITE-3828] MergeJoin throws NPE in case of null keys

core/src/main/java/org/apache/calcite/rex/RexAnalyzer.java, core/src/main/java/org/apache/calcite/rex/RexInterpreter.java, core/src/main/java/org/apache/calcite/rex/RexSimplify.java, core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-3809
=> [CALCITE-3809] RexSimplify simplifies nondeterministic function incorrectly

core/src/main/java/org/apache/calcite/plan/volcano/RelSet.java, core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java, core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleCall.java
Suppose we have 2 RelSets:
RelSet A: rel1
RelSet B: rel2
rel1 is the parent of rel2.
If there is a transformation rule that transform rel1 to rel2, we will merge
RelSet A and B. During merge process, we can safely prune rel1 to avoid further
rule apply on rel1 and reduce search space, more importantly, avoid cyclic
reference.
=> [CALCITE-3819] Prune parent RelNode when merging child RelSet with parent RelSet

core/src/main/java/org/apache/calcite/rel/rules/ReduceExpressionsRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
JIRA: https://issues.apache.org/jira/browse/CALCITE-3845
=> [CALCITE-3845] CASE WHEN expression with nullability CAST is considered as reduced wrongly in ReduceExpressionsRule

core/src/main/java/org/apache/calcite/rel/rules/SortJoinCopyRule.java
Jira: [CALCITE-3853](https://issues.apache.org/jira/browse/CALCITE-3853).
Several improvements can be made on SortJoinCopyRule (introduced via CALCITE-2624):
- The default INSTANCE currently matches LogicalSort + Join, which seems inconsistent, it should match LogicalSort + LogicalJoin
- The constructor should be public, in order to allow clients to create their own version of the rule
=> [CALCITE-3853] Minor improvements in SortJoinCopyRule

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java, core/src/test/resources/sql/functions.iq, site/_docs/reference.md
As illustrated in [CALCITE-3704](https://issues.apache.org/jira/browse/CALCITE-3704)
MySQL strcmp() function is used to compare two strings. It returns 0 if both of the strings are same and returns -1 when the first argument is smaller than the second according to the defined order and 1 when the second one is smaller the first one.
Syntax:
STRCMP (expr1, expr2)
=> [CALCITE-3704] Implement STRCMP function

babel/src/test/resources/sql/redshift.iq, core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java, core/src/test/resources/sql/functions.iq, site/_docs/reference.md
As illustrated in [CALCITE-3694](https://issues.apache.org/jira/browse/CALCITE-3694)
SINH  function returns the hyperbolic sine of a number.
select sinh(1);
+--------------------+
| EXPR$0             |
+--------------------+
| 1.1752011936438014 |
+--------------------+
(1 row)
!ok
=> [CALCITE-3694] Implement SINH function

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoin.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoinRule.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/test/java/org/apache/calcite/runtime/EnumerablesTest.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableJoinTest.java, linq4j/build.gradle.kts, linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Jira ticket: [CALCITE-3285](https://issues.apache.org/jira/browse/CALCITE-3285).
Added an extra predicate for non-equi condition in EnumerableDefaults#MergeJoinEnumerator (it will be null in case of equi-joins).
=> [CALCITE-3285] EnumerableMergeJoin should support non-equi join conditions

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoin.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/test/java/org/apache/calcite/runtime/EnumerablesTest.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableJoinTest.java, linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Jira: [CALCITE-3846](https://issues.apache.org/jira/browse/CALCITE-3846)
EnumerableMergeJoin implementation expects its inputs to be sorted in ascending order, nulls last (see EnumerableMergeJoinRule). In case of a composite key, EnumerableMergeJoin will represent keys as `JavaRowFormat.LIST`, which is a comparable list, whose comparison is implemented via `FlatLists.ComparableListImpl#compare`. This method will compare both lists, item by item, but it will consider that a null item is less-than a non-null item. This is a de-facto nulls-first collation, which contradicts the pre-requisite of the mergeJoin algorithm.
Proposed solution: merge join algorithm should not compare keys using compareTo method, instead an ad-hoc Comparator should be generated by EnumerableMergeJoin, similar to …
=> [CALCITE-3846]  EnumerableMergeJoin: wrong comparison of composite key with null values

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/type/ReturnTypes.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java, core/src/test/resources/sql/functions.iq, site/_docs/reference.md
Pull request for https://issues.apache.org/jira/browse/CALCITE-3864
=> [CALCITE-3864] Supports CONCAT for variable arguments

core/build.gradle.kts
`avatica-server` was a test only dependencies in [`calcite-core` pre 1.21.0](https://github.com/apache/calcite/blob/calcite-1.21.0/core/pom.xml#L52).
But during the switch to gradle in 1.22.0, it's configured to be an implementation dependency.
This PR switches it back to testImplementation only.
=> [CALCITE-3888] Switch avatica-server to be test dependency for core

.gitignore, .idea/vcs.xml, .ratignore
Here's sample from IDEA's Git log.
Now CALCITE-... are clickable
=> Add JIRA links in Git in IDEA

core/src/main/java/org/apache/calcite/plan/AbstractRelOptPlanner.java, core/src/main/java/org/apache/calcite/plan/RelOptPlanner.java, core/src/main/java/org/apache/calcite/plan/volcano/RelSet.java, core/src/main/java/org/apache/calcite/plan/volcano/RuleQueue.java, core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java, core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleCall.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateCaseToFilterRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateValuesRule.java, core/src/main/java/org/apache/calcite/rel/rules/CalcMergeRule.java, core/src/main/java/org/apache/calcite/rel/rules/ExchangeRemoveConstantKeysRule.java, core/src/main/java/org/apache/calcite/rel/rules/ReduceExpressionsRule.java, core/src/main/java/org/apache/calcite/rel/rules/SortRemoveConstantKeysRule.java, core/src/main/java/org/apache/calcite/rel/rules/ValuesReduceRule.java, core/src/test/java/org/apache/calcite/plan/volcano/VolcanoPlannerTest.java
Currently, volcano planner stores rel node importances with a map. In fact, the value of the map can only be 0.
So there is no need to store the values, and we replace the map with a set to store nodes whose importances are 0.
This makes the code logic clearer, and avoids instability caused by comparing floating point values.
=> [CALCITE-3851] Replace the node importance map with a set for pruned nodes

ubenchmark/build.gradle.kts, ubenchmark/src/jmh/java/org/apache/calcite/benchmarks/PreconditionTest.java
This makes `ubenchmark / .main` classes executable from IDEA
=> Make ubenchmark clases executable from IDEA

core/src/main/java/org/apache/calcite/util/Sources.java, core/src/test/java/org/apache/calcite/util/SourceTest.java
When a FileSource is constructed with only a File object, its URL is left null. This makes it inconvenient for some scenarios where a valid URL is required.
This can be resolved, as each file in the local file system corresponds to a file URL, and we fix it by converting a file object to a file URL.
=> [CALCITE-3790] Make the url() of Sources.of(file) available

core/src/main/java/org/apache/calcite/sql/type/CompositeOperandTypeChecker.java, core/src/main/java/org/apache/calcite/sql/validate/implicit/AbstractTypeCoercion.java, core/src/main/java/org/apache/calcite/sql/validate/implicit/TypeCoercionImpl.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
Such as CONCAT(123, 'abc', DATE '2020-04-17').
=> [CALCITE-3934] Allow type-coercion in CONCAT operator

core/src/main/java/org/apache/calcite/plan/AbstractRelOptPlanner.java, core/src/main/java/org/apache/calcite/plan/RelOptRule.java, core/src/main/java/org/apache/calcite/plan/hep/HepPlanner.java, core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java, core/src/test/resources/sql/sub-query.iq
JIRA: https://issues.apache.org/jira/browse/CALCITE-3868
=> [CALCITE-3868] Remove redundant ruleSet and ruleNames in VolcanoPlanner

core/src/main/java/org/apache/calcite/plan/volcano/RelSet.java, core/src/main/java/org/apache/calcite/plan/volcano/RelSubset.java, core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
It is meaningless to fire rule for RelSubset when it is generated by parent's
trait requirement. (CALCITE-3937)
=> [CALCITE-3937] Fire rule for RelSubset only when it is derived

core/src/main/java/org/apache/calcite/plan/AbstractRelOptPlanner.java
https://issues.apache.org/jira/browse/CALCITE-3947
=> [CALCITE-3947] AbstractRelOptPlanner.classes should be LinkedHashSet so that rule match order is deterministic across runs

core/src/main/java/org/apache/calcite/plan/RelOptUtil.java, core/src/main/java/org/apache/calcite/rel/type/RelDataTypeImpl.java, core/src/main/java/org/apache/calcite/rex/RexLocalRef.java, core/src/main/java/org/apache/calcite/rex/RexUtil.java, core/src/main/java/org/apache/calcite/sql/type/SqlTypeUtil.java
Current interning of types use weak references.
Change from MUST intern to SHOULD intern, and always
compare types using equals.
We clearly want to do some interning, especially within a query, so that
there aren't hundreds of copies of the same record type all over the
place. But if people don't intern, or intern in different query-specific
caches, then the logic will still work.
If equals is written using the standard template
```java
return this == o
|| o instanceof TheType && field1 == o.field1 && field2 == o.field2
```
(that is, avoiding deep comparison if possible) then the performance
will be pretty much the same.
=> [CALCITE-3954] Always compare types using equals

core/src/main/java/org/apache/calcite/rel/RelCollations.java, core/src/main/java/org/apache/calcite/rel/RelDistributions.java
=> [CALCITE-3949] RelDistributions.of() and RelCollations.of() should canonize trait instance

core/src/main/java/org/apache/calcite/plan/Convention.java, core/src/main/java/org/apache/calcite/plan/volcano/RelSet.java, core/src/main/java/org/apache/calcite/plan/volcano/RelSubset.java, core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
Existing RelSubset may be first created by parent trait request, so its state
is required. But when there is a new RelNode in the same RelSet can deliver the
same traitset, we mark the subset as derived/delivered too, in which case, we
should also fire rule for the subset.
JIRA: CALCITE-3966
=> [CALCITE-3966] Trigger rules for existing RelSubset when it becomes delivered

core/src/test/java/org/apache/calcite/test/DiffRepository.java
When many test cases using the same DiffRepository instances are running
on multiple threads, it causes lots of contention because all methods
are synchronized. One of the most used method is
DiffRepository#expand(String, String) which do not alter the state of
the tree in most cases.
As the method content itself is thread-safe, remove the synchronized
keyword as it does not bring any extra safety and just increase
artificially the contention around the lock.
=> [CALCITE-3965] Avoid DiffRepository lock contention

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableValues.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableValuesRule.java, core/src/main/java/org/apache/calcite/rel/logical/LogicalValues.java, core/src/main/java/org/apache/calcite/rel/rules/PruneEmptyRules.java, core/src/test/java/org/apache/calcite/test/RelBuilderTest.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Jira: [CALCITE-3926](https://issues.apache.org/jira/browse/CALCITE-3926)
=> [CALCITE-3926] CannotPlanException when an empty LogicalValues requires a certain collation

core/src/main/java/org/apache/calcite/rel/type/RelDataTypeSystemImpl.java, core/src/main/java/org/apache/calcite/sql/SqlSplittableAggFunction.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java, core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java, core/src/test/resources/sql/agg.iq
Pull request for https://issues.apache.org/jira/browse/CALCITE-3866
As for aggregate function sum, most of the time, its return type is  equal to its operand's type, but if its operand's type has precision, the precision of the result may be larger than the oeprans's type. So may be we can set precision to the Max value if the oeprand's type has precision, especially for the type decimal.
=> [CALCITE-3866]  "numeric field overflow" when running the generated SQL in PostgreSQL

core/src/main/java/org/apache/calcite/rel/rules/ProjectJoinTransposeRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
Remove traitset mapping that was added to ProjectJoinTransposeRule by
CALCITE-3353. Now it becomes obsolete, we should fail fast if that happens.
Otherwise, all the downstream projects that uses this rule will be wasted time
to deal with traitsets they don't need.
JIRA: CALCITE-4009
=> [CALCITE-4009] Remove traitset remapping in ProjectJoinTransposeRule

core/src/main/java/org/apache/calcite/tools/RelBuilder.java
The RelBuilder#field method that creates a RexNode based on alias + fieldName throws an IllegalArgumentException if the corresponding field is not found.
However, the exception message does not include the requested alias & fieldName, which is relevant information, definitively useful for troubleshooting.
=> [CALCITE-4043] Improve IllegalArgumentException message in RelBuilder#field

core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java, core/src/test/java/org/apache/calcite/test/MaterializedViewSubstitutionVisitorTest.java
https://issues.apache.org/jira/browse/CALCITE-4040
=> [CALCITE-4040] An aggregate function that does not support roll up throws an exception when it is rolled up

core/src/main/java/org/apache/calcite/runtime/ConsList.java, core/src/main/java/org/apache/calcite/util/graph/Graphs.java, core/src/test/java/org/apache/calcite/util/graph/DirectedGraphTest.java
Currently, we have `Graphs#makeImmutable` to compute the shortest paths between all pairs of nodes. For many scenarios, however, we do not need the exact paths between nodes. Instead, we are only interested in the lengths of the shortest paths.
To get the path length, we need to get the shortest path first, which is returned as a `List`, then we call the `List#size()` method. According to the current implementation, the returned list is of type `ConsList`. The time complexity of `ConsList#size` is O(p) (p is the number of vertices on the path), which is inefficient.
In this issue, we revise the implementation of `ConsList#size` so that it takes O(1) time. In addition, we also give a utiltiy to get the shortest distances between nodes.
=> [CALCITE-4049] Reduce the time complexity of getting shortest distances

core/src/main/java/org/apache/calcite/sql2rel/RelFieldTrimmer.java, core/src/main/java/org/apache/calcite/tools/RelBuilder.java, core/src/test/java/org/apache/calcite/sql2rel/RelFieldTrimmerTest.java
Jira: [CALCITE-4055](https://issues.apache.org/jira/browse/CALCITE-4055)
The trimmed plan generated by RelFieldTrimmer can lose the hints that might be present in the input plan.
=> [CALCITE-4055] RelFieldTrimmer loses hints

cassandra/src/main/java/org/apache/calcite/adapter/cassandra/CassandraSchema.java
Fixes the constructor
I am not entirely sure of how to test this... The existing tests are more integration test like, so to test the default port constructor we would need to modify the embedded Cassandra to listen on port 9042, which may cause issues on hosts where a Cassandra instance is already running.
If you have a preferred way please give me feedback and I will add a test accordingly :)
=> [CALCITE-3907] Use username and password for Cassandra also when not specifying port

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableUncollect.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableUncollectTest.java
Jira: https://issues.apache.org/jira/browse/CALCITE-4063
There is a mismatch regarding what an UNNEST of a "simple" ROW (just 1 item) is expected to return as element type (scalar), and what its enumerable actually returns (List).
Solves the issue by using a special lambda for selectMany in these situations.
=> [CALCITE-4063] Unnest an array of single-item structs causes ClassCastException

core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java, core/src/test/java/org/apache/calcite/test/catalog/MockCatalogReaderSimple.java
The name of the table implies that all columns are nullable so to avoid confusion 'ENAME' is also made nullable.
=> [CALCITE-4075] Mock table 'EMPNULLABLES' should allow nulls in all non-pk columns

core/src/main/java/org/apache/calcite/runtime/JsonFunctions.java, core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java, core/src/test/java/org/apache/calcite/test/SqlJsonFunctionsTest.java
As illustrated in [CALCITE-3941](https://issues.apache.org/jira/browse/CALCITE-3941)
=> [CALCITE-3941] Add the default strict mode to the path in the Json functions

core/src/main/java/org/apache/calcite/plan/ConventionTraitDef.java, core/src/main/java/org/apache/calcite/plan/RelOptMaterializations.java, core/src/main/java/org/apache/calcite/runtime/ConsList.java, core/src/main/java/org/apache/calcite/util/graph/Graphs.java, core/src/test/java/org/apache/calcite/util/graph/DirectedGraphTest.java
According to the discussion in the JIRA, we revert the changes to ConsList class, and replace shortest distances with the shortest paths.
=> [CALCITE-4049] Improve the implementation of the shortest-path algorithm

core/src/main/java/org/apache/calcite/plan/volcano/OptimizeTask.java, core/src/main/java/org/apache/calcite/plan/volcano/RelSet.java, core/src/main/java/org/apache/calcite/plan/volcano/RelSubset.java
If the child subset is used to derive new traits for current relnode, the
subset will be marked REQUIRED when registering the new derived relnode and
later will add enforcers between other delivered subsets.  e.g. a MergeJoin
request both inputs hash distributed by [a,b] sorted by [a,b]. If the left
input R1 happens to be distributed by [a], the MergeJoin can derive new traits
from this input and request both input to be distributed by [a] sorted by
[a,b]. In case there is a alternative R2 with ANY distribution in the left
input's RelSet, we end up with requesting hash distribution [a] on alternative
R2, which is unnecessary and waste, because we request distribution by [a]
because of R1 can deliver the exact same distribution and we don't need to
enforce properties on other subsets that …
=> [CALCITE-4097] Avoid requesting unnecessary trait request when deriving traits

core/src/main/java/org/apache/calcite/sql/SqlHopTableFunction.java, core/src/main/java/org/apache/calcite/sql/SqlTumbleTableFunction.java, core/src/main/java/org/apache/calcite/sql/SqlWindowTableFunction.java, core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java, core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java, core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
The scope of SqlWindowTableFunction is special because all its operands
(except the first) should have the fucntion's first operand's scope, the
first operand is always an explicit table reference.
While this is not the perfect solution, the more proper way is to
refactor the CURSOR constructor, and always uses its queries scope. The
current CURSOR has some problems:
* It always has a type with name SqlTypeName#CURSOR, in the table
function senario, it is hard to do an auxiliary fields type infernece;
* It finally translates as an invocation with format "cast($0): CURSOR", the '$0' means
the first input, which is a wrong translation;
* It does not belong to the SQL standard.
A 'TABLE' constructor may be a good substitution.
=> [CALCITE-4077] Exception when joined with built-in table functions

core/src/test/java/org/apache/calcite/runtime/EnumerablesTest.java, core/src/test/java/org/apache/calcite/test/RelMetadataTest.java, linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
[[CALCITE-3834](https://issues.apache.org/jira/browse/CALCITE-3834)] Support AntiJoin in EnumerableMergeJoin
=> [CALCITE-3834] Support AntiJoin in EnumerableMergeJoin

core/src/main/codegen/templates/Parser.jj, core/src/main/java/org/apache/calcite/sql/parser/SqlParser.java, core/src/main/java/org/apache/calcite/sql/parser/SqlParserUtil.java, core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java, core/src/test/java/org/apache/calcite/sql/parser/parserextensiontesting/ExtensionSqlParserTest.java, core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
When the parser encounters a reserved-keyword and throws, change the
error message format to:
Incorrect syntax near the keyword '{keyword}' at line {line_number}, column {column_number}.
The new format indicates that the next token is a keyword clearly so
that user can choose to use a non-reserved keyword or quotes the keyword instead.
=> [CALCITE-4115] Improve the prompt of using SQL keywords for sql parser

core/src/main/codegen/templates/Parser.jj
Add the expected tokens so that the non-identifier context error
messages does not become worse.
=> Following [CALCITE-4115], add expected tokens to the error message

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableAggregateBase.java, core/src/main/java/org/apache/calcite/adapter/enumerable/NestedBlockBuilder.java, core/src/main/java/org/apache/calcite/adapter/enumerable/NestedBlockBuilderImpl.java, core/src/main/java/org/apache/calcite/adapter/enumerable/RexToLixTranslator.java, core/src/main/java/org/apache/calcite/adapter/enumerable/StrictAggImplementor.java, core/src/main/java/org/apache/calcite/adapter/enumerable/impl/WinAggResultContextImpl.java, core/src/main/java/org/apache/calcite/interpreter/AggregateNode.java
Since `RexNode`'s nullable state is immutable, we can safely remove unused code that changes and tracks `RexNode`'s nullable.
=> [CALCITE-4116] Remove unused code for tracking RexNode's nullable state in codegen

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoin.java
Minor change.
EnumerableMergeJoin should have a protected constructor (instead of package private), in case downstream projects require to extend it.
This is already the case with other join operators, which provide a protected constructor, e.g.: EnumerableHashJoin, EnumerableNestedLoopJoin, EnumerableBatchNestedLoopJoin.
=> [CALCITE-4123] Make EnumerableMergeJoin constructor protected

core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleCall.java
After CALCITE-2018, we don't need to invalidate metadata query when a new
RelNode is generated during rule transformation.
=> [CALCITE-4124] Stop invalidating metadata cache in VolcanoRuleCall

core/src/main/java/org/apache/calcite/schema/impl/ListTransientTable.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableRepeatUnionTest.java
ListTransientTable#scan returns an enumerator that can potentially lead to NPE. Code should be fixed to prevent this from happening.
=> [CALCITE-4139] Prevent NPE in ListTransientTable

core/src/main/java/org/apache/calcite/rel/core/Aggregate.java, core/src/main/java/org/apache/calcite/sql/validate/AggregatingSelectScope.java, core/src/main/java/org/apache/calcite/util/ImmutableBitSet.java, core/src/main/java/org/apache/calcite/util/Util.java, core/src/test/java/org/apache/calcite/util/ImmutableBitSetTest.java
1. Improve the use of data structures
2. Extract common methods
3. Avoid expensive operations
=> [CALCITE-4102] Some improvements to aggregate related operations

core/src/main/java/org/apache/calcite/rex/RexBuilder.java, core/src/main/java/org/apache/calcite/sql/type/SqlTypeUtil.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java, core/src/test/java/org/apache/calcite/rex/RexBuilderTest.java, core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java, core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml, core/src/test/resources/sql/misc.iq
JIRA: https://issues.apache.org/jira/browse/CALCITE-4081
=> [CALCITE-4081] Round-tripping a DECIMAL literal throws validation error

core/src/main/java/org/apache/calcite/rel/metadata/ReflectiveRelMetadataProvider.java
Jira ticket: [CALCITE-4156](https://issues.apache.org/jira/browse/CALCITE-4156)
ReflectiveRelMetadataProvider's constructor verifies that it is not created with an empty map, using an assertion. However, this is not the most reliable way of verifying this situation, since assertions can be deactivated. In such scenario, we could silently end up having an invalid ReflectiveRelMetadataProvider, with no actual methods attached.
Also, since the map is private and has no getter, there is no way for a caller module to verify this situation on its side.
For this reason, it is proposed a minor change: replace the assertion with an IllegalArgumentException, which will work in 100% of the cases and will always prevent constructing an invalid ReflectiveRelMetadataProvider.
=> [CALCITE-4156] ReflectiveRelMetadataProvider constructor should throw an exception (instead of assertion) when called with an empty map

core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java, core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
The root cause is that the COALESCE operand type was wrongly replaced by
`SqlToRelConverter#adjustInputRef`, actually, for an agg as bb root, there is
no need to do such adjust. Because the nullability does not change and
the agg type is not same with the bb's scope.
Tweak the `#adjustInputRef` to only fix type nullability, if there
are cases that the type name also changes, just return the original node and
let the subsequent conversion work flow throw.
=> [CALCITE-4167] Group by COALESCE IN throws NullPointerException

.github/workflows/main.yml, build.gradle.kts, gradle.properties, settings.gradle.kts
The commit configures local build cache, and it delegates
Gradle execution to burrunan/gradle-cache-action.
It unlocks fine-grained remote build cache with GitHub Actions backend
(=faster builds), and it adds error markers
(e.g. compilation errors right in the commit diffs)
See https://github.com/burrunan/gradle-cache-action#gradle-cache-action
=> [CALCITE-4168] Configure Gradle local build cache

core/src/main/java/org/apache/calcite/sql/fun/SqlCastFunction.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableStringComparisonTest.java
Jira: [CALCITE-4195](https://issues.apache.org/jira/browse/CALCITE-4195)
Problem related to the feature CALCITE-3951.
A cast operation from a character type to another character type that has a different collator must be evaluated as not monotonic. Currently this is not the case.
This has an impact e.g. in SortProjectTransposeRule, since we can incorrectly transpose a sort after a projection than contains such a cast, and we end up with a plan that will return a different result than the original one.
=> [CALCITE-4195] Cast between types with different collators must be evaluated as not monotonic

core/src/main/java/org/apache/calcite/rel/metadata/RelMdUniqueKeys.java, core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
JIRA: https://issues.apache.org/jira/projects/CALCITE/issues/CALCITE-4203
=> [CALCITE-4203] RelMdUniqueKeys should not return empty when meeting Intersect and Minus if its input has unique keys

core/src/main/java/org/apache/calcite/plan/RelOptUtil.java, core/src/main/java/org/apache/calcite/rel/externalize/RelDotWriter.java, core/src/main/java/org/apache/calcite/rel/externalize/RelWriterImpl.java, core/src/main/java/org/apache/calcite/sql/SqlExplainFormat.java, core/src/test/java/org/apache/calcite/plan/RelWriterTest.java, core/src/test/java/org/apache/calcite/plan/volcano/VolcanoPlannerTest.java, core/src/test/java/org/apache/calcite/test/HepPlannerTest.java, core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
From time to time, we want to visualize the plan generated the optimizer as a DAG (Directed Acyclic Graph). This gives us an overview of the plan, and helps us to find problems with the plan quickly.
A common way to visualize a DAG is to dump it in the dot format, and then display the DAG through GraphViz. Currently, we already have a utility to dump the Volcano planner in dot format. In this issue, we want to dump a RelNode plan (a RelNode DAG) in the dot format, which will help users to see their plans more clearly.
The utility should have some options that allow users to specify the visuzalization details, for example:
1. the max length of a node description.
2. whether RelSubset/HepRelVertex should be displayed.
3. Nodes that should be highlighted.
=> [CALCITE-4197] Provide utility to visualize RelNode plans

core/src/main/java/org/apache/calcite/plan/RelOptPredicateList.java, core/src/test/resources/sql/misc.iq
Fixes root cause in RelOptPredicateList#isEffectivelyNotNull
=> [CALCITE-4258] SqlToRelConverter: SELECT 1 IS [NOT] DISTINCT FROM NULL fails with AssertionError

core/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnUniqueness.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMdDistinctRowCount.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMdUtil.java, core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
1. For {{RelMdColumnUniqueness#areColumnsUnique(RelSubset, RelMetadataQuery,
ImmutableBitSet, boolean)}}, we can return early as we encounter the first null.
2. For {{RelMdDistinctRowCount#getDistinctRowCount(Values, RelMetadataQuery,
ImmutableBitSet, RexNode)}}, we can get the distinct row count accurately, instead of guessing that half of the elements are distinct. 
3. RelMdUtil#areColumnsDefinitelyUniqueWhenNullsFiltered could be implemented in a more efficient way.
=> [CALCITE-4241] Some improvements to metadata query

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoin.java
[CALCITE-4275] EnumerableMergeJoin#create does not set EnumerableConvention in the trait set
=> [CALCITE-4275] EnumerableMergeJoin#create does not set EnumerableConvention in the trait set

.idea/vcs.xml
A small aid to make commit messages a bit more structured when using the IntelliJ.
=> Enable commit message inspection on IntelliJ IDEA

core/src/main/java/org/apache/calcite/sql/SqlHopTableFunction.java, core/src/main/java/org/apache/calcite/sql/SqlSessionTableFunction.java, core/src/main/java/org/apache/calcite/sql/SqlTumbleTableFunction.java, core/src/main/java/org/apache/calcite/sql/SqlWindowTableFunction.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
This PR try to make the key descriptor optional in SESSION table function
* Handling the optional key descriptor when checking operand  types
* Add validation and checks for operands of time column descriptor
=> [CALCITE-4176] Key descriptor can be optional in SESSION table function

core/src/main/java/org/apache/calcite/rel/type/RelDataType.java, core/src/main/java/org/apache/calcite/rel/type/RelDataTypeImpl.java
See https://issues.apache.org/jira/browse/CALCITE-4214
=> [CALCITE-4214] Make RelDataType.getSqlTypeName non-nullable

gradle.properties
Gradle defaults to 256m which seems to be too small
=> Add MaxMetaspaceSize=512m to avoid metaspace issues when building Calcite

core/src/main/java/org/apache/calcite/rel/rules/AggregateJoinRemoveRule.java, core/src/main/java/org/apache/calcite/rel/rules/ProjectJoinRemoveRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
See https://issues.apache.org/jira/browse/CALCITE-4287
=> [CALCITE-4287] AggregateJoinRemoveRule and ProjectJoinRemoveRule are not fired if the last column of the join's left input is referenced

core/src/main/java/org/apache/calcite/sql/type/CompositeOperandTypeChecker.java, core/src/test/java/org/apache/calcite/test/MockSqlOperatorTable.java, core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java, core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
Root cause is:
The minMin function of CompositeOperandTypeChecker should return the minimum of lower bound of all SqlOperandCountRange.This PR will fix it.
=> [CALCITE-4295] Composite of two checkers with SqlOperandCountRange throws IllegalArgumentException

core/src/main/java/org/apache/calcite/adapter/java/ReflectiveSchema.java, core/src/main/java/org/apache/calcite/plan/RelTraitSet.java, core/src/main/java/org/apache/calcite/prepare/RelOptTableImpl.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMdCollation.java, core/src/main/java/org/apache/calcite/rel/rules/materialize/MaterializedViewRule.java, core/src/main/java/org/apache/calcite/schema/Statistic.java, core/src/main/java/org/apache/calcite/schema/Statistics.java, core/src/main/java/org/apache/calcite/sql/SqlBinaryOperator.java, core/src/main/java/org/apache/calcite/sql/SqlPrefixOperator.java, core/src/main/java/org/apache/calcite/sql/fun/SqlExtractFunction.java, core/src/main/java/org/apache/calcite/sql/fun/SqlFloorFunction.java, core/src/main/java/org/apache/calcite/sql/fun/SqlMonotonicBinaryOperator.java, core/src/main/java/org/apache/calcite/sql/fun/SqlSubstringFunction.java, core/src/main/java/org/apache/calcite/sql/validate/IdentifierNamespace.java, core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorUtil.java, core/src/main/java/org/apache/calcite/sql2rel/RelFieldTrimmer.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterStructsTest.java
null means the statistic is not known,
emptyList means the statistic is known, and the value is empty
See https://issues.apache.org/jira/browse/CALCITE-4215
=> [CALCITE-4215] Ensure org.apache.calcite.schema.Statistic uses null vs emptyList appropriately

bom/build.gradle.kts
It enables to configure version constraints for all Jackson modules at once.
=> Use jackson-bom to specify Jackson versions

core/src/main/java/org/apache/calcite/runtime/ResultSetEnumerable.java
This reduces the likelihood of javac issues.
See https://github.com/policeman-tools/forbidden-apis/issues/173
=> Refactor ResultSetEnumerable to avoid try-catch in nested lambdas

site/_docs/adapter.md
Method result() now returns an int value, as required by the method signature
(Alexander Trushev)
=> Site: fix aggregate function doc

.travis.yml, buildSrc/build.gradle.kts
Remove files that change often from Travis cache, remove broken files automatically
The cache itself is useful, however, there might be two problems:
* Corrupted files might get cached, so the subsequent builds would fail
* Too large cache might slowdown the build
https://github.com/vlsi/cleanup-gradle-cache solves both issues.
The cache itself is still re-uploaded on every build (see "store build cache"),
so it might need more investigations.
=> Improve caching of .gradle folder at Travis

core/src/test/java/org/apache/calcite/plan/volcano/VolcanoPlannerTest.java, plus/src/test/java/org/apache/calcite/adapter/tpch/TpchTest.java
As Calcite is evolving, more and more queries are supported now. It would be nice to enable more tests to show what Calcite can achieve.
=> Enable more tests in TpchTest

core/src/main/java/org/apache/calcite/rel/RelFieldCollation.java, core/src/test/java/org/apache/calcite/rel/RelCollationTest.java
Please see https://issues.apache.org/jira/browse/CALCITE-4350
=> [CALCITE-4350] The reverse operation of collation direction is overly relaxed

core/src/main/java/org/apache/calcite/sql/SqlMatchRecognize.java, core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
The PR fixes the list of returned operands in `SqlMatchRecognize`. Without the change e.g. `SqlShuttle` cannot be used with `MATCH_RECOGNIZE` clause.
=> [CALCITE-4390] Fix SqlMatchRecognize operand list

core/src/main/java/org/apache/calcite/sql/type/SqlTypeUtil.java, core/src/test/java/org/apache/calcite/sql/type/SqlTypeUtilTest.java
Please see https://issues.apache.org/jira/browse/CALCITE-4392
=> [CALCITE-4392] The operation of checking types equal ignoring null can be more efficient

core/src/main/java/org/apache/calcite/sql/SqlCall.java, core/src/test/java/org/apache/calcite/sql/test/SqlEqualsDeepTest.java
The method equalsDeep of SqlCall will returns wrong result when used to compare count and count_distinct, because it does not compare the functionQuantifier
=>  [CALCITE-4402] SqlCall#equalsDeep does not take into account the function quantifier

core/src/main/java/org/apache/calcite/rel/type/RelDataTypeImpl.java, core/src/test/java/org/apache/calcite/test/RelBuilderTest.java
Jira: [CALCITE-4409](https://issues.apache.org/jira/browse/CALCITE-4409)
=> [CALCITE-4409] Improve exception when RelBuilder tries to create a field on a non-struct expression

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLikeOperator.java, core/src/main/java/org/apache/calcite/tools/RelBuilder.java, core/src/test/java/org/apache/calcite/test/RelBuilderTest.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/PredicateAnalyzer.java
Jira: [CALCITE-4415](https://issues.apache.org/jira/browse/CALCITE-4415)
PR based on removing rex implementor for NOT_LIKE and NOT_SIMILAR_TO
=> [CALCITE-4415] SqlStdOperatorTable.NOT_LIKE has a wrong implementor

core/src/main/java/org/apache/calcite/rex/RexChecker.java, core/src/main/java/org/apache/calcite/rex/RexFieldAccess.java, core/src/test/java/org/apache/calcite/rex/RexBuilderTest.java
For the index of a RexFieldAccess, the correct range should be `[0, refType.getFieldList().size())`.
However, according to the current implementation of RexChecker#visitFieldAccess, the valid range is `[0, refType.getFieldList().size()]`
=> [CALCITE-4435] Incorrect logic for validating RexFieldAccess

core/src/main/java/org/apache/calcite/util/graph/DefaultEdge.java, core/src/test/java/org/apache/calcite/util/graph/DirectedGraphTest.java
It is convenient to build a graph as an object of `DefaultDirectedGraph`. The class has a good `toString` implementation, which greatly helps examining the structure of the graph.
However, the output of the method may be confusing. In our system, the `toString` method produces the following result:
```
graph(vertices: [0, 1, 2, 3, 4, 5, 6], edges: [org.apache.calcite.util.graph.DefaultEdge@1a550334, 
org.apache.calcite.util.graph.DefaultEdge@891ce8a1, org.apache.calcite.util.graph.DefaultEdge@ba5c5190, 
org.apache.calcite.util.graph.DefaultEdge@c894f6b3, org.apache.calcite.util.graph.DefaultEdge@d72993fe, 
org.apache.calcite.util.graph.DefaultEdge@da030cc4, org.apache.calcite.util.graph.DefaultEdge@de17986f, 
org.apache.calcite.util.graph.DefaultEdge@e20be355, …
```
=> [CALCITE-4425] Class DefaultEdge lacks a proper toString implementation (Liya Fan)

core/src/main/java/org/apache/calcite/rex/RexExecutorImpl.java
Jira: [CALCITE-4453](https://issues.apache.org/jira/browse/CALCITE-4453)
=> [CALCITE-4453] RexExecutorImpl#compile should use RexBuilder's type factory if possible

.github/workflows/cancel-duplicates.yml
It should reduce CI load when PR or branch is updated often
See https://github.com/potiuk/cancel-workflow-runs#most-often-used-canceling-example
=> Cancel stale workflows in GitHub Actions CI

bom/build.gradle.kts, build.gradle.kts, gradle.properties, settings.gradle.kts
The PR adds optional (disabled by default) verification.
Verification can be performed with `./gradlew -PskipJandex=false jandex`
=> [CALCITE-4470] Add optional bytecode verification with Jandex

build.gradle.kts, gradle.properties
Here's the relevant jandex release notice: https://github.com/wildfly/jandex/pull/104#issuecomment-765690070
=> [CALCITE-4459] Verify the bytecode with Jandex by default

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
See https://docs.gradle.org/6.8/release-notes.html
- Faster Kotlin DSL script compilation
- Vendor selection for Java toolchains
- Task execution in composite builds
- Consistent dependency resolution
=> Bump Gradle 6.7 -> 6.8.1

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableAggregateRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableBatchNestedLoopJoinRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableCalcRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableCorrelateRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableFilterRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableIntersectRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableJoinRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableLimitSortRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMatchRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoinRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMinusRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableProjectRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableRepeatUnionRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableSortedAggregateRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableFunctionScanRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableModifyRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableScanRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableSpoolRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableUnionRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableValuesRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableWindowRule.java
This PR removes casts to `Logical` operators in `Enumerable` rules.
=> [CALCITE-4461] Do not use `Logical` nodes inside Enumerable rules (Vladimir Ozerov)

.github/workflows/buildcache.yml, .github/workflows/main.yml, gradle.properties, settings.gradle.kts
Cache build artifacts, so expensive operations (e.g. compileJava, javadoc) do not need to be re-computed
The logic is as follows:
1. Cache is populated only in CI that has S3_BUILD_CACHE_ACCESS_KEY_ID and S3_BUILD_CACHE_SECRET_KEY (GitHub Actions in the master branch)
2. Otherwise the cache is read-only (e.g. every day builds and PR builds)
=> [CALCITE-4140] Use Wasabi S3 for remote build cache

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeUnion.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeUnionRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableRules.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMdCollation.java, core/src/main/java/org/apache/calcite/tools/Programs.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/test/java/org/apache/calcite/runtime/EnumerablesTest.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableMergeUnionTest.java, linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java, linq4j/src/main/java/org/apache/calcite/linq4j/MergeUnionEnumerator.java
Jira: [CALCITE-3221](https://issues.apache.org/jira/browse/CALCITE-3221)
- New operator EnumerableMergeUnion
- New rule EnumerableMergeUnionRule
- Implementation via EnumerableDefaults#mergeUnion
- Unit tests
=> [CALCITE-3221] Add MergeUnion operator in Enumerable convention

server/src/main/java/org/apache/calcite/server/ServerDdlExecutor.java, server/src/test/java/org/apache/calcite/test/ServerTest.java
See https://issues.apache.org/jira/browse/CALCITE-4533 for the details.
=> [CALCITE-4533] Fix handling of REPLACE and IF NOT EXISTS keywords for CREATE TABLE/SCHEMA commands (Vladimir Ozerov)

build.gradle.kts, core/src/test/java/org/apache/calcite/materialize/NormalizationTrimFieldTest.java, core/src/test/java/org/apache/calcite/test/AbstractMaterializedViewTest.java, core/src/test/java/org/apache/calcite/test/Matchers.java, core/src/test/java/org/apache/calcite/test/Unsafe.java, core/src/test/java/org/apache/calcite/util/UtilTest.java, example/function/build.gradle.kts, src/main/config/forbidden-apis/signatures.txt
Matcher#matches is only needed when implementing new Matcher implementations
which is very rare.
The common test pitfall is
assertThat(contains(actual).matches(expected), is(true))
It should better be written as
assertThat(actual, contains(expected))
=> Add Matcher#matches to ForbiddenApis to avoid its accidental use

core/src/main/java/org/apache/calcite/rel/core/Correlate.java, core/src/main/java/org/apache/calcite/rel/core/Filter.java, core/src/main/java/org/apache/calcite/rel/core/Snapshot.java, core/src/main/java/org/apache/calcite/rel/logical/LogicalCorrelate.java, core/src/main/java/org/apache/calcite/rel/logical/LogicalFilter.java
Validate preconditions in the constructor of Filter, Correlate, and
Snapshot regardless if CalciteSystemProperty.DEBUG is enabled or not.
To avoid the performance overhead in production the assertions can be
disabled as it usually happens.
=> [CALCITE-4570] Always validate preconditions in Filter/Correlate/Snapshot expressions when assertions are enabled

core/src/main/java/org/apache/calcite/plan/RelOptUtil.java, core/src/main/java/org/apache/calcite/rel/type/RelDataTypeImpl.java, core/src/main/java/org/apache/calcite/rex/RexLiteral.java, core/src/main/java/org/apache/calcite/sql/type/SqlTypeUtil.java, core/src/test/java/org/apache/calcite/rex/RexBuilderTest.java, core/src/test/java/org/apache/calcite/rex/RexProgramTest.java, core/src/test/java/org/apache/calcite/rex/RexProgramTestBase.java, core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java, core/src/test/java/org/apache/calcite/sql/test/SqlTests.java, core/src/test/java/org/apache/calcite/test/CalciteAssert.java
We find weird literals for some user defined non-nullable types. Some investigation shows that the problem lies in the `RexLiteral#toJavaString` method.
In particular, it checks the type string suffix with an 8-character string:
```
if (!fullTypeString.endsWith("NOT NULL")) {
```
However, it trims the last 9 characters from the end of the string:
```
sb.append(fullTypeString, 0, fullTypeString.length() - 9);
```
=> [CALCITE-4510] RexLiteral can produce wrong digest for some user defined types

core/src/main/java/org/apache/calcite/schema/SchemaFactory.java
Currently, The href of `example CSV adapter` in `SchemaFactory`'s JavaDoc is invalid, this pr fix it
=> [CALCITE-4601] The example CSV adapter URL in SchemaFactory JavaDoc is invalid

gradle.properties
Update org.owasp.dependencycheck.version to 6.1.6 to resolve the problem.
=> [CALCITE-4613] OWASP dependency-check tasks fail due to missing resources

release/build.gradle.kts
1. Remove broken links.
2. Remove docker build instructions (there is no docker-compose file for Calcite).
3. Use GitHub URL to preview release notes.
4. Add subject template.
=> [CALCITE-4312] Improve content of prepareVote draft email

core/src/main/java/org/apache/calcite/rex/RexSimplify.java, core/src/test/java/org/apache/calcite/rex/RexProgramTest.java, core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml, core/src/test/resources/sql/misc.iq, druid/src/test/java/org/apache/calcite/test/DruidAdapter2IT.java, druid/src/test/java/org/apache/calcite/test/DruidAdapterIT.java
Some simple arithmetic operations can be simplified, for example:
```
a + 0 = a
a - 0 = a
a * 1 = a
a / 1 = a
```
In our product, we found such scenarios are fairly frequently encountered. For example, some SQL programmers use a * 1.0 as a convenient way to cast `a` to floating point type.
=> [CALCITE-4420] Some simple arithmetic operations can be simplified

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableBatchNestedLoopJoin.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeUnion.java
See [CALCITE-4741](https://issues.apache.org/jira/browse/CALCITE-4741)
=> [CALCITE-4741] AbstractRelNode#getId can overflow into a negative value causing CompileException in certain Enumerable implement methods

core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java, core/src/test/java/org/apache/calcite/test/SqlToRelTestBase.java, core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
When disable the sql validator to expand identifier, using function expr in the partition by list of over window will cause exception. See [jira:CALCITE-4584](https://issues.apache.org/jira/browse/CALCITE-4584) for mode details.
=> [CALCITE-4584] Using function in partition by list of over window cause converting exception

core/src/main/java/org/apache/calcite/rel/core/Correlate.java
Enforce the implicit class invariant (see Correlate#getRequiredColumns) via assertion to prevent construction of invalid plans and fail fast.
=> [CALCITE-4784] Ensure Correlate#requiredColumns is subset of columns in left relation

README.md
CALCITE-4796 Travis links in README.md should point to 'app.travis-ci.com' instead of 'travis-ci.org'
=> [CALCITE-4796] Travis links in README.md are broken

cassandra/src/test/java/org/apache/calcite/test/CassandraAdapterDataTypesTest.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/EmbeddedElasticsearchNode.java
The PR comprises two commits:
1. ElasticSearch: Replace deprecated `com.google.common.io.Files.createTempDir()` with `java.nio.file.Files.createTempDirectory()` in ElasticSearch tests
2. Cassandra: Finally the test failure for Cassandra was related to retrieving a timestamp, whose result depends on the user timezone (that's why it was failing on different timezones). The solution is to dynamically compute the expected timestamp output value depending on the user timezone.
The changes have been validated locally as follow to cover different guava versions and timezones (for the latter, I have applied the patch from #2534):
```bash
guavas=(19.0 25.0-jre 30.1.1-jre)
timezones=(America/New_York UTC GMT Europe/Paris America/Los_Angeles)
for g in ${guavas[@]}; do
for tz in ${timezones[@]}; do …
```
=> [CALCITE-4793] Fix Cassandra and ElasticSearch tests

core/src/main/java/org/apache/calcite/sql2rel/RelDecorrelator.java, core/src/test/resources/sql/unnest.iq
See Jira: [CALCITE-4773](https://issues.apache.org/jira/browse/CALCITE-4773)
=> [CALCITE-4773] RelDecorrelator's RemoveSingleAggregateRule can produce result with wrong row type

core/src/test/java/org/apache/calcite/test/JdbcTest.java, linq4j/src/main/java/org/apache/calcite/linq4j/tree/ConstantExpression.java, linq4j/src/test/java/org/apache/calcite/linq4j/test/ExpressionTest.java
[CALCITE-4532](https://issues.apache.org/jira/browse/CALCITE-4532)
=> [CALCITE-4532] Correct code generated for primitive-object ConstantExpression

build.gradle.kts
[CALCITE-4790] Make Gradle pass the 'user.timezone' property to the test JVM
=> [CALCITE-4790] Make Gradle pass the 'user.timezone' to test JVM

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableBatchNestedLoopJoinRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableCalcRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableCorrelateRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableFilterRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableFilterToCalcRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableLimitRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableLimitSortRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeUnionRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableProjectRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableProjectToCalcRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableFunctionScanRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableTableScanRule.java, core/src/main/java/org/apache/calcite/interpreter/Bindables.java, core/src/main/java/org/apache/calcite/plan/CommonRelSubExprRule.java, core/src/main/java/org/apache/calcite/plan/volcano/AbstractConverter.java, core/src/main/java/org/apache/calcite/rel/convert/ConverterRule.java, core/src/main/java/org/apache/calcite/rel/rules/PruneEmptyRules.java, core/src/main/java/org/apache/calcite/rel/rules/ValuesReduceRule.java, core/src/main/java/org/apache/calcite/rel/stream/StreamRules.java
This is a follow up to CALCITE-4787 to move the rest of the core/main off ImmutableBeans
=> [CALCITE-4825] Move remaining core/main off of ImmutableBeans

gradle/wrapper/gradle-wrapper.properties
Gradle 7.3 is the first release with the official support of Java 17
See https://docs.gradle.org/7.3/release-notes.html
=> Update Gradle to 7.3

core/src/main/java/org/apache/calcite/prepare/Prepare.java, core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/test/resources/sql/sub-query.iq, testkit/src/main/java/org/apache/calcite/test/QuidemTest.java
…o Values, and gives incorrect results
=> [CALCITE-4844] IN-list that references columns is wrongly converted to Values, and gives incorrect results

.asf.yaml
See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-pull-request-commits
Unfortunately, the button loses `committer` info as follows (it uses GitHub noreply for committer):
```
commit a8e50734e0460e506f1762fbe0f628bcb444b8f5
Author: Denys Kuzmenko <dk...@cloudera.com>
AuthorDate: Tue Nov 30 10:09:06 2021 +0200
Commit: GitHub <no...@github.com>
CommitDate: Tue Nov 30 09:09:06 2021 +0100
```
=> Clarify why squash commits option in GitHub PR merge is disabled

core/src/main/java/org/apache/calcite/sql2rel/RelFieldTrimmer.java, core/src/test/java/org/apache/calcite/sql2rel/RelFieldTrimmerTest.java
fix RelFieldTrimmer incorrectly drops calc condition when there is no field used by the upper 
https://issues.apache.org/jira/browse/CALCITE-4783
=> [CALCITE-4783] RelFieldTrimmer incorrectly drops filter condition

core/src/main/java/org/apache/calcite/prepare/Prepare.java
Before the PR, The Log:
```
Plan after physical tweaks: EnumerableValues(tuples=[[{ 1, 'a' }, { 2, 'b' }]]): rowcount = 2.0, cumulative cost = {2.0 rows, 1.0 cpu, 0.0 io}, id = 30
```
After the PR, The Log:
```
Plan after physical tweaks:
EnumerableValues(tuples=[[{ 1, 'a' }, { 2, 'b' }]]): rowcount = 2.0, cumulative cost = {2.0 rows, 1.0 cpu, 0.0 io}, id = 30
```
=> reformat debug log about the plan which after physical tweaks

core/src/main/java/org/apache/calcite/rel/metadata/BuiltInMetadata.java, core/src/main/java/org/apache/calcite/rel/metadata/MetadataDef.java, core/src/main/java/org/apache/calcite/rel/metadata/janino/RelMetadataHandlerGeneratorUtil.java
- Add default getDef() methods.
- Mark all function metadata handler interfaces as FunctionalInterface where possible.
- Update MetdataDef and RelMetdataHandlerGeneratorUtil to ignore getDef() methods.
=> [CALCITE-4929] Implement default getDef() methods in MetadataHandler interfaces

core/src/main/java/org/apache/calcite/plan/volcano/IterativeRuleDriver.java
Remove PLANNER logging from the message and better formulate at which point during the rule matching the cost is printed.
The original message is misleading cause it is not the planner that is printed but the queue. Moreover, `IterativeRuleDriver#toString` just prints the class name and hashcode of the instance which is useless. 
Class name might be useful but can be obtained by changing the logger configuration (pattern layout).
```
PLANNER = org.apache.calcite.plan.volcano.IterativeRuleDriver@3f3065ea; COST = {inf}
...
PLANNER = org.apache.calcite.plan.volcano.IterativeRuleDriver@3f3065ea; COST = {11.0 rows, 42.0 cpu, 0.0 io}
```
```
Best cost before rule match: {inf}
...
Best cost before rule match: {11.0 rows, 42.0 cpu, 0.0 io}
```
=> Improve debug message in IterativeRuleDriver

core/src/main/java/org/apache/calcite/rel/rules/SemiJoinRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
[[CALCITE-4941](https://issues.apache.org/jira/browse/CALCITE-4941)] SemiJoinRule loses hints
SemiJoinRule does not propagate the (potential) hints from the input Join to the output SemiJoin
=> [CALCITE-4941] SemiJoinRule loses hints

elasticsearch/build.gradle.kts, gradle.properties
Remove extra maven repository.
=> [CALCITE-4948] Revert Elasticsearch to 7.10.2

core/src/main/java/org/apache/calcite/rel/rules/AggregateUnionTransposeRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
See https://issues.apache.org/jira/browse/CALCITE-4700 for more information.
=> [CALCITE-4700] AggregateUnionTransposeRule produces wrong group sets for the top Aggregate (Vladimir Ozerov)

.github/workflows/main.yml
When tests run successfully they don't take more than a few minutes.
Sometimes though they get stuck and run forever (till the max GitHub
timeout of 6h) so set a timeout to 10minutes to avoid wasting resources
and fail-fast.
=> Set timeout for running Druid tests in GitHub CI

core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
Simplification (from `RexSimplify` class) is mostly covered in `RexProgramTest`, but tests for expressions of the form `IS NOT NULL(a) AND a=b` (with nullable and not nullable types) seem to be missing.
Since I had to write tests to make sure the simplification was as expected, I assume others might end up doing the same, and that the tests will both act as documentation and it will also protect against regressions.
=> [CALCITE-4917] Add test for 'IS NOT NULL(a) AND a=b' simplification

build.gradle.kts
The doc title should be "Apache Calcite API", but is "Apache Calcite calcite API".
=> Site: Change the Javadoc title to Apache Calcite API

core/src/main/java/org/apache/calcite/sql/dialect/MssqlSqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/SybaseSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
MS SQL doesn't allow using `FETCH` without the `ORDER BY` statement. With this change, the `TOP N` statement will be generated instead of `FETCH` to prevent such errors.
Also, added `START AT` for Sybase, since initially OFFSET was ignored there.
=> [CALCITE-4968] Use TOP N for MsSQL instead of FETCH without OFFSET

core/src/main/codegen/config.fmpp
The java.net site has closed. Update javacc official website. Help make it easier for newcomers to view the javacc documentation.
=> [MINOR] Update javacc official website

site/_docs/howto.md
Update to clarify system property value **DB** which can be `h2`, `hsqldb` etc (updated <pre>-Dcalcite.test.db=DB (where <b>db</b> is...</pre> to <pre>-Dcalcite.test.db=DB (where <b>DB</b> is...</pre>).
=> Updated to clarify DB value in system property setting

core/src/main/java/org/apache/calcite/util/Bug.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/PredicateAnalyzer.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/BooleanLogicTest.java
NamedFieldExpression is packed in CastExpression while translating bool condition.
=> [CALCITE-4965] IS NOT NULL failed in Elasticsearch Adapter

core/src/main/java/org/apache/calcite/model/JsonView.java
Corrected stream property name (`steram` to `stream`) in JsonView constructor.
=> Corrected json stream property name

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java, core/src/main/java/org/apache/calcite/sql/SqlDialect.java, core/src/main/java/org/apache/calcite/sql/SqlDialectFactoryImpl.java, core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/OracleSqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/PrestoSqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
`SELECT APPROX_COUNT_DISTINCT(product_id)
FROM foodmart.product`
will be
`SELECT COUNT(DISTINCT product_id)
FROM foodmart.product`
This can cause many tasks to run too slowly, we should keep approx_count_distinct function.
=> [CALCITE-4997] Keep APPROX_COUNT_DISTINCT in some SqlDialects

bom/build.gradle.kts, core/build.gradle.kts, core/src/main/java/org/apache/calcite/rel/metadata/MetadataDef.java, core/src/main/java/org/apache/calcite/rel/metadata/janino/RelMetadataHandlerGeneratorUtil.java, core/src/test/java/org/apache/calcite/rel/metadata/MetadataDefTest.java, core/src/test/java/org/apache/calcite/rel/metadata/MetadataHandlerTest.java, core/src/test/java/org/apache/calcite/rel/metadata/MetadataHandlerWithStaticMethod.java, core/src/test/java/org/apache/calcite/rel/metadata/TestMetadata.java, core/src/test/java/org/apache/calcite/rel/metadata/TestMetadataHandlers.java, gradle.properties
According to https://www.jacoco.org/jacoco/trunk/doc/faq.html , Jacoco
adds a synthetic static method called $jacocoInit() during
instrumentation.
MetadataDef constructor breaks if it encounters such method on
the class given to it because it does not expect it. But it looks like
it simply should not consider synthetic methods (as well as static
methods) at all.
=> [CALCITE-5008] Ignore synthetic and static methods in MetadataDef

core/src/main/java/org/apache/calcite/interpreter/TableScanNode.java, core/src/test/java/org/apache/calcite/test/ScannableTableTest.java
```sql
select a from ProjectableFilterableTable where b = 'xx'
```
The ProjectableFilterableTable will scan two times when projections and filters are different columns.
=> [CALCITE-5019] Avoid multiple scans when table is ProjectableFilterableTable

core/src/main/java/org/apache/calcite/sql/type/SqlTypeFactoryImpl.java, core/src/test/java/org/apache/calcite/sql/type/SqlTypeFactoryTest.java
[CALCITE-4872] added an UNKNOWN type that was implemented in some
places by class SqlTypeFactoryImpl.UnknownSqlType, but in others
by BasicSqlType. This would cause
SqlTypeFactoryTest.testUnknownCreateWithNullabilityTypeConsistency
to succeed or fail non-deterministically, depending on which of the
above had made it into the map of canonical type instances.
This commit solves the problem by removing class
SqlTypeFactoryImpl.UnknownSqlType and always using BasicSqlType.
=> [CALCITE-5040] SqlTypeFactoryTest.testUnknownCreateWithNullabilityTypeConsistency fails

core/src/main/java/org/apache/calcite/rel/metadata/RelMdRowCount.java, core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
This pr is to fix a minor bug: the row count of an aggregate is wrong if it is without group keys.
- Update `RelMdRowCount#getRowCount(Aggregate rel, RelMetadataQuery mq)`
- Add tests in `RelMetadataTest`
=> [CALCITE-5050] Correct rowcount of aggregate without group keys

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/JsonFunctions.java, core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/fun/SqlJsonTypeOperator.java, core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java, core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/test/java/org/apache/calcite/test/SqlJsonFunctionsTest.java, core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java, core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml, core/src/test/resources/sql/agg.iq, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
This pr makes nested json creation functions produce correct results. Before this pr, these json creation functions (json_object/json_array/json_objectagg/json_arrayagg) takes the output of inner json functions' result as raw string.
=> [CALCITE-4989] Nested JSON_OBJECT creation does not produce proper json

core/src/main/java/org/apache/calcite/rel/metadata/RelMdPredicates.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
JIRA: https://issues.apache.org/jira/browse/CALCITE-5036
Major Modification:
- simplify the condition in the filter's rel before executing the method of `getPredicates`
- change some tests to make more rigorous, link [ISSUE-5038]( https://issues.apache.org/jira/browse/CALCITE-5038)
=> [CALCITE-5036] RelMdPredicates support to analyze constant key for the operator of IS_NOT_DISTINCT_FROM

core/src/main/java/org/apache/calcite/sql/SqlDialect.java, core/src/test/java/org/apache/calcite/util/UtilTest.java
`Date and Time Patterns` can find in SimpleDateFormat Java Doc.
=> [CALCITE-5027] Incorrect format for TIMESTAMP literals in SqlDialect#quoteTimestampLiteral

core/src/main/java/org/apache/calcite/plan/RelOptUtil.java, core/src/test/java/org/apache/calcite/plan/RelOptUtilTest.java
Fix the bug for `RelOptUtil#splitJoinCondition`:
```Java
public static RexNode splitJoinCondition(
List<RelDataTypeField> sysFieldList,
List<RelNode> inputs,
RexNode condition,
List<List<RexNode>> joinKeys,
@Nullable List<Integer> filterNulls,
@Nullable List<SqlOperator> rangeOp) {
```
for following case:
```SQL
select
*
from emp left join dept
on emp.empno > 0
```
The expected result is to make `(empno > 0) = true` as the equal join key.
=> [CALCITE-5032] RelOptUtil#splitJoinCondition returns wrong when there is no equal condition

core/src/main/java/org/apache/calcite/rel/rules/AggregateReduceFunctionsRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Link to [CALCITE-5000](https://issues.apache.org/jira/browse/CALCITE-5000)
The arg of max/min exists in the aggregate's group, we could optimize it.
Such as:
`select max(a) from tbl group by a` will be optimized to `select a from tbl group by a`
=> [CALCITE-5000] Expand `AGGREGATE_REDUCE_FUNCTIONS`, when arg of agg-call is in the aggregate's group

core/src/main/java/org/apache/calcite/rel/metadata/RelMdMaxRowCount.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMdMinRowCount.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMdUtil.java, core/src/main/java/org/apache/calcite/sql2rel/RelDecorrelator.java, core/src/main/java/org/apache/calcite/tools/RelBuilder.java, core/src/test/java/org/apache/calcite/rel/metadata/RelMdUtilTest.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java, core/src/test/java/org/apache/calcite/test/RelBuilderTest.java, core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
I searched the code of `RexLiteral#intValue` in core module. Found that four class failed when LIMIT/OFFSET parameter is Dynamic. 
- RelMdMaxRowCount
- RelMdMinRowCount
- RelMdUtil
- RelDecorrelator
I fixed them, and added corresponding unit tests.
=> [CALCITE-5048] Optimizer support dynamic parameter in LIMIT/OFFSET

core/src/main/java/org/apache/calcite/rel/metadata/RelMdRowCount.java, core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
Here is the sql that fetch is deterministic and offset is dynamic 
`select * from emp order by ename limit 1 offset ?`
**RelMdRowCount#getRowCount** will return 14d, because it always return rowCount when offset is dynamic.
```
if (rel.offset instanceof RexDynamicParam) {
return rowCount;
}
```
Obviously, rowCount will not exceed 1 because LIMIT 1. We can improve it
=> [CALCITE-5091] RelMdRowCount can return more accurate rowCount

core/src/main/java/org/apache/calcite/rel/RelHomogeneousShuttle.java, core/src/main/java/org/apache/calcite/rel/logical/LogicalCalc.java, core/src/main/java/org/apache/calcite/rel/logical/LogicalTableModify.java, core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
[https://issues.apache.org/jira/browse/CALCITE-5166](https://issues.apache.org/jira/browse/CALCITE-5166)
=> [CALCITE-5166] Method accept(RelShuttle) is not overridden in LogicalCalc and LogicalTableModify

core/src/main/java/org/apache/calcite/sql/dialect/MysqlSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
ISSUE Link: https://issues.apache.org/jira/browse/CALCITE-5163
Simple Description:
MysqlSqlDialect translate function of `LISTAGG` to `GROUP_CONCAT`, when meeting `SqlKind#WITHIN_GROUP` or `SqlKind#LISTAGG`.
=> [CALCITE-5163] MysqlSqlDialect support to unparse LISTAGG aggregate function

core/src/main/java/org/apache/calcite/sql2rel/RelDecorrelator.java, core/src/main/java/org/apache/calcite/sql2rel/RelFieldTrimmer.java, core/src/main/java/org/apache/calcite/sql2rel/RelStructuredTypeFlattener.java, core/src/test/java/org/apache/calcite/test/SqlHintsConverterTest.java, core/src/test/resources/org/apache/calcite/test/SqlHintsConverterTest.xml
See details in [CALCITE-5177](https://issues.apache.org/jira/browse/CALCITE-5177).
Caused by [CALCITE-5107 - Support SQL hint for Filter, SetOp, Sort, Window, Values](https://issues.apache.org/jira/browse/CALCITE-5107), which added new Hintable RelNodes, but missed to propagate the hints for them in certain transformations (`RelDecorrelator`, `RelFieldTrimmer`, `RelStructuredTypeFlattener`).
Proposed fix: "centralizing" the hint propagation in these classes to avoid "forgetting" it for a certain RelNode in particular.
=> [CALCITE-5177] Query loses hint after decorrelation

core/src/main/java/org/apache/calcite/sql/validate/implicit/TypeCoercionImpl.java, core/src/test/java/org/apache/calcite/test/TypeCoercionConverterTest.java, core/src/test/resources/org/apache/calcite/test/TypeCoercionConverterTest.xml
Here is the sql:
```
insert into t3 
select 'a', 1.0, 1 union 
select 'b', 2, 2 union 
select 'c', 3.0, CAST(3 AS SMALLINT) union 
select 'd', 4.0, 4 union 
select 'e', 5.0, 5 
```
but the validated sql is :
```
INSERT INTO `CATALOG`.`SALES`.`T3`
SELECT 'a', CAST(1.0 AS INTEGER), CAST(1 AS SMALLINT) UNION 
SELECT 'b', 2, CAST(2 AS SMALLINT) UNION -- Encountered an integer and ended early
SELECT 'c', 3.0, CAST(3 AS SMALLINT) UNION -- Encountered an samlint and ended early
SELECT 'd', 4.0, 4 UNION -- should be cast  
SELECT 'e', 5.0, 5 -- should be cast 
```
This is why CALCITE-4458 changed '&&' to '||', the right validated sql is:
```
INSERT INTO `CATALOG`.`SALES`.`T3`
SELECT 'a', CAST(1.0 AS INTEGER), CAST(1 AS SMALLINT)
UNION
SELECT 'b', 2, CAST(2 AS SMALLINT)
UNION
SELECT 'c', CAST(3.0 …
```
=> [CALCITE-4897] Implicit type conversion is not complete for set operation in DML

core/src/main/java/org/apache/calcite/plan/RelOptUtil.java, core/src/main/java/org/apache/calcite/sql2rel/RelFieldTrimmer.java
CALCITE-5177 Query loses hint after decorrelation minor follow-up (following [this discussion](https://github.com/apache/calcite/pull/2829/files#r895412046))
=> [CALCITE-5177] Query loses hint after decorrelation (minor follow-up)

core/src/main/java/org/apache/calcite/sql/SqlSelect.java, core/src/main/java/org/apache/calcite/sql/fun/SqlInternalOperators.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java, testkit/src/main/java/org/apache/calcite/sql/parser/SqlParserTest.java
In standard SQL, the operand of union should not have limit  or order by.So parse will fail in SqlParserTetest#testLimitUnion and SqlParserTetest#OrderUnion.
However, when users use parentheses, most engines allow it. We should retain the parentheses written by users.
=> [CACLITE-5013] Retain parentheses if a setop has an LIMIT clause

gradle.properties
This is a trivial PR updating apiguardian version to 1.1.2
=> [CALCITE-5196] Bump apiguardian to 1.1.2

core/src/main/java/org/apache/calcite/rel/core/Snapshot.java, core/src/main/java/org/apache/calcite/rel/hint/HintPredicates.java, core/src/main/java/org/apache/calcite/rel/hint/NodeTypeHintPredicate.java, core/src/main/java/org/apache/calcite/rel/logical/LogicalSnapshot.java, core/src/test/java/org/apache/calcite/test/SqlHintsConverterTest.java, core/src/test/resources/org/apache/calcite/test/SqlHintsConverterTest.xml
Current, `snapshot` does not support hint yet and this blocks hint propagation to the underlying temporal table.
This pr aims to support Snapshot node.
=> [CALCITE-5251] Support SQL hint for Snapshot

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableRelImplementor.java
More info: [CALCITE-5277](https://issues.apache.org/jira/browse/CALCITE-5277)
=> [CALCITE-5277] Make EnumerableRelImplementor stashedParameters order deterministic to increase BINDABLE_CACHE hit rate

testkit/src/main/java/org/apache/calcite/test/RelOptTestBase.java, testkit/src/main/java/org/apache/calcite/test/SqlToRelTestBase.java, testkit/src/main/java/org/apache/calcite/test/SqlValidatorTestCase.java
- When I write a unit test, I often see which tables and columns are available. At present, I have to search the catalog. If there is a link to jump directly, it is very convenient.
- For new contributor, it will be easier to find the default catalog.
=> [MINOR] Add default catalog link to test fixtures

core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcSchema.java, core/src/main/java/org/apache/calcite/sql/SqlDialect.java, core/src/main/java/org/apache/calcite/sql/SqlDialectFactoryImpl.java
I used manual testing of the Drill query 
```
select * from athena.test_table limit 10 offset 3
```
where the storage plugin `athena` uses Drill's Calcite-based JDBC storage plugin. With Calcite 1.32.0 `FETCH NEXT 10 ROWS ONLY` is generated and rejected by Athena. With Calcite built from this branch the query succeeds and the expected limit and offset are applied.
A minor aside that I'd appreciate any pointers on is that Calcite prints the following to stdout for every query made against Athena.
```
Unknown table type: EXTERNAL_TABLE
```
I've seen the same thing when querying the H2 DBMS though IIRC the table type involved was different. When Drill runs in embedded mode then stdout is the same place as the user's sqlline session so these messages are quite noisy and will be disconcerting …
=> [CALCITE-5355] Use the Presto SQL dialect for AWS Athena

core/src/main/java/org/apache/calcite/rel/rules/SemiJoinRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
When rewriting the query for a semi join, the
`JoinOnUniqueToSemiJoinRule` pushes a new project via `RelBuilder`. This project is *almost* a good copy of the original `Project` -- it is just missing the field names.
This change uses `RelDataType` of the `Project` to get the field names for the new `Project` pushed on the `Relbuilder` stack. This is similar to what is done in `SemiJoinRule#perform`
#2848 introduced this rule and the bug.
=> [CALCITE-5391] JoinOnUniqueToSemiJoinRule should preserve field names, if possible

core/src/main/java/org/apache/calcite/sql/dialect/FireboltSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Adds support for the INTERVAL qualifier for [Firebolt](https://www.firebolt.io/). 
Ticket: https://issues.apache.org/jira/browse/CALCITE-5217
=> [CALCITE-5217] Add support for INTERVAL qualifier for Firebolt

core/build.gradle.kts, core/src/main/java/org/apache/calcite/runtime/ProjectionTransformer.java, site/_docs/howto.md, site/_docs/reference.md, site/_docs/spatial.md
Proj4J uses the EPSG dataset and has restricting terms of use. Making Proj4J a compileOnly dependency addresses this issue.
=> [CALCITE-5399] Remove Proj4J from the api dependencies

babel/src/test/resources/sql/select.iq, core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
PERCENT_REMAINDER operator should have the same return type inference as MOD operator.
=> [CALCITE-5410] Assertion error on PERCENT_REMAINDER operator with DECIMAL type

core/src/main/java/org/apache/calcite/runtime/SpatialTypeFunctions.java, core/src/main/java/org/apache/calcite/sql/SqlSpatialTypeOperatorTable.java, core/src/main/java/org/apache/calcite/sql/util/SqlOperatorTables.java, core/src/test/resources/sql/spatial.iq, testkit/src/main/java/org/apache/calcite/test/CalciteAssert.java
Here, the main point of caution is the creation of the operator table in `SqlLibraryOperatorTableFactory`.
=> [CALCITE-5280] Add geometry aggregate functions (ST_Accum, ST_Collect, and ST_Union)

core/src/main/java/org/apache/calcite/rel/metadata/RelMdUtil.java, core/src/test/java/org/apache/calcite/rel/metadata/RelMdUtilTest.java
According to the current implementation, the result of RelMdUtil#numDistinctVals is zero when the domain size is too big.
However, the true result should be some other positive number. We solve the problem by 3 separate cases below:
(The formulat to calculate is `N * [1 - (1 - 1 / N) ^ n]`, where N is the domain size and n is the number of selections)
1. If the values of N and n are not too big, we directly calculate the formula as N * [1 - exp(n * ln(1 - 1 / N))].
2. If the values of N or n are big, but the ratio n / N is not close to 0, we expand the exponent (n * ln(1 - 1 / N)) as a Taylor series.
3. If the values of N or n are big, and the ratio n / N is close to 0, we expand the whole formula as a Taylor series.
=> [CALCITE-4351] Improve the result of RelMdUtil#numDistinctVals for large domain sizes

core/src/main/java/org/apache/calcite/config/CalciteSystemProperty.java, core/src/main/java/org/apache/calcite/util/SaffronProperties.java
SOLR-16433 found that Calcite does not handle the Java security manager returning permission denied when checking that the calcite.test.dataset path exists. Solr runs with a security manager that doesn't allow arbitrary filesystem access. This failure causes Calcite to not load and therefore unusable.
The code in question is here: https://github.com/apache/calcite/blame/main/core/src/main/java/org/apache/calcite/config/CalciteSystemProperty.java#L189
A few other places in Calcite already check for SecurityException: https://github.com/apache/calcite/search?q=SecurityException
=> [CALCITE-5298] CalciteSystemProperty calcite.test.dataset path check fails under Java Security Manager

core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/test/resources/sql/agg.iq
The problem was that SqlRelConverter tried to convert IN sub-query inside the select list to left join, but in the current case IN sub-query in the select list refers to IN sub-query inside GROUP BY.
=> [CALCITE-5209] Proper sub-query handling if it is used inside select list and group by

core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java
The `SqlFunctionsTest.testToIntWithTimeZone` test fails in the Europe/London time zone. The issue is due to the use of `TimeZone.setRawOffset(int)` which expects the provided value to be the offset from GMT, but the test provides the offset from UTC.
I tested the changes in multiple timezones and they all passed.
=> [CALCITE-5493] Time zone tests in SqlFunctions should pass in Europe/London

cassandra/src/main/java/org/apache/calcite/adapter/cassandra/CassandraSchema.java, cassandra/src/main/java/org/apache/calcite/adapter/cassandra/CassandraSchemaFactory.java, cassandra/src/main/java/org/apache/calcite/adapter/cassandra/CassandraTable.java, cassandra/src/test/java/org/apache/calcite/test/CassandraAdapterTest.java, cassandra/src/test/java/org/apache/calcite/test/CassandraAdapterWithoutKeyspaceTest.java, cassandra/src/test/resources/model-without-keyspace.json, cassandra/src/test/resources/twissandra-small.cql
Currently, it is not possible to construct a `CassandraSchema` instance if the keyspace is not set in the CQL session.
Queries generated by `CassandraTable` do not include a keyspace and will fail if the CQL session does not have a keyspace set.
=> [CALCITE-5515] Add keyspace parameter to CassandraSchema and CassandraTable

core/src/main/java/org/apache/calcite/plan/volcano/RelSubset.java, core/src/test/java/org/apache/calcite/plan/volcano/VolcanoPlannerTest.java
When using `CheapestPlanReplacer`, semantics of a `RelNode` tree change if it contains the same node multiple times in case this node has inputs itself that have to be replaced. During replacement such nodes get copied on each occurrence.
Instead `CheapestPlanReplacer` should memoize previously visited nodes and emit the same result again in the that case.
=> [CALCITE-5503] Address issue in CheapestPlanReplacer where repeated nodes in a DAG are not reused.

core/src/main/java/org/apache/calcite/sql/type/CompositeOperandTypeChecker.java
Fix typo in CompositeOperandTypeChecker: `CompositeOperandsTypeChecking` -> `CompositeOperandTypeChecker`
=> CompositeOperandTypeChecker's java doc uses wrong class name

core/src/main/java/org/apache/calcite/tools/RelBuilder.java, core/src/test/java/org/apache/calcite/test/RelBuilderTest.java
As mentioned in the original jira issue it is required / would be nice to have for Flink
=> [CALCITE-5381] Add `convertCorrelateToJoin` config property to RelBuilder

core/src/main/java/org/apache/calcite/rel/metadata/RelColumnOrigin.java
This is a typo of RelColumnOrigin#isDerived method
=> [MINOR][JAVADOC] Updated javadoc instructions for RelColumnOrigin#isDerived method

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
Calcite already supports the CHR function for Oracle and PostgreSQL. BigQuery supports it as well ([link](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#chr)) so I would just like to enable it and add a couple more tests.
=> [CALCITE-5605] Add BigQuery as supported library for CHR

core/src/main/java/org/apache/calcite/sql/type/SqlTypeUtil.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
This PR includes the fix in #3155 as well, because it depends on it.
=> [CALCITE-5651] Inferred scale for decimal should not exceed maximum allowed scale

core/src/main/java/org/apache/calcite/plan/volcano/RelSubset.java, core/src/test/java/org/apache/calcite/plan/volcano/VolcanoPlannerTest.java
jira: [CALCITE-5563](https://issues.apache.org/jira/browse/CALCITE-5563)
Once we have found a matching Relsubset from its parent input, we can immediately end the inner loop
=> [CALCITE-5563] Reduce loops to optimize RelSubset#getParents and RelSubset#getParentSubsets

core/src/main/java/org/apache/calcite/plan/hep/HepPlanner.java
[CALCITE-5679](https://issues.apache.org/jira/browse/CALCITE-5679) 
Minor optimization:
HepPlanner#buildFinalplan clears the metadata cache info of the impacted RelNode after replacing its inputs, but in the cases where the RelNode does not change (e.g. when it has no inputs) this clear cache should not be necessary (unless I'm missing something).
=> [CALCITE-5679] HepPlanner#buildFinalPlan: do not clear metadata cache if RelNode has not changed

core/src/main/java/org/apache/calcite/sql/dialect/ClickHouseSqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java, core/src/main/java/org/apache/calcite/sql/fun/SqlSubstringFunction.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java, testkit/src/main/java/org/apache/calcite/sql/parser/SqlParserTest.java
Prevent BigQuery SUBSTR(value, position[, length]) from being translated to SUBSTRING(value FROM position FOR length). Keep arguments comma-separated by adding onto `BigQuerySqlDialect#unparseCall`.
=> [CALCITE-5677] SUBSTR signature incorrect for BigQuery

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
The functions follow Spark's description
ARRAY_DISTINCT: https://spark.apache.org/docs/latest/sql-ref-functions-builtin.html
=> [CALCITE-5657] Add ARRAY_DISTINCT function (enabled in Spark library).

core/src/main/java/org/apache/calcite/sql/fun/SqlCastFunction.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
Fixes minor regression introduced by https://github.com/apache/calcite/pull/3189
=> [CALCITE-5674] CAST expr to target type should respect nullable when it is complex type (follow-up)

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
array_compact(array) - Removes null values from the array.
Examples:
> SELECT array_compact(array(1, 2, 3, null));
[1,2,3]
> SELECT array_compact(array("a", "b", "c"));
["a","b","c"]
=> [CALCITE-5734] Add ARRAY_COMPACT function (enabled in Spark library)

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/type/ReturnTypes.java, core/src/main/java/org/apache/calcite/sql/type/SqlTypeTransforms.java, core/src/main/java/org/apache/calcite/sql/type/SqlTypeUtil.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
MAP_ENTRIES - Returns an unordered array of all entries in the given map.
For more details
https://spark.apache.org/docs/latest/sql-ref-functions-builtin.html
comments:
1. according to this talk, https://issues.apache.org/jira/browse/CALCITE-5695 the function description also changed to 
Returns the entries of the map as an array, the order of the entries is not defined
=> [CALCITE-5714] Add MAP_ENTRIES function (enabled in Spark library)

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/CalciteResource.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/main/resources/org/apache/calcite/runtime/CalciteResource.properties, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/sql/test/AbstractSqlTester.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
[sort_array](https://spark.apache.org/docs/latest/api/sql/index.html#sort_array)
sort_array(array[, ascendingOrder]) - Sorts the input array in ascending or descending order according to the natural ordering of the array elements. Null elements will be placed at the beginning of the returned array in ascending order or at the end of the returned array in descending order.
NaN is greater than any non-NaN elements for double/float type.  which is default behavior, so i don't add into the doc
Examples:
> SELECT sort_array(array('b', 'd', null, 'c', 'a'), true);
[null,"a","b","c","d"]
> SELECT sort_array(array('b', 'd', null, 'c', 'a'));
[null,"a","b","c","d"]
=> [CALCITE-5738] Add SORT_ARRAY function (enabled in Spark library)

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
The unit test pretty much sums it up. Without the logic fix, the resulting SQL would be this:
```
SELECT "JOB"
FROM "scott"."EMP"
GROUP BY "JOB"
ORDER BY "JOB", 2
```
which is of course wrong because it's ordering by `2` and there's only one expression in the `SELECT` list.
=> [CALCITE-5768] Fix early return in hasSortByOrdinal

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableBatchNestedLoopJoinRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableLimitRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableLimitSortRule.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeUnionRule.java, core/src/main/java/org/apache/calcite/plan/RelOptRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateRemoveRule.java, core/src/main/java/org/apache/calcite/rel/rules/CalcRemoveRule.java, core/src/main/java/org/apache/calcite/rel/rules/ProjectRemoveRule.java, core/src/main/java/org/apache/calcite/rel/rules/SortRemoveRule.java, core/src/test/java/org/apache/calcite/test/HepPlannerTest.java, geode/src/main/java/org/apache/calcite/adapter/geode/rel/GeodeRules.java
See problem description in:
[CALCITE-5401](https://issues.apache.org/jira/browse/CALCITE-5401) Rule fired by HepPlanner can return Volcano's RelSubset.
Issue solved by  adding new `RelOptRule#convert` with an additional planner parameter, and use it in potentially sensitive locations for this issue to occur (basically rules' `onMatch`)
=> [CALCITE-5401] Rule fired by HepPlanner can return Volcano's RelSubset

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/CalciteResource.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java, core/src/main/java/org/apache/calcite/sql/type/ReturnTypes.java, core/src/main/java/org/apache/calcite/sql/type/SqlTypeTransforms.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/main/resources/org/apache/calcite/runtime/CalciteResource.properties, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
 STR_TO_MAP(string[, stringDelimiter[, keyValueDelimiter]])
Returns a map after splitting the string into key/value pairs using delimiters. Default delimiters are ',' for stringDelimiter and ':' for keyValueDelimiter Both pairDelim and keyValueDelim are treated as regular expressions.
```
Examples:
> SELECT str_to_map('a:1,b:2,c:3', ',', ':');
- {"a":"1","b":"2","c":"3"}
> SELECT str_to_map('a');
{"a":null} 
```
MAP_FROM_ARRAYS (array1, array2)
Returns a map created from an array1 and *array2. Note that the lengths of two arrays should be the same
> SELECT map_from_arrays(array(1.0, 3.0), array('2', '4'));
{1.0:"2",3.0:"4"}
=> [CALCITE-5744] Add MAP_FROM_ARRAYS, STR_TO_MAP function (enabled in Spark library)

core/src/main/java/org/apache/calcite/rel/rules/materialize/MaterializedViewRule.java
1.  `If` maybe better than `assert`
- old
```
assert !compensationColumnsEquiPred.isAlwaysTrue()
|| !otherCompensationPred.isAlwaysTrue()
```
- new
```
if (compensationColumnsEquiPred.isAlwaysTrue()
&& otherCompensationPred.isAlwaysTrue()) {
continue;
}
```
2. Optimize code comments
- Old code comments can cause misunderstandings.
```
grep -n "// [abc]\." MaterializedViewRule.java
385:            // b. Generate union branch (query).
396:            // c. Generate union branch (view).
422:            // a. Compute final compensation predicate.
459:            // b. Generate final rewriting if possible.
```
- Here are new comments.
```
grep -n "// [abcAB]\." MaterializedViewRule.java
368:            // a. Attempt partial rewriting using union operator. This rewriting
387:            // b. …
```
=> [MINOR] Assert can be replaced in `AbstractMaterializedViewRule#perform()`

innodb/src/main/java/org/apache/calcite/adapter/innodb/IndexCondition.java, innodb/src/main/java/org/apache/calcite/adapter/innodb/InnodbToEnumerableConverter.java
https://issues.apache.org/jira/browse/CALCITE-5824
Refine constructor of IndexCondition, when pointQueryKey is null set an emptyList like other variables do.
This change is a trivial rework / code cleanup. Verifying by current total cases.
=> [CALCITE-5824] Handle IndexCondition null pointQueryKey list in innodb

core/src/main/java/org/apache/calcite/sql/type/CompositeOperandTypeChecker.java, core/src/main/java/org/apache/calcite/sql/type/CompositeSingleOperandTypeChecker.java, core/src/main/java/org/apache/calcite/sql/type/FamilyOperandTypeChecker.java, core/src/main/java/org/apache/calcite/sql/type/IntervalOperandTypeChecker.java, core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java, core/src/test/java/org/apache/calcite/sql/type/OperandTypesTest.java
By adjusting handling of iFormalOperand in various checkers.
1) CompositeOperandTypeChecker: always send the proper iFormalOperand; never zero.
2) FamilyOperandTypeChecker: always look at the first (and only) family when being used as a SqlSingleOperandTypeChecker via checkSingleOperandType. Continue considering all families when used as a SqlOperandTypeChecker via checkOperandTypes.
3) IntervalOperandTypeChecker: use the SqlNode parameter, not the SqlCallBinding, to get the node to check. Using the SqlCallBinding violates the contract of SqlSingleOperandTypeChecker#checkSingleOperandType.
=> [CALCITE-5479] FamilyOperandTypeChecker is not readily composable in sequences

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableInterpretable.java, core/src/test/java/org/apache/calcite/adapter/enumerable/StaticFieldDetectorTest.java
=> [CALCITE-5839] EnumerableInterpretable#StaticFieldDetector can overwrite its flag and return an incorrect result

core/src/main/codegen/templates/Parser.jj, core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
[CALCITE-5747](https://issues.apache.org/jira/browse/CALCITE-5747) introduced some BigQuery-specific logic for FLOOR and CEIL that is keyed off the conformance being `SqlConformanceEnum.BIG_QUERY`. However, it was implemented in such a way that implementations of `SqlConformance` that are not `SqlConformanceEnum` would throw `ClassCastException`.
=> [CALCITE-5865] ClassCastException with FLOOR and CEIL on conformances that are not builtin

core/src/main/codegen/templates/Parser.jj
There are no warning.
- core
```
$ javacc core/build/fmpp/fmppMain/javacc/Parser.jj
Java Compiler Compiler Version 7.0.9 (Parser Generator)
(type "javacc" with no arguments for help)
Reading from file core/build/fmpp/fmppMain/javacc/Parser.jj . . .
Note: UNICODE_INPUT option is specified. Please make sure you create the parser/lexer using a Reader with the correct character encoding.
File "TokenMgrError.java" is being rebuilt.
File "ParseException.java" is being rebuilt.
File "Token.java" is being rebuilt.
File "SimpleCharStream.java" is being rebuilt.
Parser generated successfully.
```
- server
```
$ javacc server/build/fmpp/fmppMain/javacc/Parser.jj
Java Compiler Compiler Version 7.0.9 (Parser Generator)
(type "javacc" with no arguments for help)
Reading from file …
```
=> Following [CALCITE-5688] Eliminate warnings in server parser

babel/src/test/resources/sql/big-query.iq, core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/type/ReturnTypes.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
Add support for SAFE_MULTIPLY in BigQuery.
SAFE_MULTIPLY: Equivalent to the multiplication operator '*', but returns NULL if overflow occurs.
Example 1: SELECT SAFE_MULTIPLY(3, 4) would return 12.
Example 2: SELECT SAFE_MULTIPLY(2^63, 2) would return NULL because of overflow.
Any comments, questions, or suggestions are welcome as always!
=> [CALCITE-5735] Add SAFE_MULTIPLY function (enabled in BigQuery)

redis/src/test/java/org/apache/calcite/adapter/redis/RedisCaseBase.java
code cleanup, remove some unnecessary null checks for redis adapter, because the static variable must be initialized successfully unless there is an exception.
Remove some unnecessary null checks in redis adapter.
It's minor fix can be covered by current total cases.
=> [CALCITE-5875] Remove unnecessary NULL checks in Redis adapter

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/SqlBasicFunction.java, core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
Returns Soundex code of the string.
> SELECT soundex('Miller');
M460
details pls see: https://issues.apache.org/jira/browse/CALCITE-5831
note: spark soundex not throw exception but return original string if the input string can't be mapped.
Add soundex function (enabled in Spark Library)
SqlOperatorTests#testSoundex2Func()
=> [CALCITE-5831] Add SOUNDEX function (enabled in Spark library)

linq4j/src/main/java/org/apache/calcite/linq4j/tree/Expressions.java, linq4j/src/main/java/org/apache/calcite/linq4j/tree/Primitive.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
I wasn't entirely sure how to handle conversions to other types than the numeric ones, so I left the previous behavior unchanged, but there may be other problems lurking.
=> [CALCITE-5843] Constant expression with nested casts causes a compiler crash

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
This bug is reproduced only when specific optimizations are run on the buggy (now corrected) function definitions.
I have added the test cases in RelOptRulesTest, because that's where it's easy to control the optimizations applied, but if there is a better file for these tests, please let me know. They depend on specific SQL dialects.
=> [CALCITE-5813] Type inference for sql functions REPEAT, SPACE, XML_TRANSFORM, and XML_EXTRACT is incorrect

core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java, core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
1. Add the visit(Sample e) method in RelToSqlConverter
2. In SqlImplementor#wrapSelect method,allow SqlStdOperatorTable.TABLESAMPLE
3. Add some tests in ReltoSqlConverterTest
=> [CALCITE-5906] JDBC adapter should generate TABLESAMPLE

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/type/ArrayInsertOperandTypeChecker.java, core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
Add array_insert(x, pos, val) function(enabled in Spark library).
Places val into index pos of array x. Array indices start at 1, or start from the end if index is negative. Index above array size appends the array, or prepends the array if index is negative, with 'null' elements
issue: https://issues.apache.org/jira/browse/CALCITE-5830
Examples:
> SELECT array_insert(array(1, 2, 3, 4), 5, 5); [1,2,3,4,5]
> SELECT array_insert(array(5, 3, 2, 1), -3, 4); [5,4,3,2,1] 
https://spark.apache.org/docs/latest/api/sql/index.html#array_insert
Add array_insert(x, pos, val) function(enabled in Spark library).
SqlOperatorTests#testArrayInsertFunc()
=> [CALCITE-5830] Add ARRAY_INSERT function(enabled in Spark library)

babel/src/test/resources/sql/big-query.iq, core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/type/ReturnTypes.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
This PR continues working towards the goal of implementing all BigQuery safe arithmetic functions, captured in [CALCITE-5591](https://issues.apache.org/jira/browse/CALCITE-5591). SAFE_MULTIPLY was merged recently in [1b8dc6](https://github.com/apache/calcite/commit/1b8dc60b7673d83445f06ecaebd5f89dfd5781f6) and this PR follows a very similar structure, except of course using addition rather than multiplication. 
Any questions or suggestions would be appreciated as always!
=> [CALCITE-5640] Add SAFE_ADD function (enabled in BigQuery library)

core/src/main/codegen/templates/Parser.jj, core/src/main/java/org/apache/calcite/sql/parser/SqlParserUtil.java, core/src/test/java/org/apache/calcite/sql/test/SqlAdvisorTest.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java, core/src/test/resources/sql/misc.iq, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/sql/parser/SqlParserTest.java
This PR mainly does one thing:
1. make calcite E2E support decimal '12.3' sql grammer,and it is consistent with Postgres,the sql like this:
```sql
-- result is 10.9
select decimal '9.9' + 1
```
=> [CALCITE-5870] Allow literals like DECIMAL '12.3' (consistent with Postgres)

babel/src/main/codegen/config.fmpp, babel/src/test/resources/sql/big-query.iq, core/src/main/codegen/default_config.fmpp, core/src/main/codegen/templates/Parser.jj, core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/SqlFunction.java, core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java, core/src/main/java/org/apache/calcite/sql/validate/SqlValidator.java, core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
BigQuery's `CONTAIN_SUBSTR` determines whether a string appears in an expression. This expression can be of many types, as seen in the docs [here](https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#contains_substr).
Also removes some random extra whitespace. Let me know if this should be reverted.
Any comments, questions, or suggestions in the meantime are appreciated as always.
=> [CALCITE-5644] Add CONTAINS_SUBSTR function (enabled in BigQuery library)

core/src/main/java/org/apache/calcite/util/TimeString.java, core/src/main/java/org/apache/calcite/util/TimestampString.java, core/src/test/java/org/apache/calcite/rex/RexBuilderTest.java
This PR corrects the example usage of the withMillis, withNanos, and withFraction methods to match the TimeString constructor which only accepts a time string. And some other improvements
=> [CALCITE-5946] TimeString should allow fractional seconds ending in zero

core/src/main/java/org/apache/calcite/rel/rules/ProjectToWindowRule.java, core/src/main/java/org/apache/calcite/rel/rules/ReduceExpressionsRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
With this change the PROJECT_REDUCE_EXPRESSIONS rule will also optimize constants that appear in window bound expressions. This makes it possible to compile programs that use (constant) expressions in window bounds.
However, I suspect that the rule PROJECT_TO_LOGICAL_PROJECT_AND_WINDOW is still buggy, since it will move window bound expressions into separate projections, as described in the JIRA case. Unfortunately I could not figure out how to fix that rule - the code is very generic and treats all expressions in the same way, regardless where they appear in the RexNode. Perhaps I should file another JIRA issue about this?
=> [CALCITE-5861] Optimization rules do not constant-fold expressions in window bounds

core/src/main/java/org/apache/calcite/rel/rules/AggregateCaseToFilterRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml, core/src/test/resources/sql/agg.iq
The aggregate: SUM(case when x = 1 then 1 else 0 end)
* must be null only in case there are no input rows
* may only be 0 if there is at least one input which doesn't match the filter
=> [CALCITE-5953] AggregateCaseToFilterRule may make inaccurate SUM transformations

core/src/main/java/org/apache/calcite/rel/rules/SemiJoinJoinTransposeRule.java, core/src/test/java/org/apache/calcite/runtime/RelOptRulesRuntimeTest.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
https://issues.apache.org/jira/browse/CALCITE-5952
=> [CALCITE-5952] SemiJoinJoinTransposeRule should check if JoinType supports pushing predicates into its inputs

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableHashJoin.java, core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoin.java, core/src/main/java/org/apache/calcite/adapter/enumerable/PhysType.java, core/src/main/java/org/apache/calcite/adapter/enumerable/PhysTypeImpl.java, core/src/main/java/org/apache/calcite/runtime/Utilities.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/test/java/org/apache/calcite/runtime/EnumerablesTest.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableHashJoinTest.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableJoinTest.java, linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
See Jira CALCITE-5732.
Proposed solution:
- For HashJoin: generate key with a new accessor that will return null if one of the fields is null (and the hashJoin algorithm will work as usual and will return the correct result).
- For MergeJoin: the previous approach could not be applied, since the current MergeJoin implementation works with keys sorted in ascending order, nulls last, so having a null means that the left/right input is exhausted, and that could have undesired effects (wrong results) in the MJ. Instead, use a new, dedicated key comparator that will NOT consider two null values as equal
=> [CALCITE-5732] EnumerableHashJoin and EnumerableMergeJoin on composite key return rows matching condition 'null = null'

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-5862
Fix incorrect spark semantics of array function when array elements have Numeric and Character types.
SqlOperatorTests#testArrayFunc()
=> [CALCITE-5862] Incorrect semantics of ARRAY function (Spark library) when elements have Numeric and Character types

core/src/main/java/org/apache/calcite/sql/fun/SqlTranslateFunction.java, testkit/src/main/java/org/apache/calcite/sql/parser/SqlParserTest.java
@ILuffZhe this PR fixes a test which you recently wrote which I suspect was wrong.
Can you please take a look?
=> [CALCITE-5996] TRANSLATE operator is incorrectly unparsed

mongodb/src/main/java/org/apache/calcite/adapter/mongodb/MongoSort.java, mongodb/src/test/java/org/apache/calcite/adapter/mongodb/MongoAdapterTest.java
The following query fails with a `JsonParseException`:
```sql
select state as "STATE", avg(pop) as "AVG(pop)"
from zips
group by "STATE"
order by "AVG(pop)"
```
Stack trace:
```
org.bson.json.JsonParseException: JSON reader was expecting ':' but found '('.
at org.bson.json.JsonReader.readBsonType(JsonReader.java:150)
at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:85)
at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:104)
at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
at org.bson.BsonDocument.parse(BsonDocument.java:66)
at org.apache.calcite.adapter.mongodb.MongoTable.aggregate(MongoTable.java:138)
at …
```
=> [CALCITE-6026] MongoDB: Column is not quoted in "order by" clause and throws JsonParseException

site/_docs/history.md
The old link is empty now, why we use old link and why we change to this new link can be found at
https://issues.apache.org/jira/browse/CALCITE-6017
=> [CALCITE-6017] Update the GitHub link of released versions

babel/src/main/codegen/config.fmpp, babel/src/main/codegen/includes/parserImpls.ftl, babel/src/test/java/org/apache/calcite/test/BabelParserTest.java, babel/src/test/java/org/apache/calcite/test/BabelTest.java, babel/src/test/resources/sql/select.iq, core/src/main/codegen/templates/Parser.jj, core/src/main/java/org/apache/calcite/sql/JoinType.java, core/src/main/java/org/apache/calcite/sql/SqlJoin.java, core/src/main/java/org/apache/calcite/sql/validate/JoinNamespace.java, core/src/main/java/org/apache/calcite/sql/validate/JoinScope.java, core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
[CALCITE-5962](https://issues.apache.org/jira/browse/CALCITE-5962) Allow Spark-style syntax "LEFT ANTI JOIN" in Babel parser
=> [CALCITE-5962] Support parse Spark-style syntax LEFT ANTI JOIN in Babel parser

core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java, core/src/main/java/org/apache/calcite/rel/rules/SortRemoveRedundantRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
More details could see:https://issues.apache.org/jira/browse/CALCITE-6009
=> [CALCITE-6009] Add optimization to remove redundant LIMIT that is more than input row count

core/src/main/java/org/apache/calcite/rex/RexSimplify.java, core/src/test/java/org/apache/calcite/rex/RexProgramTest.java, geode/src/main/java/org/apache/calcite/adapter/geode/rel/GeodeFilter.java, geode/src/main/java/org/apache/calcite/adapter/geode/rel/GeodeRules.java, geode/src/test/java/org/apache/calcite/adapter/geode/rel/GeodeAllDataTypesTest.java
Simplify 'p OR NOT p' to 'TRUE' (if p is not nullable), or to 'null AND p IS NOT NULL' (if p is nullable).
GeodeFilter support converting 'p IS NOT NULL' to 'p <> null'.
=> [CALCITE-4189] Simplify 'p OR (p IS NOT TRUE)' to 'TRUE'

site/_config.yml, site/_docs/adapter.md
- fix following broken links on adapter page:
https://calcite.apache.org/avatica/apidocs/org/apache/calcite/avatica/ConnectStringParser.html
https://calcite.apache.org/javadocAggregate/org/apache/calcite/sql/fun/SqlGroupedWindowFunction.html
https://pig.apache.org/docs/r0.7.0/piglatin_ref1.html
https://calcite.apache.org/javadocAggregate/org/apache/calcite/rel/cassandra/CassandraProject.html
https://calcite.apache.org/javadocAggregate/org/apache/calcite/rel/metadata/RelMetadataQuery.html#getSelectivity-org.apache.calcite.rel.RelNode-org.apache.calcite.rex.RexNode-
=> [CALCITE-6033] Correct broken links on adapter page

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
The problem addressed is that character literals with a charset specified lose charset information when the program is translated to Rel and back. This change adds the charset to SqlLiterals, but only if the charset is not the default one. (Prior to this fix the charset was always 'null'). We could always add the charset, but then many literals obtained from RelToSql would look like `"_ISO-8859-1'char'"`
=> [CALCITE-6006] RelToSqlConverter loses charset information

core/src/main/java/org/apache/calcite/sql/type/SqlTypeUtil.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
```
[info]   java.lang.UnsupportedOperationException: Unsupported type when convertTypeToSpec: MAP
[info]   at org.apache.calcite.sql.type.SqlTypeUtil.convertTypeToSpec(SqlTypeUtil.java:1140)
[info]   at org.apache.calcite.sql.SqlDialect.getCastSpec(SqlDialect.java:848)
[info]   at io.narrative.nql.package$$anon$1.getCastSpec(package.scala:50)
[info]   at org.apache.calcite.rel.rel2sql.RelToSqlConverter.castNullType(RelToSqlConverter.java:486)
[info]   at org.apache.calcite.rel.rel2sql.RelToSqlConverter.visit(RelToSqlConverter.java:458)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[info]   at …
```
=> Following [CALCITE-5570] Support nested map type for SqlDataTypeSpec

babel/src/test/java/org/apache/calcite/test/BabelTest.java, core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
Please note that running this test requires #3445 to be merged first.
=> [CALCITE-6030] DATE_PART is not handled by the RexToLixTranslator

site/_docs/reference.md
The background is that I was going to implement Spark's MAP function, and found that the MAP constructor embedded in calcite had no examples in docs. So try to add it here.
Background and context can be found at: https://issues.apache.org/jira/browse/CALCITE-5918
=> [MINOR] Add example for MAP type in reference docs

core/src/test/java/org/apache/calcite/test/SqlOperatorUnparseTest.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
Follow-up of [CALCITE-5921](https://issues.apache.org/jira/browse/CALCITE-5921) (https://github.com/apache/calcite/pull/3471) to fix some broken tests
=> [CALCITE-5921] SqlOperatorFixture.checkFails and checkAggFails don't check runtime failure (follow-up)

core/src/main/java/org/apache/calcite/rex/RexExecutable.java, core/src/test/java/org/apache/calcite/rex/RexExecutorTest.java
[CALCITE-5949] RexExecutable should return unchanged original expressions when it fails
=> [CALCITE-5949] RexExecutable should return unchanged original expressions when it fails

core/src/main/codegen/templates/Parser.jj, core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/prepare/LixToRelTranslator.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/sql/parser/SqlParserTest.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-5918
the spark map function has 2 different points with calcite map constructor:
1. use map(k, v, ...) rather than map[k, v, ...]
2. allows empty map such as map(); however calcite map constructor not support it.
=> [CALCITE-5918] Add MAP function (enabled in Spark library)

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
https://issues.apache.org/jira/browse/CALCITE-6037
the definition of function category in ANSI-SQL(not very sure this is the sql standard, but the implementation of calcite is similar to it): 
https://www.oreilly.com/library/view/sql-in-a/9780596155322/ch04s04.html.
=> [CALCITE-6037] The function category of ARRAY/EXTRACT_VALUE/XML_TRANSFORM/EXTRACT_XML/EXISTSNODE is incorrect

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableCollect.java, core/src/main/java/org/apache/calcite/rel/core/Collect.java, core/src/main/java/org/apache/calcite/sql/fun/SqlMapQueryConstructor.java, core/src/main/java/org/apache/calcite/sql/type/SqlTypeTransforms.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/test/resources/sql/sub-query.iq, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
Currently the map sub-query such as `map(select a, b)` can't work.
details pls see: https://issues.apache.org/jira/browse/CALCITE-6041
=> [CALCITE-6041] MAP sub-query gives NullPointerException

core/src/main/java/org/apache/calcite/util/Bug.java, core/src/test/java/org/apache/calcite/test/SqlOperatorUnparseTest.java, linq4j/src/main/java/org/apache/calcite/linq4j/tree/Primitive.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/sql/test/SqlOperatorFixture.java, testkit/src/main/java/org/apache/calcite/sql/test/SqlTests.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
It turns out that in SQL casts are checked: a cast that cannot represent the resulting value in the destination type should report a runtime error. This PR adds range checking for Number values. The tests for this PR require https://github.com/apache/calcite/pull/3471 to fix a bug in the test fixture.
=> [CALCITE-5990] Explicit cast to numeric type doesn't check overflow

core/src/main/java/org/apache/calcite/sql/SqlWindow.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml, core/src/test/resources/sql/misc.iq
Allow multiple ORDER BY columns with RANGE bounds in window functions, if both of the bounds are constant bounds (CURRENT ROW, UNBOUNDED PRECEDING, UNBOUNDED FOLLOWING)
=> [CALCITE-5863] Calcite rejects valid query with multiple ORDER BY columns and constant RANGE bounds in window functions

core/src/main/java/org/apache/calcite/util/Sources.java, file/src/main/java/org/apache/calcite/adapter/file/CsvStreamReader.java, gradle.properties
bump commons-codec from 1.13 to 1.16.0
bump commons-dbcp2 from 2.9.0 to 2.11.0
bump commons-io from 2.11.0 to 2.15.0
bump commons-lang3 from 3.8 to 3.13.0
bump commons-pool2 from 2.6.2 to 2.12.0
bump commons-text from 1.10.0 to 1.11.0
=> Bump 6 dependencies

core/src/main/java/org/apache/calcite/sql/SqlInsert.java, core/src/test/java/org/apache/calcite/sql/test/SqlPrettyWriterTest.java, core/src/test/resources/org/apache/calcite/sql/test/SqlPrettyWriterTest.xml
fix of [CALCITE-6102](https://issues.apache.org/jira/browse/CALCITE-6102)
SqlWriter in SqlInsert's unparse() start a list but does not end it.
if we put a SqlInsert into a SqlWith's body, when we unparse the SqlWith , it will throw an Expception :
java.lang.IllegalArgumentException: Frame does not match current frame
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
at org.apache.calcite.sql.pretty.SqlPrettyWriter.endList(SqlPrettyWriter.java:884)
at org.apache.calcite.sql.SqlWith$SqlWithOperator.unparse(SqlWith.java:109)
=> [CALCITE-6102] SqlWriter in SqlInsert's unparse start a list but does not end it

site/_docs/reference.md
https://issues.apache.org/jira/browse/CALCITE-6118
=> [CALCITE-6118] Missing empty ARRAY function usage in reference doc

site/_docs/reference.md
function for empty string arguments
=> [CALCITE-6105] Documentation does not specify the behavior of SPLIT

site/_docs/reference.md
change ARRAY form to `ARRAY([expr [, expr ]*])`.
JSON_ARRAY already uses this form.
=> [CALCITE-6118] Missing empty ARRAY function usage in reference doc (follow-up)

core/src/main/java/org/apache/calcite/rel/type/RelDataTypeSystem.java, core/src/main/java/org/apache/calcite/sql/type/SqlTypeName.java
Update javadoc for SqlTypeName#allowsPrecScale method
=> Update javadoc for SqlTypeName#allowsPrecScale method

core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/fun/SqlSubstringFunction.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
The bug was a combination of type inference and lack of support for versions of `substring` with long arguments.
=> [CALCITE-5811] Error messages produced for constant out-of-bounds arguments are confusing

core/src/main/java/org/apache/calcite/interpreter/AggregateNode.java, core/src/main/java/org/apache/calcite/plan/VisitorDataContext.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMdSize.java, core/src/main/java/org/apache/calcite/rel/type/RelDataTypeFactoryImpl.java, core/src/main/java/org/apache/calcite/rex/RexBuilder.java, core/src/main/java/org/apache/calcite/rex/RexLiteral.java, core/src/main/java/org/apache/calcite/sql/SqlLiteral.java, core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/ClickHouseSqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/JethroDataSqlDialect.java, core/src/main/java/org/apache/calcite/sql/type/SqlTypeAssignmentRule.java, core/src/main/java/org/apache/calcite/sql/type/SqlTypeExplicitPrecedenceList.java, core/src/main/java/org/apache/calcite/sql/type/SqlTypeUtil.java, core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java, core/src/test/java/org/apache/calcite/rex/RexBuilderTest.java, druid/src/main/java/org/apache/calcite/adapter/druid/DruidType.java, file/src/main/java/org/apache/calcite/adapter/file/CsvEnumerator.java, piglet/src/main/java/org/apache/calcite/piglet/PigTypes.java, piglet/src/test/java/org/apache/calcite/test/PigRelExTest.java
This is based on a code audit.
The assumption is that FLOAT=DOUBLE=64 bit and REAL=32 bit
I also deleted some deprecated functions instead of fixing them.
=> [CALCITE-6074] The size of REAL, DOUBLE, and FLOAT is not consistent

core/src/main/java/org/apache/calcite/runtime/Like.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
fix possibility to execute:
`select 'Dev\ops' like 'Dev#\ops' escape '#';`
=> CALCITE-6180 Append possibility to escape backslash in LIKE with ESCAPE operator

core/src/main/java/org/apache/calcite/rex/RexChecker.java
Update the javadoc for `RexChecker` to reflect changes from https://issues.apache.org/jira/browse/CALCITE-955
=> [MINOR] Update javadoc for RexChecker with Litmus argument

core/src/main/java/org/apache/calcite/sql/validate/implicit/AbstractTypeCoercion.java, core/src/test/java/org/apache/calcite/test/TypeCoercionConverterTest.java, core/src/test/java/org/apache/calcite/test/TypeCoercionTest.java, core/src/test/resources/org/apache/calcite/test/TypeCoercionConverterTest.xml
In AbstractTypeCoercion#promoteToVarChar() return resultType with nullability if any of the types being promoted are nullable.
=> [CALCITE-5130] AssertionError: "Conversion to relational algebra failed to preserve datatypes" when union VARCHAR literal and CAST(null AS INTEGER)

core/src/main/java/org/apache/calcite/sql/dialect/ClickHouseSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
In ClickHouse, there is an issue with RelDataType of Nullable type when casting to a non-Nullable type. For example, `SELECT CAST(NULL, 'Int32')` will throw an error. In such cases, we should use `SELECT CAST(NULL, 'Nullable(Int32)')` instead.
```
CREATE TABLE default.test
(
`id` Int64,
`a` Nullable(Int64)
)
ENGINE = MergeTree
ORDER BY id
```
`insert into test(id,a) values(1,1);`
`insert into test(id,a) values(2,null);`
`SELECT CAST(a, 'String') FROM test;`
DB::Exception: Cannot convert NULL value to non-Nullable type
=> [CALCITE-6149] Unparse for CAST Nullable with ClickHouseSqlDialect

core/src/main/java/org/apache/calcite/util/format/FormatElementEnum.java, core/src/main/java/org/apache/calcite/util/format/FormatModels.java, core/src/test/java/org/apache/calcite/util/format/FormatElementEnumTest.java
https://issues.apache.org/jira/browse/CALCITE-6179
=> [CALCITE-6179] Support weekofmonth function format and add test

core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java, core/src/main/java/org/apache/calcite/sql2rel/StandardConvertletTable.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
Enabling LENGTH for Snowflake and adding the LEN alias
=> [CALCITE-6182] Add LENGTH/LEN functions (enabled in Snowflake library)

core/src/main/java/org/apache/calcite/adapter/enumerable/RexToLixTranslator.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, linq4j/src/main/java/org/apache/calcite/linq4j/tree/Primitive.java, testkit/src/main/java/org/apache/calcite/sql/test/SqlOperatorFixture.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
This also fixes a few more tests which were disabled in SqlOperatorTests.
I still have to handle casts to decimal values, but hopefully this fixes the behavior of casts to integer types.
This behavior also has to be documented, so a future PR will describe in more details how Calcite evaluates casts.
=> [CALCITE-6111] Explicit cast from expression to numeric type doesn't check overflow

core/src/main/java/org/apache/calcite/adapter/java/ReflectiveSchema.java, core/src/test/java/org/apache/calcite/test/MaterializedViewTester.java, core/src/test/java/org/apache/calcite/test/ReflectiveSchemaTest.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableCorrelateTest.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableHashJoinTest.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableRepeatUnionTest.java, testkit/src/main/java/org/apache/calcite/test/CalciteAssert.java, testkit/src/main/java/org/apache/calcite/test/QuidemTest.java, testkit/src/main/java/org/apache/calcite/test/ReflectiveSchemaWithoutRowCount.java
(from #3154)
This PR adds row count statistics for simple reflective schemas with array and Collection field tables.
This small enhancement makes it a little easier to write tests for optimizer rules, particularly rules that might behave specially when the row count is 1 or 0.
=> [CALCITE-5649] Get row count statistics from ReflectiveSchema

core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/test/resources/sql/sub-query.iq, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/sql/parser/SqlParserTest.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
issue: 
https://issues.apache.org/jira/browse/CALCITE-6063
context:
The sql-standard-2003 allows array constrcutor by query:
```
<array value constructor by query> ::=
ARRAY <left paren>  <query expression>  [ <order by clause>  ] <right paren> 
```
and calcite does support it.
however the orderby was removed by the issue https://issues.apache.org/jira/browse/CALCITE-2978.
The solution of this PR is same as #1763 to allow sort in subquery.
=> [CALCITE-6063] If ARRAY subquery has ORDER BY (without LIMIT), rows are not sorted

core/src/main/java/org/apache/calcite/sql/fun/SqlJsonValueFunction.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
From [CALCITE-6208](https://issues.apache.org/jira/browse/CALCITE-6208)
This PR modifies the `SqlJsonValueFunction` return type inference to special handle explicit array syntax so that the arrays are returned with nullable elements.
The added tests fail with:
```
Expected: is "INTEGER ARRAY"
but: was "INTEGER NOT NULL ARRAY"
```
and
```
Expected: is "INTEGER ARRAY ARRAY"
but: was "INTEGER NOT NULL ARRAY NOT NULL ARRAY"
```
without the changes in this PR.
=> [CALCITE-6208] update JSON_VALUE return type inference to make explicit array return types be nullable with nullable elements

core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
The syntax UNNEST() WITH ORDINALITY is missing the ORDINALITY during the RelToSql stage
https://issues.apache.org/jira/browse/CALCITE-6231
=> [CALCITE-6231] JDBC adapter generates "UNNEST" when it should generate "UNNEST ... WITH ORDINALITY"

.gitignore, .ratignore
When using jenv to manage the local java environment, it will generate a `.java-version` file, we should ignore it.
See more details about jenv in https://github.com/jenv/jenv.
=> Add .gitignore and .ratignore for jenv

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/type/NonNullableAccessors.java, core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-6223
=> [CALCITE-6223] Add MAP_CONTAINS_KEY function (enabled in Spark library)

core/src/main/java/org/apache/calcite/rel/metadata/RelMdPopulationSize.java, core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
(From: #3151)
This PR corrects a row count call to use the RelMetadataQuery instead of going directly to rel.estimateRowCount.
Using rel.estimateRowCount directly will behave incorrectly when using a cardinality estimator that is implemented entirely in a MetadataHandler class, as it will evade the metadata handler's implementation of getRowCount and fall through to the underlying default method for Values.
This corrects the problem by using mq.getRowCount instead of rel.estimateRowCount. In the default case this results in the same value but in the custom cardinality model case the expected handler is called.
=> [CALCITE-5647] RelMdPopulationSize should use mq.getRowCount(rel) instead of rel.estimateRowCount(mq)

core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java, core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
I had to modify a test in testJdbcFun which no longer passes in the original form.
I don't understand why it was passing beforehand. 
To the reviewers: please double check this.
=> [CALCITE-6238] Exception while evaluating ROUND/TRUNCATE functions

site/_docs/innodb_adapter.md
The new rendered HTML is as follows(IDEA Local preview without CSS style).
=> [CALCITE-6256] Incorrect rendering of HTML on InnoDB adapter page

core/src/main/java/org/apache/calcite/tools/RelBuilder.java, core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java, core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
Here is JIRA ticket: https://issues.apache.org/jira/browse/CALCITE-6214
=> [CALCITE-6214] Remove DISTINCT in aggregate function if field is unique

core/src/test/java/org/apache/calcite/test/JdbcTest.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
This PR is a pair to https://github.com/apache/calcite-avatica/pull/238 and should be merged before the other one can pass.
It only changes a few date literals in tests to conform to the expectation of the SQL standard.
Together these two PRs constitute a fix to [CALCITE-6248]
=> [CALCITE-6248] Illegal dates are accepted by casts

core/src/main/java/org/apache/calcite/sql/dialect/PrestoSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
fixed Presto Map Function is unparsed incorrectly ：map(array<K>, array<V>) 
https://issues.apache.org/jira/browse/CALCITE-6258
=> [CALCITE-6258] Map value constructor is unparsed incorrectly for PrestoSqlDialect

core/src/main/codegen/templates/Parser.jj, core/src/main/java/org/apache/calcite/runtime/CalciteResource.java, testkit/src/main/java/org/apache/calcite/sql/parser/SqlParserTest.java
[CALCITE-6255](https://issues.apache.org/jira/browse/CALCITE-6255)
Currently, Calcite has two styles for invoking `JSON_OBJECT`:
```
JSON_OBJECT(KEY 'foo' VALUE 'bar', KEY 'foo2' VALUE 'bar2')
```
and:
```
JSON_OBJECT('foo' : 'bar', 'foo2' : 'bar')
```
However, [BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#json_object) uses a lighter-weight syntax resembling the MAP<> constructor, with an even numbered argument list where every odd item is a key and the following even item is a value:
```
JSON_OBJECT('foo', 'bar', 'foo2', 'bar2')
```
This PR updates the grammar to allow `,` as well as `:` for separating key/value pairs in the invocation.
It does not prevent mixing `,` and `:`, but retains the prohibition from mixing with `KEY`/`VALUE` syntax.
=> [CALCITE-6255] Support BigQuery-style JSON_OBJECT invocation syntax

core/src/main/codegen/templates/Parser.jj, testkit/src/main/java/org/apache/calcite/sql/parser/SqlParserTest.java
[CALCITE-6254](https://issues.apache.org/jira/browse/CALCITE-6254) Support table function calls in `FROM` clause without `TABLE` wrapping.
Currently, when selecting from a table function, the function call needs to be wrapped in `TABLE()` like this:
```
SELECT * FROM TABLE(table_func('args'));
```
This PR enables this syntax:
```
SELECT * FROM table_func('args');
```
Three tokens of lookahead are necessary to avoid a conflict in the grammar with the [dynamic columns feature used by Phoenix](https://phoenix.apache.org/dynamic_columns.html)
```
SELECT * FROM EventLog(lastGCTime TIME)
```
Three tokens of lookahead means looking past the `(` and identifier to the presence of a type production. The table extension clause for dynamic columns requires at least one field, so the empty case of …
=> [CALCITE-6254] Support table function calls in FROM clause without TABLE() wrapper

site/_docs/reference.md
I expected that I could use `SAFE_ADD(INTEGER, INTEGER)` to check for overflow. It turns out that doesn't work, because `SAFE_ADD` will convert the arguments to `BIGINT` first. I think this deserves to be documented. At least this is the BIGQUERY behavior: https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions#safe_add
=> Clarify semantics of SAFE* functions

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/type/ReturnTypes.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
The modified tests are a result of me changing the `ARG0_EXCEPT_INTEGER` return type. I wrote that code last June and I got the nullability wrong so that's why some FLOOR/CEIL tests got changed. I also realized I wasn't preserving the scale/precision of DECIMAL types so I fixed that too. Let me know if anyone has questions.
=> [CALCITE-6290] Incorrect return type for BigQuery TRUNC

core/src/main/java/org/apache/calcite/plan/Strong.java
According to the definition, `c1 = 1 OR c2 IS NULL` cannot be strong in `[c1]`, because `c2 IS NULL` could be true.
=> Improve documentation for Strong

core/src/main/java/org/apache/calcite/sql/fun/SqlAbstractTimeFunction.java, core/src/test/java/org/apache/calcite/sql/type/RelDataTypeSystemTest.java
Change datetime functions taking in a precision to validate against the max precision from the type system, rather than the SqlTypeName.
=> [CALCITE-6262] CURRENT_TIMESTAMP(P) ignores DataTypeSystem#getMaxPrecision

babel/src/test/java/org/apache/calcite/test/BabelQuidemTest.java, babel/src/test/resources/sql/spark.iq, core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-6278
1. Add Function [REGEXP](https://spark.apache.org/docs/latest/api/sql/index.html#regexp)、[REGEXP_LIKE](https://spark.apache.org/docs/latest/api/sql/index.html#regexp_like) enabled in the Spark library.
Since this function has the same implementation as the Spark [RLIKE](https://spark.apache.org/docs/latest/api/sql/index.html#rlike) function. 
The implementation can be reused.
[Source Code](https://github.com/apache/spark/blob/ee15cbd3ac3cc98ae262834b4f16e74fe54d82c3/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/FunctionRegistry.scala#L567C1-L569C54)
[undo] Discuss results in Jira:
> 2. Since Spark 2.0, string literals (including regex patterns) are unescaped in SQL parser, also fix this bug in calcite.  
2. Add spark …
=> [CALCITE-6278] Add REGEXP, REGEXP_LIKE  function (enabled in Spark library)

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorUtil.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-5976
=> [CALCITE-5976] Function ARRAY_PREPEND/ARRAY_APPEND/ARRAY_INSERT gives exception when inserted element type not equals array component type

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/sql/SqlCall.java, core/src/main/java/org/apache/calcite/sql/fun/SqlExtractFunction.java, core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java, core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java, site/_docs/history.md, testkit/src/main/java/org/apache/calcite/sql/test/SqlOperatorFixture.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
While attempting to fix the bug described in the issue I have discovered that many cases for EXTRACT are actually not implemented. So I implemented most of them, and I have improved the validation as well; the case indicated in the JIRA issue will now be rejected statically.
There is one case for EXTRACT which I haven't implemented: `EXTRACT(EPOCH FROM INTERVAL '...' YEAR TO MONTH)` because I wasn't sure how to properly use the convertlets to do it. Help would be appreciated.
This PR also makes some unexpected tiny changes in SqlValidatorImpl and SqlCall, so I would appreciate comments from people who are more knowledgeable.
=> [CALCITE-6015] AssertionError during optimization of EXTRACT expression

core/src/main/java/org/apache/calcite/sql/validate/AggChecker.java, core/src/main/java/org/apache/calcite/sql/validate/SqlValidator.java, core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
Split nakedMeasures flag into two flags:
- nakedMeasuresInsideAggregatingQuery : allowed in group-by queries
- nakedMeasuresOutsideAggregatingQuery : allowed in non-group-by queries
The existing nakedMeasures flag is marked as deprecated. Its functionality is equivalent to setting the above two flags to the same value.
=> [CALCITE-6337] Distinguish naked measure inside and outside aggregation

core/src/main/java/org/apache/calcite/rel/metadata/RelMdCollation.java, core/src/test/java/org/apache/calcite/test/RelMetadataTest.java, core/src/test/resources/sql/sub-query.iq
More details in: [CALCITE-6338](https://issues.apache.org/jira/browse/CALCITE-6338)
Note: the quidem test that required an adjustment actually shows a good example of a side effect of this bug:
Notice how the original plan contained an unnecessary EnumerableSort:
```
old plan:
EnumerableMergeJoin(condition=[=($0, $5)], joinType=[left])
EnumerableCalc(expr#0..7=[{inputs}], EMPNO=[$t0])
EnumerableTableScan(table=[[scott, EMP]])
EnumerableSort(sort0=[$4], dir0=[ASC]) <-- *** HERE! ***
EnumerableCalc(expr#0..7=[{inputs}], expr#8=[1:BIGINT], expr#9=[true], c=[$t8], d=[$t8], m=[$t0], trueLiteral=[$t9], EMPNO1=[$t0])
EnumerableTableScan(table=[[scott, EMP]])
=>
new plan:
EnumerableMergeJoin(condition=[=($0, $5)], joinType=[left])
EnumerableCalc(expr#0..7=[{inputs}], EMPNO=[$t0]) …
```
=> [CALCITE-6338] RelMdCollation#project can return an incomplete list of collations in the presence of aliasing

core/src/main/java/org/apache/calcite/adapter/enumerable/RexToLixTranslator.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java, linq4j/src/main/java/org/apache/calcite/linq4j/tree/Expressions.java, linq4j/src/main/java/org/apache/calcite/linq4j/tree/Types.java
Given a column of type `INT`. When providing a `short` value as a placeholder in a prepared statement, a `ClassCastException` is thrown.
```java
final String sql =
"select \"empid\" from \"hr\".\"emps\" where \"empid\" in (?, ?)";
CalciteAssert.hr()
.query(sql)
.consumesPreparedStatement(p -> {
p.setShort(1, (short) 100);
p.setShort(2, (short) 110);
})
.returnsUnordered("empid=100", "empid=110");
```
```
java.lang.ClassCastException: class java.lang.Short cannot be cast to class java.lang.Integer (java.lang.Short and java.lang.Integer are in module java.base of loader 'bootstrap')
at Baz$1$1.moveNext(Unknown Source)
at org.apache.calcite.linq4j.Linq4j$EnumeratorIterator.<init>(Linq4j.java:679)
```
=> [CALCITE-6265] Type coercion is failing for numeric values in prepared statements

core/src/main/java/org/apache/calcite/rel/rules/AggregateExpandDistinctAggregatesRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Given that we are already creating a select distinct and moving the filter condition in the aggregate call to project, there is no need to set the filter argument in the aggregate call.
=> [CALCITE-6333] NullPointerException in AggregateExpandDistinctAggregatesRule.doRewrite when rewriting filtered distinct aggregation

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
There are some issues in the `needNewSubQuery` -> `hasSortByOrdinal` method in [SqlImplementor](https://github.com/apache/calcite/blob/main/core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java#L1938C21-L1958) when using `RelToSqlConverter` specifying `NULLS LAST`, for some particular queries.
The method `hasSortByOrdinal` fails to recognize that the order might contain nested calls. For example, we can easily produce `SqlSelect -> SqlNodeList order -> SqlBasicCall (nulls last) -> SqlBasicCall (desc) -> SqlNumericLiteral`, but it can only match correctly if there's a single `SqlBasicCall` in the chain.
With that, this query:
```
select "product_id"
from "product"
where "net_weight" is not null
group by "product_id"
order by MAX("net_weight") desc nulls last 
```
Resolves …
=> [CALCITE-6355] RelToSqlConverter[ORDER BY] generates an incorrect order by when NULLS LAST is used in non-projected field

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumUtils.java, core/src/main/java/org/apache/calcite/adapter/enumerable/RexToLixTranslator.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java, linq4j/src/main/java/org/apache/calcite/linq4j/tree/Types.java
Address some issues on the original patch (https://github.com/apache/calcite/commit/4e6a320bf476c4b3c313d86f8ff3c6edf4c2a578 , via PR https://github.com/apache/calcite/pull/3687 )
See details in CALCITE-6265
=> [CALCITE-6265] Type coercion is failing for numeric values in prepared statements (follow-up)

core/src/main/java/org/apache/calcite/rel/rules/MultiJoinOptimizeBushyRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
This fix refuses to apply the MULTI_JOIN_OPTIMIZE_BUSHY optimization rule for multijoins that contain any outer joins.
=> [CALCITE-5289] Assertion failure in MultiJoinOptimizeBushyRule

redis/src/test/java/org/apache/calcite/adapter/redis/RedisCaseBase.java
Docker since 19.x deprecated image manifest v2 schema 1
and disabled since 26.x
it is also going to remove it since 27.x
as mentioned at https://docs.docker.com/engine/deprecated/#pushing-and-pulling-with-image-manifest-v2-schema-1
for that reason need to bump redis docker image which uses deprecated version
=> [CALCITE-6378] Bump Redis Docker image from 2.8.19 to 7.2.4

build.gradle.kts, core/src/test/java/org/apache/calcite/test/LintTest.java
The testContributorsFileIsSorted and testMailmapFile tests fail cause they rely on git and there is no git info available in source distribution.
In fact the tests don't really need git and the paths to the .mailmap and contributor.yml files can be specified explicitly. This removes the git requirement and also makes the tests more efficient since there is no process calls and lookup involved.
=> [CALCITE-6385] LintTest fails when run in source distribution

.github/workflows/main.yml, Jenkinsfile, arrow/build.gradle.kts
First commit removes `add-opens` flag to reproduce the issue on gha
Second commit to fix the problem both for gha and local run
=> [CALCITE-6387] Make Arrow adapter passing tests with jdk17+

core/src/main/java/org/apache/calcite/runtime/FlatLists.java, core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java, core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
This fix is simpler than #3780 and should cover all sizes, not just 7
=> [CALCITE-6376] Selecting 6 columns with QUALIFY operation results in exception

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/type/ReturnTypes.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
* The existing power function is moved to all non PostgreSQL libraries
* The new power function is only for PostgreSQL
* The new function returns a decimal if any argument is a decimal
=> [CALCITE-6313] Add POWER function for PostgreSQL

core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-6400
=> [CALCITE-6400] MAP_ENTRIES function should throw if a key value is null

core/src/main/java/org/apache/calcite/tools/RelBuilder.java, core/src/main/java/org/apache/calcite/util/Bug.java, core/src/test/java/org/apache/calcite/test/RelBuilderTest.java
Calculate the post-pruning RelTraitSet on the projection using TraitSet#apply(Mapping)
=> [CALCITE-6340] RelBuilder drops traits when aggregating over duplicate projected fields

babel/src/test/java/org/apache/calcite/test/BabelQuidemTest.java, core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/SqlBasicFunction.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/main/java/org/apache/calcite/util/format/PostgresqlDateTimeFormatter.java, core/src/test/java/org/apache/calcite/util/format/PostgresqlDateTimeFormatterTest.java, core/src/test/resources/pg_to_char_queries.sql, core/src/test/resources/to_char_generate_iq.py, testkit/src/main/java/org/apache/calcite/test/QuidemTest.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
* Splits the PostgreSQL toChar function off to its own function
* Does not implement SP suffix
* Timezone patterns are supported but all datetimes are in local timezone
=> [CALCITE-6358] Support all PostgreSQL 14 date/time patterns for to_char

core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java, core/src/main/java/org/apache/calcite/sql/type/ReturnTypes.java, core/src/main/java/org/apache/calcite/sql2rel/StandardConvertletTable.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-6397
=> [CALCITE-6397] Add NVL2 function (enabled in Oracle, Spark library)

babel/src/main/codegen/config.fmpp, babel/src/main/codegen/includes/parserImpls.ftl, babel/src/test/resources/sql/postgresql.iq, babel/src/test/resources/sql/redshift.iq, core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/SqlIntervalQualifier.java, core/src/main/java/org/apache/calcite/sql/fun/SqlExtractFunction.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
* PostgreSQL expects the first argument to be a string
* The first argument can be any expression that results in a valid time unit string
* RedShift and PostgreSQL share the same implementation
=> [CALCITE-6311] Support PostgreSQL DATE_PART

babel/src/test/java/org/apache/calcite/test/BabelParserTest.java, core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java, core/src/test/java/org/apache/calcite/tools/PlannerTest.java, testkit/src/main/java/org/apache/calcite/sql/parser/SqlParserTest.java
=> [CALCITE-6434] JDBC adapter generates wrong SQL for Spark and Hive because it fails to quote an identifier containing '$'

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/type/ReturnTypes.java, testkit/src/main/java/org/apache/calcite/sql/test/SqlOperatorFixture.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorFixtureImpl.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
ARRAY_AGG in BigQuery and Postgres returns NULL if there are zero input rows or expression evaluates to NULL for all rows.
However, it will return `ARRAY<arg0> NOT NULL` in the return type of the function definition.
https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#array_agg
https://www.postgresql.org/docs/8.4/functions-aggregate.html
=> [CALCITE-6008] ARRAY_AGG should returns ARRAY NULL when there's no input rows

babel/src/test/java/org/apache/calcite/test/BabelParserTest.java, site/_docs/reference.md
Calcite has been supporting MAP types for a long time, but they do not show up in the documentation.
=> Document MAP types in grammar

core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java, site/_docs/reference.md
As discussed in the JIRA, this seems to be a documentation bug
=> [CALCITE-6442] Validator rejects FILTER in OVER windows

babel/src/test/resources/sql/postgresql.iq, core/src/main/java/org/apache/calcite/sql/SqlBasicFunction.java, core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql2rel/StandardConvertletTable.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
* Add new GREATEST and LEAST functions for PostgreSQL
* The new functions only return null if all arguments are null
* Created a new library for RedShift since it is not truly a union of Oracle and PostgreSQL functions
=> [CALCITE-5634] Enable GREATEST, LEAST functions in PostgreSQL library

core/src/main/java/org/apache/calcite/rel/rules/SortRemoveConstantKeysRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
See more info in [CALCITE-6460](https://issues.apache.org/jira/browse/CALCITE-6460)
=> [CALCITE-6460] SortRemoveConstantKeysRule fails with AssertionError due to mismatched collation on resulting Sort

core/src/main/java/org/apache/calcite/rex/RexSimplify.java, core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml, core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml, core/src/test/resources/sql/sub-query.iq, druid/src/test/java/org/apache/calcite/test/DruidAdapter2IT.java, druid/src/test/java/org/apache/calcite/test/DruidAdapterIT.java
Conversion path for comparisions generated from IN expressions was handling types differently. This may have lead to some over-simplification in some cases.
Altered the conversion to do the full SqlToRex conversion steps for these generated nodes as well. Added an extra safeguard check to RexSimplify to prevent the bug from being triggered.
=> [CALCITE-6435] SqlToRel conversion of IN expressions may lead to incorrect simplifications

babel/src/test/resources/sql/spark.iq, core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/type/ReturnTypes.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-6445
Add Function [REVERSE](https://spark.apache.org/docs/latest/api/sql/#reverse) in Spark library.
=> [CALCITE-6445] Add REVERSE function (enabled in Spark library)

core/src/main/java/org/apache/calcite/rex/RexSimplify.java, core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
In `RexSimplify.simplifyCast` after constant reduction return the reduced expressions operand as result if the reduced expression and it's operand type is equal but different in nullability.
=> [CALCITE-6453] Simplify casts which are result of constant reduction

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumUtils.java, core/src/main/java/org/apache/calcite/adapter/enumerable/JavaRowFormat.java, core/src/main/java/org/apache/calcite/interpreter/Row.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/test/java/org/apache/calcite/test/LargeGeneratedJoinTest.java
Fix errors about the code size being too large for a method when joining thousands of fields.
=> [CALCITE-3094] Code of method grows beyond 64 KB when joining two tables with many fields

core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/test/resources/sql/operator.iq, core/src/test/resources/sql/sort.iq, linq4j/src/main/java/org/apache/calcite/linq4j/function/Functions.java
* <, <=, >, >= now work for arrays and rows
* Can also sort arrays and rows
* Comparison is performed along corresponding indexes
* Longer arrays are considered greater
* null is considered greater than anything
* Cannot change whether nulls are first or last
=> [CALCITE-6454] Implement array comparison operators

ubenchmark/README.md, ubenchmark/build.gradle.kts
1. Add jmh.includes property to specify benchmarks to run.
2. Update README instructions for running JMH benchmarks.
=> [CALCITE-6470] Run specific JMH benchmarks without modifying sources

core/src/main/java/org/apache/calcite/rel/metadata/RelMdMaxRowCount.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMdRowCount.java, core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
=> [CALCITE-6474] Aggregate with constant key can get a RowCount greater than its MaxRowCount

arrow/src/main/java/org/apache/calcite/adapter/arrow/ArrowTable.java, arrow/src/main/java/org/apache/calcite/adapter/arrow/ArrowTranslator.java, arrow/src/test/java/org/apache/calcite/adapter/arrow/ArrowAdapterTest.java, core/src/main/java/org/apache/calcite/util/Bug.java
Add the unary `isnull` Gandiva operator to `ArrowTranslator`.
=> [CALCITE-6296] Support IS NULL in Arrow adapter

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-6312
https://issues.apache.org/jira/browse/CALCITE-6456
=> [CALCITE-6312] Add LOG function (enabled in PostgreSQL library)

site/_docs/reference.md
The description of the `TRIM` function
`Removes the longest string containing only the characters in string1 from the start/end/both ends of string1`
should be the following to be accurate:
`Removes the longest string containing only the characters in string1 from the start/end/both ends of string2` (last word should be `string2` and not `string1`)
=> [CALCITE-6487] TRIM function documentation refers to string1 two times

arrow/src/main/java/org/apache/calcite/adapter/arrow/ArrowTranslator.java, arrow/src/test/java/org/apache/calcite/adapter/arrow/ArrowAdapterTest.java, core/src/main/java/org/apache/calcite/util/Bug.java
Analogous change to [[CALCITE-6296] Support IS NULL in Arrow adapter](https://github.com/apache/calcite/commit/e371b336a8b404ed36955f517196a5e8606455d7). I've adjusted the test cases to align with what we've merged for `IS NULL` support in the arrow adapter to make this part of the test code a bit more predictable.
=> [CALCITE-6295] Support IS NOT NULL in Arrow adapter

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, site/_docs/reference.md
Enabled the LEN function for:
* Amazon Redshift
* Snowflake
* Spark
Enabled the LENGTH function for:
* BigQuery
* Hive
* PostgreSQL
* Amazon Redshift
* Snowflake
* Spark
=> [CALCITE-6483] Enable LEN and LENGTH in the correct function libraries

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumUtils.java, core/src/main/java/org/apache/calcite/rex/RexBuilder.java, core/src/main/java/org/apache/calcite/sql/SqlNumericLiteral.java, core/src/test/resources/org/apache/calcite/test/TypeCoercionConverterTest.xml, linq4j/src/main/java/org/apache/calcite/linq4j/tree/Expressions.java, linq4j/src/main/java/org/apache/calcite/linq4j/tree/UnaryExpression.java, testkit/src/main/java/org/apache/calcite/sql/test/SqlOperatorFixture.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
This is a piece of https://github.com/apache/calcite/pull/3589 which only contains the fix to CALCITE-6169
This also fixes CALCITE-6366
The main part of the fix is implementing Expressions.convertChecked.
There was a recent implementation of this method, but we replace it in the generated Java code with a call to Primitive.numberValue, which covers more cases than the existing implementation.
=> [CALCITE-6169] EnumUtils.convert does not implement the correct SQL cast semantics

core/src/main/java/org/apache/calcite/rel/rules/ProjectSetOpTransposeRule.java
Minor improvement to enlarge ProjectSetOpTransposeRule's adaptability.
More info: CALCITE-6495
=> [CALCITE-6495] Allow ProjectSetOpTransposeRule to work with any subclass of Project

elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/ElasticSearchAdapterTest.java
I'm working on the `LIKE` operator for Elasticsearch and noticed that the `ElasticSearchAdapterTests` are not using a helper method setting up a connection to Elasticsearch consistently, but rather duplicate code sometimes. I want to keep the change separate to not clutter the diff in the `LIKE` operator PR.
=> [CALCITE-6497] Use helper setup method throughout whole ElasticsearchAdapterTest

core/src/main/codegen/templates/Parser.jj, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
There was another bug in the parsing of array ITEM operators, which was uncovered by this fix.
=> [CALCITE-6502] Parser loses position information for Expression3

.github/workflows/buildcache.yml, .github/workflows/main.yml, gradle.properties, settings.gradle.kts
This change migrates Calcite to use the Develocity Gradle Plugin. The existing Gradle Enterprise Gradle Plugin will no longer be supported when ge.apache.org is updated to 2024.3.
These changes will not functionally change how build scans are published to ge.apache.org.
=> [CALCITE-6511] Migrate from Gradle Enterprise Gradle Plugin to Develocity Gradle Plugin

core/src/main/java/org/apache/calcite/sql/SqlNumericLiteral.java, core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java, core/src/main/java/org/apache/calcite/util/Bug.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
The comment below is no longer accurate after the PR was split into two separate PRs.
--------------
I initially started with the goal of fixing just [CALCITE-3522], https://issues.apache.org/jira/browse/CALCITE-3522, which is limiting the size of decimal literals to 64 bits. The fix is to actually check the precision of the type system when rejecting a decimal literal. That's easy. I am not checking the scale, under the assumption that rounding is OK for literals but losing precision is not.
However, fixing this problem unmasked a bunch of other bugs in handling large values, so in order to make the tests pass I had to also fix [CALCITE-6169], which is about incorrect casts between numeric values. There is still one case which is not handled, which is casts between decimal values that …
=> [CALCITE-3522] SqlValidator.validateLiteral rejects literals with a DECIMAL type that require more than 64 bits

core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java
Noticed that there are no tests for `SqlFunctions#overlay`, so adding them with this PR.
=> [CALCITE-6490] Missing tests for SqlFunctions#overlay

core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
https://issues.apache.org/jira/browse/CALCITE-6471
This patch replaces all unconditional conversions of SqlNode to string in SqlToRelConverter with on-demand message suppliers for null checks (`requireNonNull`).
=> [CALCITE-6471] Improve performance of SqlToRelConverter by preventing unconditional conversion of sqlNodes to string for null-check messages 

core/src/test/java/org/apache/calcite/examples/RelBuilderExample.java
The original for loop was set to iterate from 0 to 3, which excluded the case 4 from being processed in the doExample method. This commit updates the loop condition to i <= 4 to ensure all cases are covered.
=> Enable more tests in RelBuilderExample

core/src/main/java/org/apache/calcite/rel/type/RelDataTypeSystem.java, core/src/test/java/org/apache/calcite/sql/type/RelDataTypeSystemTest.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java, core/src/test/java/org/apache/calcite/test/TypeCoercionTest.java, core/src/test/resources/sql/measure-paper.iq, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
Alternative PR to #3855. I have taken some tests from that PR, but adjusted the algorithm.
See the JIRA and the comments for a justification.
=> [CALCITE-6464] Type inference for DECIMAL division seems incorrect

core/src/main/java/org/apache/calcite/sql/SqlFunction.java, core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/SqlUtil.java, core/src/main/java/org/apache/calcite/util/Util.java, testkit/src/main/java/org/apache/calcite/sql/test/SqlOperatorFixture.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
The PR is much more involved than expected, because it also solves another bug where functions declared in multiple libraries cannot be resolved by the validator. There were no tests using multiple libraries at the same time.
=> [CALCITE-6518] ClassCastException during validation when loading multiple libraries

core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java, core/src/test/java/org/apache/calcite/test/MaterializedViewSubstitutionVisitorTest.java
Assertion errors occur in some joinUnifyRules because of the change in nullable type produced by the join. Intercepts these cases and replaces the assertion error with a return of null. For a specific example, see the test.
=> [CALCITE-6501] Assertion Error in JoinUnifyRule Due to Type Mismatch

core/src/main/java/org/apache/calcite/rel/type/RelDataTypeSystem.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
Turns out it's a bug I introduced during the fix for https://issues.apache.org/jira/browse/CALCITE-6464
=> [CALCITE-6533] Division between integer and decimal produces incorrect result

core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java, core/src/test/java/org/apache/calcite/test/MaterializedViewSubstitutionVisitorTest.java
This PR addresses both [CALCITE-6534] and [CALCITE-6528] and is based on [CALCITE-6501]. For the problem of nullablility due to Join null-side, if RexNode satisfies null-if-null, we will adjust the nullability, if not, we should reject this rewrite regardless of the nullablility.
=> [CALCITE-6534] Adjust type when pulling up Calc in JoinUnifyRule

core/src/main/java/org/apache/calcite/sql/validate/AbstractNamespace.java
Some other classes add isInstance judgments before calling clazz.cast
=> AbstractNamespace unwrap add isInstance judgments

core/src/main/java/org/apache/calcite/plan/RelOptCost.java, core/src/main/java/org/apache/calcite/plan/RelOptCostImpl.java, core/src/main/java/org/apache/calcite/plan/volcano/VolcanoCost.java
=> [CALCITE-6543] Change the RelOptCostImpl toString method to be consistent with VolcanoCost

core/src/main/codegen/templates/Parser.jj, testkit/src/main/java/org/apache/calcite/sql/parser/SqlParserTest.java
Allows sub-queries to be used in grammar for operands to square-bracketed array constructor function.
=> [CALCITE-6508] Parse error when using scalar sub-query as operand to Array constructor function

testkit/src/main/java/org/apache/calcite/sql/test/SqlOperatorFixture.java, testkit/src/main/java/org/apache/calcite/sql/test/SqlTester.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java, testkit/src/main/java/org/apache/calcite/util/TestUtil.java
The VmName.FENNEL does not seem to be used anywhere, so I deleted it.
I also re-enabled a few SqlOperatorTest tests that work given recent fixes.
And fixed a tiny bug in the regex quoting code.
There are many more disabled tests that should be audited. I audited some of them, and they still fail (or I would have enabled them).
=> Remove FENNEL VM; enable some disabled tests

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/test/resources/sql/functions.iq, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
* All libraries now have a BITCOUNT() function
* The MySQL library also has BIT_COUNT() which is an alias for BITCOUNT()
* BITCOUNT() counts all of the bits set in an integer or bytestring
* Return NULL if the argument is NULL
This is based on a previous PR that appears dormant.
https://github.com/apache/calcite/pull/1746
=> [CALCITE-3697] Implement BITCOUNT scalar function

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/CalciteResource.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java, core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java, core/src/main/java/org/apache/calcite/sql/type/ReturnTypes.java, core/src/main/resources/org/apache/calcite/runtime/CalciteResource.properties, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
* All three functions accept either a pair of Integer or Binary values as arguments
* Binary arguments must be of the same length
* Returns NULL if any argument is NULL
* Returns a value of the same type as the first argument if both arguments are not null
=> [CALCITE-3779] Implement BITAND, BITOR, BITXOR scalar functions

core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java, core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml, core/src/test/resources/sql/sub-query.iq
Check for correlation variables in intermediate project when converting aggregation.
Its probably wise for us to check other places where this may be an issue.
I'm open to alternative solutions which have a wider effect, such as having the RelBuilder or even the constructor collect the correlation variables when the variable set is otherwise undefined.
=> [CALCITE-6554] Check for correlation variables in project during SqlToRelConverter.createAggImpl

core/src/main/java/org/apache/calcite/sql/SqlIntervalQualifier.java, core/src/test/java/org/apache/calcite/sql/parser/SqlParserUtilTest.java, core/src/test/resources/sql/misc.iq
WEEK and QUARTER intervals were incorrectly treated like HOUR and MONTH respectively. This patch fixes the handling, and adds unit tests.
This patch also renames the two "fillIntervalValueArray" methods to "fillDayIntervalValueArray" (for INTERVAL_DAY_TIME type intervals) and "fillYearMonthIntervalValueArray" (for INTERVAL_YEAR_MONTH type intervals) to make it more clear which one is which.
=> [CALCITE-6581] Incorrect INTERVAL math for WEEK and QUARTER

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java, core/src/main/java/org/apache/calcite/rel/core/AggregateCall.java, core/src/main/java/org/apache/calcite/rel/core/Window.java, core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateCaseToFilterRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateExpandDistinctAggregatesRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateExpandWithinDistinctRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateFilterTransposeRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateReduceFunctionsRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateRemoveRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateStarTableRule.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateUnionTransposeRule.java, core/src/main/java/org/apache/calcite/rel/rules/ProjectAggregateMergeRule.java, core/src/main/java/org/apache/calcite/rel/rules/ReduceDecimalsRule.java, core/src/main/java/org/apache/calcite/rel/rules/materialize/MaterializedViewAggregateRule.java, core/src/main/java/org/apache/calcite/rex/RexBuilder.java, core/src/main/java/org/apache/calcite/rex/RexCall.java, core/src/main/java/org/apache/calcite/rex/RexCopier.java, core/src/main/java/org/apache/calcite/rex/RexSimplify.java, core/src/main/java/org/apache/calcite/rex/RexUtil.java, core/src/main/java/org/apache/calcite/sql/SqlSplittableAggFunction.java, core/src/main/java/org/apache/calcite/sql2rel/AggConverter.java, core/src/main/java/org/apache/calcite/sql2rel/RelDecorrelator.java, core/src/main/java/org/apache/calcite/sql2rel/RelStructuredTypeFlattener.java, core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/main/java/org/apache/calcite/sql2rel/StandardConvertletTable.java, core/src/main/java/org/apache/calcite/tools/RelBuilder.java, core/src/test/java/org/apache/calcite/materialize/NormalizationTrimFieldTest.java, core/src/test/java/org/apache/calcite/test/fuzzer/RexShrinker.java
This PR adds source position (`SqlParserPos`) information to two kinds of nodes:
- RexCall
- AggregateCall
Not all RexCall nodes and AggregateCall operations need to have meaningful source position information. The most useful nodes are the ones that could lead to runtime errors. So operations like addition (which can overflow) or casts (which can fail when the target type is too narrow) need to carry such information. Nodes where the operation cannot fail dynamically (e.g., MAX, comparisons, or IS_NULL) may have the source position set to ZERO.
In this PR I have carefully audited the entire code base and tried to thread the flow of the position information everywhere, but there are a few places where I couldn't figure out where it should come from. There are, for example, a few casts …
=> [CALCITE-6071] RexCall should carry source position information for runtime error reporting

core/src/main/java/org/apache/calcite/util/format/FormatElementEnum.java, core/src/main/java/org/apache/calcite/util/format/FormatModels.java, core/src/test/java/org/apache/calcite/util/format/FormatElementEnumTest.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-6226
=> [CALCITE-6226] Wrong ISOWEEK and no ISOYEAR on BigQuery FORMAT_DATE

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql2rel/StandardConvertletTable.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
The following is my recent review of why the BC date is equal to 0000.
In calcite, the date function will go through a series of conversions, such as the bigquery date_add function will be converted to DATETIME_PLUS later,and the current adapted DATE_ADD is no exception.
After being converted to DATETIME_PLUS, it seems that it will be converted to PLUS operator operation later, and finally enter `RexlmpTable.DatetimeArithmeticImplementor `to perform parameter type conversion and partial calculation, `return normalize(typeName, Expressions.add(trop0, trop1))`. Of course, there may be higher levels of abstraction and conversion later, but unfortunately I haven't found it yet.
In this process, I found that calcite did not restrict the result set of the date function to the date BC date and …
=> [CALCITE-6527] Add DATE_ADD function (enabled in Spark library)

arrow/src/main/java/org/apache/calcite/adapter/arrow/ArrowTranslator.java, arrow/src/test/java/org/apache/calcite/adapter/arrow/ArrowAdapterTest.java, core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java, core/src/main/java/org/apache/calcite/rex/RexBuilder.java, core/src/main/java/org/apache/calcite/rex/RexLiteral.java, core/src/main/java/org/apache/calcite/tools/RelBuilder.java, core/src/main/java/org/apache/calcite/util/Util.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java, core/src/test/java/org/apache/calcite/rex/RexExecutorTest.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/java/org/apache/calcite/util/UtilTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml, core/src/test/resources/org/apache/calcite/test/TypeCoercionConverterTest.xml, core/src/test/resources/sql/cast.iq, druid/src/main/java/org/apache/calcite/adapter/druid/DruidExpressions.java, druid/src/test/java/org/apache/calcite/test/DruidAdapter2IT.java, druid/src/test/java/org/apache/calcite/test/DruidAdapterIT.java, piglet/src/main/java/org/apache/calcite/piglet/PigRelExVisitor.java, piglet/src/test/java/org/apache/calcite/test/PigRelExTest.java, piglet/src/test/java/org/apache/calcite/test/PigRelOpTest.java, site/_docs/history.md, testkit/src/main/java/org/apache/calcite/util/TestUtil.java
This is another attempt to fix [CALCITE-2067]. 
PR #572 attempted to do this, but wasn't merged about 8 years ago.
This PR includes very similar changes.
The current implementation of RexLiteral uses a BigDecimal value to store DOUBLE values. This is a problem for 2 reasons:
- it loses precision, since some FP values cannot be stored precisely in decimal notation
- it cannot represent special FP values, such as -0.0, Infinity, or NaN
With this PR these issues are solved. As a side-effect, this enables the simplification engine to simplify some expressions that it couldn't before, such as expressions that produce special FP values.
Objections to the original PR which can be seen here: https://issues.apache.org/jira/browse/CALCITE-2067 include the fact that this "changes the SQL language …
=> [CALCITE-2067] RexLiteral cannot represent accurately floating point values, including NaN, Infinity

core/src/main/java/org/apache/calcite/rel/rules/AggregateJoinTransposeRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
=> [CALCITE-6600] AggregateJoinTransposeRule can throw ArrayIndexOutOfBoundsException when applied on a SemiJoin

core/src/main/java/org/apache/calcite/adapter/enumerable/EnumUtils.java, core/src/main/java/org/apache/calcite/adapter/enumerable/JavaRowFormat.java, core/src/main/java/org/apache/calcite/config/CalciteSystemProperty.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/test/java/org/apache/calcite/test/LargeGeneratedJoinTest.java
The fix is quite simple. I added tests for left join and right join with empty tables.
The test file changed a bit more than expected because: 
- I extracted some code to be reused in the other tests;
- I removed a `query.WithHook` because it was not being used, as this call doesn't mutate the query object;
- I changed the field names to be able to select them easily on the right outer join.
=> [CALCITE-6593] NPE when outer joining tables with many fields and unmatching rows

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java, core/src/main/java/org/apache/calcite/sql/type/ReturnTypes.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
* Implemented the BITNOT scalar function as a standard function
* Supports integer and binary arguments
* Returns NULL if the argument is NULL
=> [CALCITE-3592] Implement BITNOT scalar function

core/src/main/java/org/apache/calcite/tools/RelBuilder.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java, core/src/test/java/org/apache/calcite/test/RelBuilderTest.java, core/src/test/resources/sql/agg.iq, core/src/test/resources/sql/join.iq, core/src/test/resources/sql/outer.iq, core/src/test/resources/sql/winagg.iq
The issue fixed here was first reported as part of https://issues.apache.org/jira/browse/CALCITE-6617
=> [CALCITE-6620] VALUES created by RelBuilder do not have a homogeneous type

arrow/src/main/java/org/apache/calcite/adapter/arrow/ArrowTranslator.java, arrow/src/test/java/org/apache/calcite/adapter/arrow/ArrowAdapterTest.java
https://issues.apache.org/jira/browse/CALCITE-6618
=> [CALCITE-6618] Support NOT EQUALS operator in Arrow adapter

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/sql2rel/StandardConvertletTable.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-6612
=> [CALCITE-6612] Add DATE_SUB function(enabled in Spark library)

core/src/main/java/org/apache/calcite/sql/dialect/MssqlSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Invalid unparse for CEIL in MssqlSqlDialect
=> [CALCITE-6633] Add CEILING to MSSQL dialect

arrow/src/main/java/org/apache/calcite/adapter/arrow/ArrowFieldType.java, arrow/src/test/java/org/apache/calcite/adapter/arrow/ArrowAdapterTest.java
https://issues.apache.org/jira/browse/CALCITE-6637
=> [CALCITE-6637] Date type results should not be automatically converted to timestamp in Arrow adapters

core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
…n it's input include NULL VALUE
=> [CALCITE-6592] Add test for RelMdPredicates pull up predicate from UNION when it's input predicates include NULL VALUE

core/src/main/java/org/apache/calcite/sql/dialect/PrestoSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
PrestoSqlDialect by default will change any length function in a query to char_length function but char_length function is not available/supported in PrestoSql.
Add length function support in PrestoSqlDialect
=> [CALCITE-6643] Char_Length Function is not recognized in PrestoSql. Add LENGTH function in PrestoSqlDialect

core/src/main/java/org/apache/calcite/rel/rules/AggregateUnionTransposeRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
When pushing down aggregates through child branches of a union in `AggregateUnionTransposeRule`, the nullability of aggregated columns may differ from the nullability of the corresponding union'ed columns.
Hence, the declared types of the aggregates created in each branch must be re-evaluated when needed.
=> [CALCITE-6642] AggregateUnionTransposeRule should account for changes in nullability of pushed down aggregates

core/src/main/java/org/apache/calcite/materialize/Lattice.java, core/src/test/java/org/apache/calcite/materialize/LatticeSuggesterTest.java
https://issues.apache.org/jira/browse/CALCITE-6605
=> [CALCITE-6605] Lattice SQL supports complex column expressions

babel/src/test/resources/sql/postgresql.iq, core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
We can support split_part function for postgresq:
split_part ( string text, delimiter text, n integer ) → text
Splits string at occurrences of delimiter and returns the n'th field (counting from one), or when n is negative, returns the |n|'th-from-last field.
```
split_part('abc@~def@~ghi', '@~', 2) → def
split_part('abc,def,ghi,jkl', ',', -2) → ghi
```
=> [CALCITE-6663] Support SPLIT_PART function for PostgreSql

core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
The fix is to slightly change the validation order: 
- validate the SELECT list before the HAVING 
- perform type inference in HAVING before checking the aggregations
=> [CALCITE-6677] HAVING clauses fail validation when type coercion is applied to GROUP BY clause

core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
Reduced the number of type checks by moving the instanceof check outside the loop, improving performance and code clarity.
=> [CALCITE-6679] Reduced the number of type checks in VolcanoPlanner

testkit/src/main/java/org/apache/calcite/test/DiffRepository.java, testkit/src/test/java/org/apache/calcite/test/DiffRepositoryTest.java, testkit/src/test/resources/org/apache/calcite/test/DiffRepositoryTest.xml
Use JUnit instead of Hamcrest assert methods since the latter are not using/throwing the `AssertionFailedError` so we never enter the catch block that updates the log file.
Basically revert the DiffRepository part from https://github.com/apache/calcite/commit/9985b6af156d41fc4a986a9aadbf7f8227981388.
=> [CALCITE-6676] DiffRepository does not update log (_actual) file when assertion fails

core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java, core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java, core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml, core/src/test/resources/sql/misc.iq
Stop identifiers in a SQL call from being treated as aliases and expanded into select expressions.
For example:
`select replace(name, 'a', 'b') as name from users group by replace(name, 'a', 'b')`
The **name** in GROUP BY clause should not be replaced by `replace(name, 'a', 'b')`, it will be resolved as users.name,
i.e. 
`select replace(users.name, 'a', 'b') as name from users group by replace(users.name, 'a', 'b')`
Make the sql semantics unchanged when treating identifiers within Group By clause as aliases.
current calcite behavior:
`select replace(**name**, 'a', 'b') as **name** from users group by replace(**name**, 'a', 'b')`
will be expanded into
`select replace(**name**, 'a', 'b') as **name** from users group by replace(**replace(name, 'a', 'b')**, 'a', 'b')`
the semantics has been …
=> [CALCITE-4512] GROUP BY expression with argument name same with SELECT field and alias causes validation error

babel/src/test/resources/sql/spark.iq, core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/jdbc/JavaTypeFactoryImpl.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/test/java/org/apache/calcite/test/ReflectiveSchemaTest.java, core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableCalcTest.java, testkit/src/main/java/org/apache/calcite/test/schemata/catchall/CatchallSchema.java
Based on a patch submitted in Jira by Chris Dennis
https://issues.apache.org/jira/secure/attachment/13072690/is-empty-nullable.patch
Had to tweak some other parts of Calcite, since the Java type system claimed arrays and maps cannot be null.
I inspected some other array operations as well, hopefully I didn't miss any.
=> [CALCITE-6680] RexImpTable erroneously declares NullPolicy.NONE for IS_EMPTY

core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
Hive Supports INSTR(), add support for the same in Hive SqlLibrary.
Also post [HIVE-25230](https://issues.apache.org/jira/browse/HIVE-25230) Hive supports instr() with position and occurence, adding support for the same in HiveSqlDialect.
=> [CALCITE-6689] Add support for INSTR() in Hive SqlLibrary

core/src/main/java/org/apache/calcite/prepare/CalciteCatalogReader.java, core/src/main/java/org/apache/calcite/sql/validate/SqlUserDefinedFunction.java, core/src/main/java/org/apache/calcite/sql/validate/SqlUserDefinedTableFunction.java, core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java, core/src/test/java/org/apache/calcite/test/UdfTest.java, piglet/src/main/java/org/apache/calcite/piglet/PigUserDefinedFunction.java, plus/src/main/java/org/apache/calcite/chinook/CalciteConnectionProvider.java, testkit/src/main/java/org/apache/calcite/test/CalciteAssert.java, testkit/src/main/java/org/apache/calcite/util/Smalls.java
* pass SqlSyntax.FUNCTION_ID to SqlUserDefinedFunction when function has no parameters, and allowNiladicParentheses is false
* add udf test case for function without parentheses
=> [CALCITE-6645] Support user-defined function without parentheses when db dialect's allowNiladicParentheses property is false

core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcRules.java, core/src/main/java/org/apache/calcite/interpreter/Bindables.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnUniqueness.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMdPredicates.java, core/src/main/java/org/apache/calcite/rel/rules/AggregateProjectPullUpConstantsRule.java, core/src/main/java/org/apache/calcite/rel/rules/SortRemoveConstantKeysRule.java, core/src/main/java/org/apache/calcite/rel/rules/UnionPullUpConstantsRule.java, core/src/main/java/org/apache/calcite/util/Bug.java, core/src/test/java/org/apache/calcite/test/JdbcAdapterTest.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/java/org/apache/calcite/test/ScannableTableTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml, core/src/test/resources/sql/sub-query.iq, druid/src/test/java/org/apache/calcite/test/DruidAdapter2IT.java, druid/src/test/java/org/apache/calcite/test/DruidAdapterIT.java, innodb/src/main/java/org/apache/calcite/adapter/innodb/InnodbRules.java, innodb/src/main/java/org/apache/calcite/adapter/innodb/InnodbToEnumerableConverter.java
The fundamental problem this PR solves is to make RelMetadataQuery#getPulledUpPredicates(RelSubset) not always return EMPTY, allowing some rules to be applied in VolcanoPlanner.
However, after some rules were applied, there were some other issues that prevented the test from passing completely. So I split it into three commits for easy review
=> [CALCITE-6586] Some Rules not firing due to RelMdPredicates returning null in VolcanoPlanner

core/src/main/java/org/apache/calcite/sql2rel/AggConverter.java, core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java, core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml, core/src/test/resources/sql/agg.iq
Note that almost all deleted lines are from my incorrect previous fix for task [CALCITE-5209](https://issues.apache.org/jira/browse/CALCITE-5209)
=> [CALCITE-5590] NullPointerException when converting 'in' expression that is used inside select list and group by

core/src/main/java/org/apache/calcite/rex/RexProgram.java, core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
This operator does not seem to ever be instantiated.
=> Remove IN_FENNEL operator

arrow/src/main/java/org/apache/calcite/adapter/arrow/ArrowTable.java, arrow/src/main/java/org/apache/calcite/adapter/arrow/ArrowTranslator.java, arrow/src/test/java/org/apache/calcite/adapter/arrow/ArrowAdapterTest.java
https://issues.apache.org/jira/browse/CALCITE-6684
=> [CALCITE-6684] Support Arrow filter pushdown conditions that have subexpressions of a decimal type

core/src/main/java/org/apache/calcite/jdbc/CalciteConnectionImpl.java, core/src/test/resources/sql/dual-table-query.iq, core/src/test/resources/sql/dummy.iq
* Use view table to implement dual table query for better optimize
* Move dual table query test case to new `dual-table-query.iq` file
=> [CALCITE-6678] Calcite should support dual table query when db provides this feature

core/src/main/codegen/templates/Parser.jj, core/src/main/java/org/apache/calcite/runtime/CalciteResource.java, core/src/main/resources/org/apache/calcite/runtime/CalciteResource.properties, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/sql/parser/SqlParserTest.java
I rewrote the parser in such a way that the `illegalFromEmpty` exception is no longer necessary.
The case covered by the exception will cause a parse error instead.
=> [CALCITE-6709] Parser accepts a call to TRIM() with no arguments

site/_docs/reference.md
In reference document - https://calcite.apache.org/docs/reference.html#dialect-specific-operators, `CONCAT_WS` and `REVERSE` functions had rendering problems because their syntax included `|` without using escape characters.
* CONCAT_WS:
* REVERSE:
=> Site: Reformat CONCAT_WS and REVERSE document

elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/AggregationTest.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/EmbeddedElasticsearchPolicy.java
Set "**fielddata**" to "**true**" in Elasticsearch mapping, since aggregations and sorting are disabled by default for text type.
It's only set in the test module, which provides instruction for SQL users when they want to group or sort text field.
=> [CALCITE-4954] Group TEXT field failed in Elasticsearch Adapter

core/src/main/java/org/apache/calcite/sql/SqlBasicFunction.java, core/src/test/java/org/apache/calcite/rex/RexNormalizeTest.java, core/src/test/java/org/apache/calcite/rex/RexProgramBuilderBase.java, core/src/test/java/org/apache/calcite/test/RelBuilderTest.java
`SqlBasicFunction` did not override `SqlOperator#reverse()` so functions belonging to the `SqlKind.SYMMETRICAL` set threw a NPE [during normalization](https://github.com/apache/calcite/blob/8b4136bbd183f10e72c2ec02bef9caf1748631c2/core/src/main/java/org/apache/calcite/rex/RexNormalize.java#L102). 
This PR adds a overridden `reverse()` method to `SqlBasicFunction` that returns the operator if `isSymmetrical()` is true.
=> [CALCITE-6688] Allow operators of SqlKind.SYMMETRICAL to be reversed

core/src/test/java/org/apache/calcite/test/RelMetadataTest.java, testkit/src/main/java/org/apache/calcite/test/catalog/MockCatalogReader.java, testkit/src/test/java/org/apache/calcite/test/MockTableTest.java
MockTable currently allows only one key to be specified; the key can be either simple or composite. In real scenarios though a table can have multiple keys.
1. Add `MockTable#addKey` API to explicitly support multiple (individual & composite) keys.
2. Modify `MockTable#addColumn` to create individual keys when `isKey` is `true`. There is a slight change in behavior since when the method is called multiple times for the same table it will now create multiple simple keys instead of one composite.
=> [CALCITE-6724] MockTable support for multiple (individual & composite) keys

core/src/main/java/org/apache/calcite/sql/dialect/MssqlSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
MOD is not supported in MSSQL. Translate it to %.
=> [CALCITE-6726] Add translation for MOD operator in MSSQL

core/src/main/java/org/apache/calcite/sql/validate/implicit/AbstractTypeCoercion.java, core/src/test/java/org/apache/calcite/test/TypeCoercionTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml, core/src/test/resources/sql/agg.iq, core/src/test/resources/sql/misc.iq, core/src/test/resources/sql/sub-query.iq
The current implementation is based on the rules for inferring the result for addition (but does not require an extra digit).
=> [CALCITE-6733] Type inferred by coercion for comparisons with decimal is too narrow

core/src/main/java/org/apache/calcite/rel/rules/LoptMultiJoin.java, core/src/main/java/org/apache/calcite/rel/rules/LoptOptimizeJoinRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
This patch restores the original behavior of {{LoptOptimizeJoinRule.java}} prior #2189
=> [CALCITE-6737] LoptOptimizeJoinRule can not identify selfjoin on unique join keys

core/src/main/java/org/apache/calcite/adapter/enumerable/RexToLixTranslator.java, core/src/main/java/org/apache/calcite/sql/validate/implicit/AbstractTypeCoercion.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java, core/src/test/java/org/apache/calcite/test/TypeCoercionTest.java, core/src/test/resources/sql/misc.iq
I also had to implement in the RexToLixTranslator casts between ROW types.
=> [CALCITE-6735] Type coercion for comparisons does not coerce ROW types

core/src/main/java/org/apache/calcite/util/Bug.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchMethod.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchRel.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchSort.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchTable.java, elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchToEnumerableConverter.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/AggregationAndSortTest.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/ElasticSearchAdapterTest.java
Support NULLS LAST/FIRST SQL semantics by modifying Elasticsearch scripts.
=> [CALCITE-4860] In Elasticsearch adapter, support NULLS FIRST and NULLS LAST query

core/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnUniqueness.java, core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
In the existing test
```
// RelMetadataTest.java
@Test void testColumnUniquenessForJoinOnLimit1() {
final String sql = ""
+ "select *\n"
+ "from emp A\n"
+ "join (\n"
+ "  select * from emp\n"
+ "  limit 1) B\n"
+ "on A.empno = B.empno";
sql(sql)
.assertThatAreColumnsUnique(bitSetOf(0), is(true))
.assertThatAreColumnsUnique(bitSetOf(1), is(true))
.assertThatAreColumnsUnique(bitSetOf(9), is(true))
.assertThatAreColumnsUnique(bitSetOf(10), is(true))
.assertThatAreColumnsUnique(bitSetOf(), is(true))
.assertThatUniqueKeysAre(bitSetOf());
} 
```
the join result column `A.ENAME` is considered to be unique because `A.EMPNO` is the unique key. The test still passes when the query changes to left join, in which case `A.ENAME` is not guaranteed to be unique.
=> [CALCITE-6727] Column uniqueness constrain should only apply to inner join

core/src/main/java/org/apache/calcite/rel/rules/ProjectWindowTransposeRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
The visitor that keep track of the used fields did not account for the window bounds.
=> [CALCITE-6746] Optimization rule ProjectWindowTranspose is unsound

core/src/main/java/org/apache/calcite/sql/dialect/MysqlSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
StarRocks does not support the following `EXTRACT` unit syntax, and `StarRocksSqlDialect` may require some adjustments to accommodate this.
For example:
```
SELECT EXTRACT(DOW FROM DATE '2023-12-01');
SELECT EXTRACT(DOY FROM DATE '2023-12-01');
```
To ensure compatibility during the StarRocks dialect conversion, the above syntax can be translated as follows:
```
SELECT DAYOFWEEK(DATE '2023-12-01');
SELECT DAYOFYEAR(DATE '2023-12-01');
```
=> [CALCITE-6761] StarRocks generates incorrect SQL for certain units in the EXTRACT function

core/src/main/java/org/apache/calcite/adapter/enumerable/RexToLixTranslator.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/test/resources/sql/misc.iq, testkit/src/main/java/org/apache/calcite/test/CalciteAssert.java
While fixing this bug I uncovered two more bugs, https://issues.apache.org/jira/browse/CALCITE-6752 and https://issues.apache.org/jira/browse/CALCITE-6753. Some of the code changes are workarounds for these other bugs.
=> [CALCITE-6751] Reduction of CAST from string to interval is incorrect

core/src/main/java/org/apache/calcite/sql/dialect/StarRocksSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
When performing starrocks dialect conversion for varchar, it defaults to using MySQL dialect，MySQL doesn't have a VARCHAR type, only CHAR,So during StarRocks dialect conversion, VARCHAR will also be converted to CHAR
Since StarRocks supports the VARCHAR type, we should modify the StarRocks dialect
https://docs.starrocks.io/docs/sql-reference/data-types/string-type/VARCHAR/
=> [CALCITE-6699] Invalid unparse for Varchar in StarRocksDialect

core/src/main/java/org/apache/calcite/sql/dialect/PrestoSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
In Calcite, if the dialect's `supportsImplicitTypeCoercion` is set to `true` (the default value is `true`), Calcite will remove the cast in the `SqlImplementor#stripCastFromString()` method. For example, the following SQL:
```
FROM applydata_bigdata.kafka_topic_cluster_user_dept_month_one_day_msg_info
WHERE ymd > CAST('20240801' AS INTEGER)
ORDER BY ymd DESC
```
will be transformed into:
```
FROM "hive"."applydata_bigdata"."kafka_topic_cluster_user_dept_month_one_day_msg_info"
WHERE "ymd" > '20240801'
ORDER BY "ymd" IS NULL DESC, "ymd" DESC LIMIT 200
```
Here, the `CAST` is removed.
However, in Presto, different data types cannot be directly compared, which will result in an error. 
Similar situations also exist:
```
select * from …
```
=> [CALCITE-6762] Preserving the CAST conversion for String type operands in Presto

core/src/main/java/org/apache/calcite/prepare/CalciteCatalogReader.java, core/src/test/java/org/apache/calcite/test/UdfTest.java
- Jira link: https://issues.apache.org/jira/browse/CALCITE-6745
=> [CALCITE-6745] UDF without parameters cannot be validated when use default conformance

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/test/java/org/apache/calcite/rex/RexExecutorTest.java
=> [CALCITE-6775] ToChar and ToTimestamp PG implementors should use translator's root instead of creating a new root expression

core/src/main/java/org/apache/calcite/sql/dialect/PrestoSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Since FLOAT type is not supported in Presto
According to the documentation: https://prestodb.io/docs/current/language/types.html#real
Using CAST(xxxx AS FLOAT) will result in an error:
```
SELECT CAST(message_count AS FLOAT)
FROM applydata_bigdata.kafka_topic_cluster_user_dept_month_one_day_msg_info
WHERE ymd = 20250105
```
It should be converted to the DOUBLE type instead.
=> [CALCITE-6771] Convert Type from FLOAT to DOUBLE in PrestoDialect

.github/workflows/main.yml, gradle.properties, settings.gradle.kts
This PR migrates the Calcite project to publish Build Scans to the the new Develocity instance at develocity.apache.org.
=> [CALCITE-6769] Publish build scans to develocity.apache.org

core/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnOrigins.java, core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
=> [CALCITE-6744] RelMetadataQuery.getColumnOrigins should return null when column origin includes correlation variables

core/src/main/java/org/apache/calcite/rel/type/RelDataTypeFactory.java, core/src/main/java/org/apache/calcite/rel/type/RelDataTypeFactoryImpl.java, core/src/main/java/org/apache/calcite/rex/RexBuilder.java, core/src/main/java/org/apache/calcite/sql/type/BasicSqlType.java, core/src/main/java/org/apache/calcite/sql/type/SqlTypeFactoryImpl.java, core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java, core/src/test/java/org/apache/calcite/test/TableInRootSchemaTest.java, site/_docs/history.md
We have already merged a PR fixing this issue, but I have reopened it, and this is a second PR addressing a second bug related to the same problem.
=> [CALCITE-6764] Field access from a nullable ROW should be nullable (part 2)

core/src/main/java/org/apache/calcite/sql/dialect/VerticaSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
correctly unparse Vertica [LIMIT](https://docs.vertica.com/24.2.x/en/sql-reference/statements/select/limit-clause/) ... [OFFSET](https://docs.vertica.com/24.2.x/en/sql-reference/statements/select/offset-clause/)
=> [CALCITE-6790] Write LIMIT for fetch operations in Vertica

core/src/main/java/org/apache/calcite/config/CalciteConnectionProperty.java
We've added several libraries, and the [java doc](https://calcite.apache.org/javadocAggregate/org/apache/calcite/config/CalciteConnectionProperty.html#FUN) needs to be updated.
=> Update javadoc for the fun connect string parameter

core/src/main/java/org/apache/calcite/sql/dialect/PrestoSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Since BINARY  type is not supported in Presto
According to the documentation:
https://prestodb.io/docs/current/language/types.html#varbinary
Using CAST(xxxx AS BINARY) will result in an error:
```
SELECT cast(task_id as binary)
from applydata_bigdata.xflink_task_info
where reader_info like '%mongodbreader%' or writer_info like '%mongodbwriter%';
```
It should be converted to the VARBINARY type instead.
=> [CALCITE-6796] Convert Type from BINARY to VARBINARY in PrestoDialect

core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcCorrelationDataContext.java, core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcCorrelationDataContextBuilder.java, core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcCorrelationDataContextBuilderImpl.java, core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcImplementor.java, core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcToEnumerableConverter.java, core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java, core/src/main/java/org/apache/calcite/runtime/ResultSetEnumerable.java, core/src/test/java/org/apache/calcite/test/JdbcAdapterTest.java
See [CALCITE-4188](https://issues.apache.org/jira/projects/CALCITE/issues/CALCITE-4188)
=> [CALCITE-4188] Implement BatchNestedLoopJoin for JDBC

core/src/test/java/org/apache/calcite/test/LintTest.java
https://issues.apache.org/jira/browse/CALCITE-6801
=> [CALCITE-6801] Linter should disallow tags such as 'Chore' in commit messages

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
Currently Spark Hive hex and unhex function not introduce for calcite, need to support it.
jira: https://issues.apache.org/jira/browse/CALCITE-6805
=> [CALCITE-6805] Support hex function for Hive and Spark Library

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
Enable some methods to hive which had already been implemented for other libraries.
issue: https://issues.apache.org/jira/browse/CALCITE-6800
supported functions as follow:
1. DATE_ADD
2. DATE_SUB
3. DECODE
4. LPAD
5. RPAD
6. LTRIM
7. RTRIM
8. SPACE
9. GREATEST
10.  LEAST
11. REGEXP_REPLACE_3
12. REPEAT
13. SOUNDEX
14. TO_DATE
15. MD5
16. SHA1
17. LOG_MYSQL
=> [CALCITE-6800] Enable a few existing functions to HIVE library

bom/build.gradle.kts, gradle.properties
Add version contraint ensuring that we are always using the 2.3 version for json-smart.
There is a transitive dependecy to json-smart from the piglet module with a version range [1.3.1,2.3]:
project :piglet > org.apache.hadoop:hadoop-common:2.10.2 > org.apache.hadoop:hadoop-auth:2.10.2 > com.nimbusds:nimbus-jose-jwt:7.9
The maven-metadata.xml of json-smart in Maven central [1] is used to resolve version ranges. After the 2.5.2 relase of json-smart [2] the previous versions were removed from the metadata file leading to failures in the resolution of ranged versions.
Using a version constraint by-passes the ranged version problem and improves build stability.
[1] https://repo.maven.apache.org/maven2/net/minidev/json-smart/maven-metadata.xml
[2] …
=> [CALCITE-6827] Build failure due to json-smart version mismatch

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java, core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java, core/src/main/java/org/apache/calcite/sql/SqlKind.java, core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java, core/src/main/java/org/apache/calcite/util/BuiltInMethod.java, site/_docs/reference.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
As descrption in JIRA: https://issues.apache.org/jira/browse/CALCITE-6831
=> [CALCITE-6831] Add ARRAY_SLICE function（enabled in Hive Library）

core/src/main/java/org/apache/calcite/sql/dialect/MssqlSqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/OracleSqlDialect.java, core/src/main/java/org/apache/calcite/util/RelToSqlConverterUtil.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
In MSSQL dialect use 1=1 instead of TRUE
=> [CALCITE-6819] MSSQL doesn't support TRUE/FALSE keywords in its Join predicate

mongodb/src/test/java/org/apache/calcite/adapter/mongodb/MongoAdapterTest.java
Currently MongoDB Adapter not have a test for join, this is nessary because other adapter may had bug in join such as elastic search( https://issues.apache.org/jira/browse/CALCITE-6274 )
=> Add JOIN test for MongoDB adapter

elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchRules.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/JoinTest.java
[CALCITE-6274](https://issues.apache.org/jira/browse/CALCITE-6274)
Two index of Elasticsearch join return empty result even if the data from both indexes can match。
create index test_01:
`
PUT /test_01/_doc/1
{
  "doc_id" : 1,
  "doc_desc" : "doc01"
} 
`
create index test_02:
`
PUT /test_02/_doc/1
{
  "doc_id" : 1,
  "doc_score" : 90
} 
`
execute sql:
`
select * from es.test_01 t1 join es.test_02 t2 on cast(t1._MAP['doc_id'] as bigint) = cast(t2._MAP['doc_id'] as bigint) 
`
the code generate by ElasticsearchToEnumerableConverter like this:
subquery of index test_01:
`
{
return ((org.apache.calcite.adapter.elasticsearch.ElasticsearchTable.ElasticsearchQueryable) org.apache.calcite.schema.Schemas.queryable(root, root.getRootSchema().getSubSchema("es"), java.lang.Object[].class, …
=> [CALCITE-6274] Two Elasticsearch index join return empty result

gradle.properties
- Increased JVM heap max memory to 2GB
As it has been pointed out in the PR where we last increased the JVM heap size (https://github.com/apache/calcite/pull/3864), this change will also affect the local JVM. 
Last time we decided that a 0.5GB increase was modest and not worth the trouble, but it's technically possible to limit the increase to just the sonar task in CI (I had it working at some point, most probably in this commit: https://github.com/apache/calcite/commit/88e7e27e13a1a0cd79c169c5021adc103800e776), so if there are objections to the proposed solutions I can try and make it work only for CI.
=> [CALCITE-6865] Sonar analysis fails due to OOM

core/src/main/java/org/apache/calcite/rel/rules/LoptOptimizeJoinRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
A backwards-compatible approach for CALCITE-6788
=> [CALCITE-6788] LoptOptimizeJoinRule should be able to delegate costs to the planner

druid/src/main/java/org/apache/calcite/adapter/druid/DruidQuery.java, druid/src/test/java/org/apache/calcite/test/DruidAdapterIT.java
As description in JIRA：https://issues.apache.org/jira/browse/CALCITE-6876
ut had test success in Druid docker test env.
=> [CALCITE-6876] Druid Adapter support more functions

.mailmap, NOTICE, README, site/_docs/history.md, site/_docs/howto.md
1. Add and curate release notes for 1.39.0
2. Update README and howto to refer to 1.39.0
3. Update .mailmap with coordinates of new contributors
4. Update copyright year in NOTICE to 2025
=> [CALCITE-6872] Release Calcite 1.39.0

core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java, core/src/main/java/org/apache/calcite/rel/rules/FilterSortTransposeRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
link: [[CALCITE-6878]](https://issues.apache.org/jira/projects/CALCITE/issues/CALCITE-6878)
=> [CALCITE-6878] Implement FilterSortTransposeRule

core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
Jira link: https://issues.apache.org/jira/browse/CALCITE-6897
=> [CALCITE-6897] AbstractConverter of root node is not needed in topdown mode

core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java, core/src/main/java/org/apache/calcite/rel/rules/IntersectToExistsRule.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
issue: https://issues.apache.org/jira/projects/CALCITE/issues/CALCITE-6836
=> [CALCITE-6836] Add Rule to convert INTERSECT to EXISTS

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java, core/src/main/java/org/apache/calcite/sql/fun/SqlQuantifyOperator.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
- Add support for `ALL`, `SOME`, `ANY` on subQuery like `IN`.
- Add overrite `not` in `SqlQuantifyOperator` to NOT SOME/ALL.
JIRA: https://issues.apache.org/jira/browse/CALCITE-6825
=> [CALCITE-6825] Add support for ALL, SOME, ANY in RelToSqlConverter

core/src/main/java/org/apache/calcite/sql/dialect/ClickHouseSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6909
=> [CALCITE-6909] ClickHouse dialect should limit the Precision and Scale of the Decimal type to be within 76

core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6931
=> [CALCITE-6931] STARTSWITH/ENDSWITH in SPARK should not convert to STARTS_WITH/ENDS_WITH

core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java, core/src/main/java/org/apache/calcite/rel/rules/MinusToAntiJoinRule.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Please see: [CALCITE-6948](https://issues.apache.org/jira/browse/CALCITE-6948)
=> [CALCITE-6948] Implement MinusToAntiJoinRule

core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java, core/src/main/java/org/apache/calcite/rel/rules/JoinConditionExpandIsNotDistinctFromRule.java, core/src/test/java/org/apache/calcite/test/JdbcTest.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
please see: [CALCITE-6927](https://issues.apache.org/jira/browse/CALCITE-6927)
=> [CALCITE-6927] Add rule for join condition remove IS NOT DISTINCT FROM

core/src/main/java/org/apache/calcite/sql/dialect/MysqlSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6958
=> [CALCITE-6958] JDBC adapter for MySQL not support floor date to MILLISECOND/MICROSECOND

core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java, core/src/main/java/org/apache/calcite/rel/rules/ExpandDisjunctionForTableRule.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
For the following SQL:
`
select t1.name from t1, t2 
where t1.id = t2.id 
and ( 
(t1.id > 20 and t2.height < 50)  
or 
(t1.weight < 200 and t2.sales > 100) 
) 
`
The disjunction `(t1.id > 20 and t2.height < 50) or (t1.weight < 200 and t2.sales > 100)` uses t1 and t2, thus cannot be pushed below the join. 
In fact, we can extract redundant `(t1.id > 20 or t1.weight < 200)` , `(t2.height < 50 or t2.sales > 100)` from this predicate by a new rule and push down these two predicates to both side of Join input.
More detail: https://issues.apache.org/jira/browse/CALCITE-6914
=> [CALCITE-6914] Expand join-dependent predicates from disjunction

core/src/main/java/org/apache/calcite/rel/rules/PruneEmptyRules.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml, core/src/test/resources/sql/set-op.iq
Please see: [CALCITE-6955](https://issues.apache.org/jira/browse/CALCITE-6955)
=> [CALCITE-6955] PruneEmptyRules does not handle the all attribute of SetOp correctly

core/src/main/java/org/apache/calcite/sql/SqlDelete.java, core/src/test/java/org/apache/calcite/sql/SqlCallOperandsTest.java
Please view the detail : [CALCITE-6964]
=> [CALCITE-6964] SqlDelete#getOperandList return operands' both order and size not match with SqlDelete#setOperand

core/src/main/java/org/apache/calcite/sql/dialect/ClickHouseSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6967
=> [CALCITE-6967] Unparsing STARTS_WITH/ENDS_WITH/BIT functions is incorrect for the Clickhouse dialect

core/src/main/java/org/apache/calcite/sql/dialect/MysqlSqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/PhoenixSqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/PrestoSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6974
=> [CALCITE-6974] Default typesystem has incorrect limits for DECIMAL for Presto/MySQL/Phoenix

core/src/main/java/org/apache/calcite/sql/fun/SqlJsonQueryFunction.java, core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
optional arguments does not reject mistyped expressions
=> [CALCITE-6984] FamilyOperandTypeChecker with a Predicate describing

core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java, core/src/main/java/org/apache/calcite/rel/rules/ExpandDisjunctionForJoinInputsRule.java, core/src/main/java/org/apache/calcite/rel/rules/ExpandDisjunctionForTableRule.java, core/src/main/java/org/apache/calcite/rex/RexUtil.java, core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java, core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml, core/src/test/resources/sql/planner.iq
Similar to Calcite-6914, we can expand redundant predicates from the disjunction and push them down. However, the predicates expanded by Calcite-6914 must belong to a single table, that is, if join_type does not restrict pushdown, the redundant predicates can be pushed directly on TableScan.
However, pushing predicates down to the inputs of Join is also very useful ([link](https://github.com/apache/calcite/pull/4267#discussion_r2021576009)), for example:
```
select t1.id from t1, t2, t3
where t1.id = t2.id
and t1.id = t3.id
and (
(t1.age < 50 and t3.age > 20)
or
(t2.weight > 70 and t3.height < 180)
) 
```
Because `(t1.age < 50 and t3.age > 20)` or `(t2.weight > 70 and t3.height < 180)` a is a disjunction and involves multiple tables, it cannot be pushed down.
However, we can expand it to …
=> [Calcite-6946] Expand predicates from disjunction for inputs of Join

core/src/main/java/org/apache/calcite/sql/SqlDelete.java, testkit/src/main/java/org/apache/calcite/sql/parser/SqlParserTest.java
The details please see [CALCITE-6977](https://issues.apache.org/jira/browse/CALCITE-6977)
=> [CALCITE-6977] Unparse DELETE SQL throws unsupported exception

core/src/main/java/org/apache/calcite/plan/visualizer/RuleMatchVisualizer.java
The Charset constants in Guava's Charsets are deprecated in favor of StandardCharsets.
=> Use StandardCharsets in RuleMatchVisualizer.java

core/src/main/java/org/apache/calcite/sql/fun/SqlCaseOperator.java, core/src/main/java/org/apache/calcite/sql/fun/SqlCoalesceFunction.java, core/src/main/java/org/apache/calcite/sql/validate/implicit/TypeCoercion.java, core/src/main/java/org/apache/calcite/sql/validate/implicit/TypeCoercionImpl.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
details info see [CALCITE-6991](https://issues.apache.org/jira/browse/CALCITE-6991)
=> [CALCITE-6991] Validator cannot infer type for COALESCE when call is not expanded

core/src/main/java/org/apache/calcite/jdbc/Driver.java, core/src/main/java/org/apache/calcite/model/ModelHandler.java, core/src/test/java/org/apache/calcite/model/ModelHandlerTest.java, core/src/test/resources/hsqldb-scott.json
ModelHandler is mainly a parser that can transform YAML/JSON files into SchemaPlus objects.
Currently, the class requires a CalciteConnection in order to be instantiated and the latter is a pretty heavyweight object. The usage of the CalciteConnection makes it rather cumbersome to instantiate and use the parsing capabilities of the ModelHander independently.
In reality though, the handler does not need much from the CalciteConnection and we could easily refactor the handler to not depend on the connection at all.
The motivation for this change is to facilitate the creation of schema objects from YAML/JSON files.
=> [CALCITE-7022] Decouple ModelHandler from CalciteConnection

core/src/main/java/org/apache/calcite/prepare/CalcitePrepareImpl.java, core/src/test/java/org/apache/calcite/test/ReflectiveSchemaTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-7014
=> [CALCITE-7014] Support EQUAL/GreaterThanOrEqual/LessThanOrEqual expressions to RexNode in CalcitePrepare

core/src/main/java/org/apache/calcite/plan/RelOptUtil.java, core/src/main/java/org/apache/calcite/rel/rules/SubQueryRemoveRule.java, core/src/main/java/org/apache/calcite/sql2rel/RelFieldTrimmer.java, core/src/test/java/org/apache/calcite/test/enumerable/EnumerableCorrelateTest.java, core/src/test/resources/sql/sub-query.iq
LogicalJoin can contain sub-query which correlated inputs are not considered in further LogicalJoin fields trimming
subquery: $SCALAR_QUERY with correlate
```
LogicalProject(DEPTNO=[$1])
LogicalFilter(condition=[=(CAST($0):CHAR(11) NOT NULL, $cor0.DNAME)])
```
```
---------------------------LogicalJoin ----------------------
V                                                            V  
left                                                         right
|                                                            |
LogicalProject.NONE.[0, 1]                                             LogicalValues.NONE.[0]
RecordType(INTEGER DEPTNO, CHAR(11) DNAME)                             RecordType(INTEGER DEPTNO)
```
In such a case  $cor0.DNAME - has not been considered which leads to mention …
=> CALCITE-5638 Assertion Failure during planning correlated query with orderby

core/src/main/java/org/apache/calcite/sql/SqlUtil.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
~~This is a sort of poc for the jira issue.~~
~~I can add similar to other places of `Util#needToImplement` usage if the approach is ok~~
UPD: it looks the reason of failures we faced is unsupported UNION, INTERSECT, EXCEPT, MINUS in SqlUtil#getSelectListItem
added support for this and changes in this file reverted
=> [CALCITE-7027] Improve error message in case of several `UNION`, `INTERSECT`, `EXCEPT` in a query

core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java, core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml, core/src/test/resources/sql/scalar.iq
https://issues.apache.org/jira/browse/CALCITE-7009
This patch addresses an issue when AssertionError is thrown if multiple correlated subqueries reference different tables in FROM list. Proposed solution is to simply remove assertion check. See attached JIRA for details.
=> [CALCITE-7009] AssertionError when converting query containing multiple correlated subqueries referencing different tables in FROM

core/src/test/resources/sql/scalar.iq
@korlov42 I am disabling the test you have introduced recently, since it fails after being rebased.
I have filed https://issues.apache.org/jira/browse/CALCITE-7064 to track this.
=> Disable test introduced in #4378 [CALCITE-7009] which breaks main

babel/src/test/java/org/apache/calcite/test/BabelQuidemTest.java, core/src/test/java/org/apache/calcite/test/CoreQuidemTest.java, core/src/test/resources/sql/misc.iq, testkit/src/main/java/org/apache/calcite/test/QuidemTest.java
This just moves a class around so the command !explain... is available both in CoreQuidemTests and in BabelQuidemTests (where the command was originally added).
=> [CALCITE-7060] Enable dumping high-level plans in quidem tests

core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java, core/src/main/java/org/apache/calcite/sql/SqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/PostgresqlSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Jira: [CALCITE-5583](https://issues.apache.org/jira/browse/CALCITE-5583)
=> [CALCITE-5583] JDBC adapter does not generate 'SELECT *' when duplicate field names

core/src/main/java/org/apache/calcite/materialize/MaterializationService.java
Our current logic using a PriorityQueue to select the tile with the fewest rows when multiple tiles are available. However, there are several potential issues:
1. The PriorityQueue stores all satisfiable tiles. When the number of tiles is large, maintaining the heap structure during element insertion has a time complexity of O(log n), which also increases memory usage.
2. The initial size of the PriorityQueue is difficult to estimate and is currently set to 1, causing frequent resizing of the PriorityQueue.
We can optimize the code by keeping only a single bestCandidate tile to improve performance.
=> [CALCITE-6763] Optimize logic to select the tiles with the fewest rows

elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchSchemaFactory.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/ElasticSearchAdapterTest.java
jira: https://issues.apache.org/jira/browse/CALCITE-6386
I had reviewed origin PR(https://github.com/apache/calcite/pull/3775)  which maybe not right way to fix and staled for more than one year. so I open a new pr to fix it.
=> [CALCITE-6386] Elasticsearch adapter throws NullPointerException when used with with model.json and no username, password or pathPrefix

elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchJson.java, elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchJsonTest.java
jira: https://issues.apache.org/jira/browse/CALCITE-3190
The issue is staled for several years，and I reviewed previous PR which fix way is not suitable，so I continue to fix it in this pr.
=> [CALCITE-3190] ElasticsearchJson throws Exception when visitMappingProperties

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Turns out the fix is pretty straightforward: Use `SqlImplementor.BaseContext` instead of `SqlImplementor.Context` in `SqlImplementor.Result.builder()`.
=> [CALCITE-7112] Correlation variable in HAVING clause causes UnsupportedOperationException in RelToSql conversion

core/src/main/java/org/apache/calcite/sql/validate/implicit/TypeCoercionImpl.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java, core/src/test/java/org/apache/calcite/test/TypeCoercionConverterTest.java, core/src/test/resources/org/apache/calcite/test/TypeCoercionConverterTest.xml
The fix is to consider only 0 as FALSE, and everything else as TRUE in type coercion.
=> [CALCITE-7147] Comparison of INTEGER and BOOLEAN produces strange results

core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java, core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java, core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
See https://issues.apache.org/jira/browse/CALCITE-7135
Basically after creating the RelRoot of the subquery, we must not use `relRoot.rel`, but rather `relRoot.project()` which adds a Project on top if it is necessary to remove some fields (e.g. the ORDER BY field that is not part of the final projection of the subquery).
=> [CALCITE-7135] SqlToRelConverter throws AssertionError on ARRAY subquery order by a field that is not present on the final projection

core/src/main/java/org/apache/calcite/rel/metadata/RelMdMaxRowCount.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMdMinRowCount.java, core/src/main/java/org/apache/calcite/rel/metadata/RelMdRowCount.java, core/src/main/java/org/apache/calcite/rex/RexLiteral.java, core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
See: [CALCITE-7154](https://issues.apache.org/jira/browse/CALCITE-7154)
=> [CALCITE-7154] When the offset or limit of a SORT operation is of type BIGINT row count calculation overflows

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java, core/src/main/java/org/apache/calcite/sql/SqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/PostgresqlSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
See: [CALCITE-7157](https://issues.apache.org/jira/browse/CALCITE-7157)
=> [CALCITE-7157] PostgreSQL does not support string literal in ORDER BY clause

core/src/main/java/org/apache/calcite/sql/dialect/DorisSqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/MysqlSqlDialect.java, core/src/main/java/org/apache/calcite/sql/dialect/StarRocksSqlDialect.java, core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
JIRA：https://issues.apache.org/jira/projects/CALCITE/issues/CALCITE-7069
=> [CALCITE-7069] Invalid unparse for INT UNSIGNED and BIGINT UNSIGNED in MysqlSqlDialect

core/src/main/java/org/apache/calcite/sql/type/FunctionSqlType.java, core/src/test/java/org/apache/calcite/sql/type/FunctionSqlTypeTest.java
`FunctionSqlType` misses a getter for `parameterType`. This PR adds it.
=> [CALCITE-7141] Add missing getter to FunctionSqlType

core/src/main/java/org/apache/calcite/sql/type/SqlTypeUtil.java, core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
The fix is to actually to allow the NULL type (only the NULL literal can have this type) to be compared to any other type. The previous implementation excluded ARRAY, ROW, and MAP types.
=> [CALCITE-7195] COALESCE type inference rejects legal arguments

babel/src/test/resources/sql/redshift.iq, core/src/main/java/org/apache/calcite/sql/validate/SqlConformance.java, core/src/main/java/org/apache/calcite/sql2rel/StandardConvertletTable.java, site/community/index.md, testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
I added a second commit adding my last blog post to the documentation, since it was approved by the reviewers.
=> [CALCITE-7210] BINARY literal values may not match their type
