- cassandra/src/test/java/org/apache/calcite/test/CassandraAdapterTest.java
- core/src/main/java/org/apache/calcite/util/Sources.java
- core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
- core/src/test/java/org/apache/calcite/test/CalciteAssert.java
- core/src/test/java/org/apache/calcite/test/DiffRepository.java
- core/src/test/java/org/apache/calcite/test/QuidemTest.java
- core/src/test/java/org/apache/calcite/util/SourceTest.java
- druid/src/test/java/org/apache/calcite/test/DruidAdapterIT.java
- druid/src/test/java/org/apache/calcite/test/DruidAdapterIT2.java
- example/csv/src/test/java/org/apache/calcite/test/CsvTest.java
- file/src/main/java/org/apache/calcite/adapter/file/FileReader.java
- file/src/test/java/org/apache/calcite/adapter/file/FileReaderTest.java
- geode/src/test/java/org/apache/calcite/adapter/geode/rel/BaseGeodeAdapterIT.java
- geode/src/test/java/org/apache/calcite/adapter/geode/rel/GeodeAdapterBookshopIT.java
- geode/src/test/java/org/apache/calcite/adapter/geode/rel/GeodeZipsIT.java
- pig/src/test/java/org/apache/calcite/test/AbstractPigTest.java
- pig/src/test/java/org/apache/calcite/test/PigAdapterTest.java
- plus/src/test/java/org/apache/calcite/adapter/os/OsAdapterTest.java
- src/main/config/forbidden-apis/signatures.txt
https://issues.apache.org/jira/browse/CALCITE-2495
> [CALCITE-2495] Rework URL->File conversion in tests

- core/src/main/java/org/apache/calcite/jdbc/CalciteConnectionImpl.java
- core/src/main/java/org/apache/calcite/sql/advise/SqlAdvisor.java
- core/src/main/java/org/apache/calcite/sql/advise/SqlAdvisorGetHintsFunction2.java
- core/src/main/java/org/apache/calcite/sql/advise/SqlAdvisorHint2.java
- core/src/main/java/org/apache/calcite/sql/advise/SqlSimpleParser.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
- core/src/main/java/org/apache/calcite/util/Util.java
- core/src/test/java/org/apache/calcite/sql/test/SqlAdvisorTest.java
- core/src/test/java/org/apache/calcite/sql/test/SqlTestFactory.java
- core/src/test/java/org/apache/calcite/test/CalciteSuite.java
- core/src/test/java/org/apache/calcite/test/JdbcTest.java
- core/src/test/java/org/apache/calcite/test/SqlAdvisorJdbcTest.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorTestCase.java
- core/src/test/java/org/apache/calcite/test/WithLex.java
https://issues.apache.org/jira/browse/CALCITE-2433,
https://issues.apache.org/jira/browse/CALCITE-2434,
https://issues.apache.org/jira/browse/CALCITE-2473,
https://issues.apache.org/jira/browse/CALCITE-2474,
https://issues.apache.org/jira/browse/CALCITE-2475,
https://issues.apache.org/jira/browse/CALCITE-2476,
https://issues.apache.org/jira/browse/CALCITE-2477,
https://issues.apache.org/jira/browse/CALCITE-2478,
https://issues.apache.org/jira/browse/CALCITE-2479
There's relevant https://issues.apache.org/jira/browse/CALCITE-2439, however it is not included here.
> [CALCITE-2433] [CALCITE-2434]...[CALCITE-2479] SqlAdvisor: better quoting support, advice for nested identifiers

- core/src/test/java/org/apache/calcite/test/CalciteSuite.java
- core/src/test/java/org/apache/calcite/test/fuzzer/RexFuzzer.java
- core/src/test/java/org/apache/calcite/test/fuzzer/RexProgramFuzzyTest.java
- core/src/test/java/org/apache/calcite/test/fuzzer/RexToTestCodeShuttle.java
- core/src/test/java/org/apache/calcite/test/fuzzer/SimplifyTask.java
https://issues.apache.org/jira/browse/CALCITE-2504
Note: seed=43 and rex.fuzzing.iterations=5 enables for the test to succeed
Entry point is https://github.com/apache/calcite/pull/830/files#diff-ffa17851d5a9882f0391445f2fc04468R216
> [CALCITE-2504] Add randomized test for better code coverage of rex node create and simplification

- core/src/main/java/org/apache/calcite/rex/RexSimplify.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/java/org/apache/calcite/test/RexProgramTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
- core/src/test/resources/sql/misc.iq
- core/src/test/resources/sql/sub-query.iq
https://issues.apache.org/jira/browse/CALCITE-2590
> [CALCITE-2590] Remove redundant CAST when operand has exactly the same type as it is casted to

- core/pom.xml
- core/src/test/java/org/apache/calcite/test/CalciteSuite.java
- core/src/test/kotlin/org/apache/calcite/TestKtTest.kt
- pom.xml
This implements https://issues.apache.org/jira/browse/CALCITE-2458
> [CALCITE-2458] Add Kotlin as a test dependency

- core/src/test/java/org/apache/calcite/test/CalciteAssert.java
Make sure top-most exception is AssertionError, so test failures are simpler to understand.
For instance:
```
java.lang.AssertionError:
Expected: a string containing "EnumerableTableScan(tab le=[[hr, m0]])"
but: was "PLAN=EnumerableCalc(expr#0..4=[{inputs}], expr#5=[1], expr#6=[+($t0, $t5)], EXPR$0=[$t6])\n  EnumerableTableScan(table=[[hr, m0]])\n\n"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at org.apache.calcite.test.CalciteAssert.lambda$checkResultContains$7(CalciteAssert.java:437)
at org.apache.calcite.test.CalciteAssert.assertQuery(CalciteAssert.java:556)
at org.apache.calcite.test.CalciteAssert$AssertQuery.returns(CalciteAssert.java:1454)
at …
```
> Improve assert messages for CalciteAssert-based tests

- elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchProject.java
- elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/ElasticSearchAdapterTest.java
Fix handling of `select *` in projections.
Example of failing query:
```sql
select * from elastic where _MAP['state'] = 'NY' order by _MAP['city']
```
> [CALCITE-2863] ElasticSearch Adapter. select * and predicates on _MAP fail

- core/src/main/codegen/templates/Parser.jj
- core/src/main/java/org/apache/calcite/runtime/CalciteResource.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlJsonArrayAggAggFunction.java
- core/src/main/resources/org/apache/calcite/runtime/CalciteResource.properties
- core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
- core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
- core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
- core/src/test/resources/sql/agg.iq
- site/_docs/reference.md
The JIRA issue:
https://issues.apache.org/jira/browse/CALCITE-2786
> [CALCITE-2786] Add order by clause support for JSON_ARRAYAGG

- core/src/main/java/org/apache/calcite/sql/fun/SqlBaseContextVariable.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
- core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
Change-Id: I32d931ce22d430d466ddcd8fff6f944eee7cdfc1
> [CALCITE-2750] PI operator incorrectly identified as dynamic function

- core/src/main/java/org/apache/calcite/rex/RexSimplify.java
- core/src/test/java/org/apache/calcite/test/RexProgramTest.java
This change enables to rewrite comparisions between the same operands to a form which relys on the nullability check of the original expression.
For example `x=x` is rewritten to `null or x is not null`
> [CALCITE-2421] Generalize simplification of self-comparisions

- core/src/main/java/org/apache/calcite/adapter/enumerable/BasicAggregateLambdaFactory.java
- core/src/main/java/org/apache/calcite/adapter/enumerable/BasicLazyAccumulator.java
- core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableAggregate.java
- core/src/main/java/org/apache/calcite/adapter/enumerable/LazyAggregateLambdaFactory.java
- core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
- core/src/test/resources/sql/agg.iq
JIRA: https://issues.apache.org/jira/browse/CALCITE-2785
> [CALCITE-2785] In EnumerableAggregate, wrong result produced If there are sorted aggregates and non-sorted aggregates at the same time

- core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
- core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
- core/src/test/resources/sql/misc.iq
JIRA: https://issues.apache.org/jira/browse/CALCITE-2818
> [CALCITE-2818] EXTRACT returns wrong results for DATE and TIMESTAMP values before epoch

- linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
The implementation of semiJoin in EnumerableDefaults.java is based on two elements: an outer enumerator and an inner lookup. The method "returns elements of outer for which there is a member of inner with a matching key". 
In order to achieve that, the innerLookup is always eagerly computed, even though in some cases it might be not necessary at all: when the outer enumerator returns no element there is no need for the innerLookup. In a worst case scenario, a time-consuming innerLookup computation combined with an empty outer enumerator will lead to an inefficient execution, which could have been easily avoided.
In order to improve that, it is proposed to delay the computation of the innerLookup until the moment when we are sure that it will be really needed, i.e. when the first outer …
> [CALCITE-2909] Optimize Enumerable SemiJoin with lazy computation of innerLookup (Ruben Quesada Lopez)

- core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
- core/src/main/java/org/apache/calcite/rel/rules/AggregateMergeRule.java
- core/src/main/java/org/apache/calcite/sql/SqlSplittableAggFunction.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
JIRA: https://issues.apache.org/jira/browse/CALCITE-1172
> [CALCITE-1172] Add rule to flatten two Aggregate operators into one

- site/_docs/index.md
JIRA: https://issues.apache.org/jira/browse/CALCITE-3006
> [CALCITE-3006] Example code on site cannot compile

- elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchProject.java
- elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/Projection2Test.java
Simple query like below is using `script` when `_source` is sufficient.
```sql
select  _MAP['a'], _MAP['b.a'] from elastic
```
> [CALCITE-3054] Elasticsearch adapter. Avoid scripting for simple projections

- mongodb/src/test/java/org/apache/calcite/adapter/mongodb/MongoAdapterTest.java
`BsonDocument.parse()` is more lenient with input and this omission was not noticed before
> Mongo adapter. Mongo checker validates only first line of the Bson query in tests

- core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
- core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
- core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
JIRA: https://issues.apache.org/jira/browse/CALCITE-2936
> [CALCITE-2936] Simplify EXISTS or NOT EXISTS sub-query that has "GROUP BY ()"

- core/src/main/java/org/apache/calcite/plan/RelOptUtil.java
- core/src/main/java/org/apache/calcite/rel/rules/AggregateJoinJoinRemoveRule.java
- core/src/main/java/org/apache/calcite/rel/rules/AggregateJoinRemoveRule.java
- core/src/main/java/org/apache/calcite/rel/rules/AggregateProjectMergeRule.java
- core/src/main/java/org/apache/calcite/rel/rules/ProjectJoinJoinRemoveRule.java
- core/src/main/java/org/apache/calcite/rel/rules/ProjectJoinRemoveRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
JIRA: https://issues.apache.org/jira/browse/CALCITE-2712
> [CALCITE-2712] Add rule to remove unnecessary outer join

- core/src/main/java/org/apache/calcite/plan/hep/HepProgram.java
- core/src/main/java/org/apache/calcite/plan/hep/HepProgramBuilder.java
- core/src/test/java/org/apache/calcite/test/HepPlannerTest.java
- core/src/test/resources/org/apache/calcite/test/HepPlannerTest.xml
JIRA: https://issues.apache.org/jira/browse/CALCITE-3068
> [CALCITE-3068] testSubprogram() does not test whether subprogram gets re-executed

- core/src/test/java/org/apache/calcite/plan/RelOptUtilTest.java
RelOptUtilTest was creating a static RelOptCluster which could be used
during tests running in parallel to acces the associated RelMetadataQuery
instance.  Alas the object is not safe to access from multiple threads
and in some occasions tests would fail with CyclicMetadataException.
Fixing the test class by creating a new RelOptCluster/RelBuilder
instance for each test, and removing the static instances.
> RelOptUtilTest concurrency fixup

- core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableRules.java
- core/src/main/java/org/apache/calcite/config/CalciteSystemProperty.java
- core/src/main/java/org/apache/calcite/plan/RelOptRules.java
- core/src/main/java/org/apache/calcite/plan/RelOptUtil.java
- core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
- core/src/main/java/org/apache/calcite/prepare/CalcitePrepareImpl.java
- core/src/main/java/org/apache/calcite/prepare/RelOptTableImpl.java
- core/src/main/java/org/apache/calcite/tools/Programs.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-3095
> [CALCITE-3095] Add several system properties to control enabling/disabling of rules and traits

- core/src/main/java/org/apache/calcite/util/Bug.java
- core/src/test/java/org/apache/calcite/test/JdbcTest.java
- core/src/test/java/org/apache/calcite/test/QuidemTest.java
- core/src/test/resources/sql/struct.iq
- pom.xml
Remove bug for CALCITE-2776 which was fixed in Avatica 1.15.
Remove bug for CALCITE-2993 which is fixed in Calcite but forgotten.
> [CALCITE-3116] Upgrade to Avatica 1.15

- mongodb/pom.xml
- mongodb/src/test/java/org/apache/calcite/adapter/mongodb/MongoAdapterTest.java
- mongodb/src/test/java/org/apache/calcite/adapter/mongodb/MongoDatabasePolicy.java
- mongodb/src/test/java/org/apache/calcite/test/MongoAssertions.java
- pom.xml
Mongo java server is a better alternative to fongo. All tests (including IT) are passing.
> [CALCITE-3156] Mongo adapter. Replace fongo with Mongo Java Server for tests

- core/src/main/java/org/apache/calcite/rel/type/RelDataTypeFactoryImpl.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-3149
> [CALCITE-3149] RelDataType CACHE in RelDataTypeFactoryImpl can't be garbage collected

- core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
This patch also merge the redundant sql statements with
`SqlParserTest.Sql#sansCarets`.
> [CALCITE-3168] Add test for invalid literal of sql parser

- core/src/main/java/org/apache/calcite/sql2rel/RelDecorrelator.java
decorrelateRel method should return when meeting SEMI/ANTI join in RelDecorrelator
> [CALCITE-3169] decorrelateRel method should return when meeting SEMI/ANTI join in RelDecorrelator

- core/src/main/java/org/apache/calcite/rel/rules/SubQueryRemoveRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
- core/src/test/resources/sql/sub-query.iq
https://issues.apache.org/jira/browse/CALCITE-3031
> [CALCITE-3031] Support for correlated ANY/SOME/ALL sub-query

- core/src/main/codegen/templates/Parser.jj
- core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
- core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-2496.
> [CALCITE-2496] Return 0 in case of extract(milli/micro/nanosecond from Date)

- core/src/main/java/org/apache/calcite/rel/rules/JoinToMultiJoinRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
JoinToMultiJoinRule should not match SEMI/ANTI LogicalJoin
> [CALCITE-3225] JoinToMultiJoinRule should not match SEMI/ANTI LogicalJoin

- core/src/main/java/org/apache/calcite/rel/rules/SortJoinCopyRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Jira: https://issues.apache.org/jira/browse/CALCITE-2624
> [CALCITE-2624] Add a rule to copy a sort below a join operator

- core/src/main/java/org/apache/calcite/plan/RelOptUtil.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
JIRA: https://issues.apache.org/jira/browse/CALCITE-3101
> [CALCITE-3101] Don't push non-equi join conditions into Project below Join

- site/_docs/geode_adapter.md
JIRA: https://issues.apache.org/jira/browse/CALCITE-2835
> [CALCITE-2835] Markdown errors on the Geode adapter page

- core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
- core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
- core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
JIRA: https://issues.apache.org/jira/projects/CALCITE/issues/CALCITE-3229
> [CALCITE-3229] UnsupportedOperationException for UPDATE with IN query

- core/src/main/java/org/apache/calcite/interpreter/Bindables.java
- core/src/main/java/org/apache/calcite/rel/core/Project.java
- core/src/main/java/org/apache/calcite/rel/rules/ProjectTableScanRule.java
- core/src/test/java/org/apache/calcite/test/RelBuilderTest.java
- core/src/test/java/org/apache/calcite/tools/FrameworksTest.java
JIRA: https://issues.apache.org/jira/projects/CALCITE/issues/CALCITE-3228
> [CALCITE-3228] Error while applying rule ProjectScanRule: interpreter

- elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchSchemaFactory.java
… i.e. to allow connecting on HTTPS
> [CALCITE-3335] ElasticSearch adapter. Introduce configuration parameter "hosts"

- core/src/main/java/org/apache/calcite/rel/metadata/RelMdDistribution.java
- core/src/main/java/org/apache/calcite/rex/RexProgram.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
When using `EnumerableCalcRule` with `RelDistributionTraitDef` for planner, got AssertionError.
Please refer to [CALCITE-3348](https://issues.apache.org/jira/browse/CALCITE-3348) for details.
This PR tries to implement the logic of determining distribution for Calc.
> [CALCITE-3348] AssertionError while determining distribution of Calc

- core/src/main/java/org/apache/calcite/rel/core/Calc.java
- core/src/test/java/org/apache/calcite/test/RexShuttleTest.java
In current code, `Calc#accept(RexShuttle shuttle)` keep the original `rowType`, even when the expression list is modified by the shuttle. https://github.com/apache/calcite/blob/master/core/src/main/java/org/apache/calcite/rel/core/Calc.java#L175 
It might be wrong and a new `rowType` should be derived.
> [CALCITE-3239] Calc#accept(RexShuttle shuttle) does not update rowType

- core/src/test/java/org/apache/calcite/tools/PlannerTest.java
Jira ticket with description: [CALCITE-3376](https://issues.apache.org/jira/browse/CALCITE-3376).
Problem actually solved via [CALCITE-2018](https://issues.apache.org/jira/browse/CALCITE-2018), just add a unit test for this specific scenario.
> [CALCITE-3376] VolcanoPlanner CannotPlanException: best rel is null even though there is an option with non-infinite cost

- core/src/main/java/org/apache/calcite/rel/externalize/RelJson.java
- core/src/test/java/org/apache/calcite/plan/RelWriterTest.java
Throws exception in two cases:
1. interval type
2. empty partition key or order key for RexOver.
Please refer to [CALCITE-3254](https://issues.apache.org/jira/browse/CALCITE-3254) for the full stack trace.
Changes in this PR:
add check for INTERVAL_TYPES
add check for the empty case of partition key or order key when deserialize RexOver
> [CALCITE-3254] Exception while deserializing of interval type or with empty partition/order key for RexOver

- site/_docs/algebra.md
remove redundant brackets which make the hyperlink failed in algebra.md
> [hotfix][docs] remove redundant brackets

- core/src/main/java/org/apache/calcite/config/CalciteSystemProperty.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-3521
> [CALCITE-3521] CalciteSystemProperty failed to load config file

- core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableNestedLoopJoin.java
- core/src/test/java/org/apache/calcite/runtime/EnumerablesTest.java
- linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Jira ticket: https://issues.apache.org/jira/browse/CALCITE-3539
> [CALCITE-3539] EnumerableDefaults#nestedLoopJoin returns duplicates for JoinType.SEMI

- core/src/main/java/org/apache/calcite/rex/RexSimplify.java
- core/src/test/java/org/apache/calcite/test/RexProgramTest.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-3544.
> [CALCITE-3544] RexSimplify does not exploit all known predicates

- core/src/main/java/org/apache/calcite/sql/fun/SqlCaseOperator.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-3355
> [CALCITE-3355] Deduce whether CASE and COALESCE may produce NULL values

- core/src/main/java/org/apache/calcite/rel/rules/AbstractMaterializedViewRule.java
- core/src/test/java/org/apache/calcite/test/MaterializationTest.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-3569.
> [CALCITE-3569] IndexOutOfBoundsException when pushing simplified filter to view

- core/src/main/java/org/apache/calcite/rel/logical/ToLogicalConverter.java
- core/src/test/java/org/apache/calcite/rel/logical/ToLogicalConverterTest.java
this pr try to support EnumerableIntersect and EnumerableMinus convert to Logical.
> [CALCITE-3566] Support EnumerableIntersect and EnumerableMinus convert to Logical

- core/src/main/java/org/apache/calcite/interpreter/Nodes.java
- core/src/main/java/org/apache/calcite/interpreter/UncollectNode.java
- core/src/test/java/org/apache/calcite/test/InterpreterTest.java
Jira: [CALCITE-3561](https://issues.apache.org/jira/browse/CALCITE-3561)
This PR tries to add support for using unnest in `Interpreter`.
> [CALCITE-3561] Support using unnest in Interpreter

- linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Jira ticket: [CALCITE-3546](https://issues.apache.org/jira/browse/CALCITE-3546)
The current implementation of `EnumerableDefaults#nestedLoopJoin` builds the complete join result in a list before returning it. As specified in a comment there, this is "easy, but hogs memory". Also, it is not very efficient if after the join there is a LIMIT.
An alternative implementation of nested loop join can be proposed, based on iterating through the outer an inner enumerables, and returning the results step by step (something similar to `EnumerableDefaults#correlateJoin`).
> [CALCITE-3546] Improve EnumerableDefaults nested loop join

- core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
- core/src/main/java/org/apache/calcite/sql/dialect/MssqlSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Hive and Sql Server dialect support with cube and with rollup.
it should be true in HiveSqlDialect and MssqlDialect.
> [CALCITE-3496] Hive dialect and MS SQL dialect support with cube and with rollup

- core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
- core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
- core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
JIRA: https://issues.apache.org/jira/browse/CALCITE-3575.
> [CALCITE-3575] IndexOutOfBoundsException when converting sql to rel

- .gitignore
* Add .DS_Store into .gitignore
> [CALCITE-3602] Git should ignore .DS_Store files on macOS

- core/src/main/java/org/apache/calcite/rel/rules/FilterJoinRule.java
- core/src/test/java/org/apache/calcite/test/JdbcFrontJdbcBackLinqMiddleTest.java
- core/src/test/java/org/apache/calcite/test/MaterializationTest.java
- core/src/test/resources/sql/misc.iq
JIRA: https://issues.apache.org/jira/browse/CALCITE-3576
> [CALCITE-3576] Remove enumerable convention check in FilterIntoJoinRule

- core/src/main/java/org/apache/calcite/sql/advise/SqlAdvisorValidator.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
- core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
- core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
JIRA: https://issues.apache.org/jira/browse/CALCITE-3387.
> [CALCITE-3387] Query with GROUP BY and JOIN ... USING wrongly fails with "Column DEPTNO is ambiguous" error

- core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java
- core/src/main/java/org/apache/calcite/sql/type/SqlTypeUtil.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
- core/src/main/java/org/apache/calcite/sql/validate/implicit/AbstractTypeCoercion.java
- core/src/main/java/org/apache/calcite/sql/validate/implicit/TypeCoercion.java
- core/src/main/java/org/apache/calcite/sql/validate/implicit/TypeCoercionImpl.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
- core/src/test/java/org/apache/calcite/test/JdbcAdapterTest.java
- core/src/test/java/org/apache/calcite/test/JdbcTest.java
- core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
- core/src/test/java/org/apache/calcite/test/TypeCoercionConverterTest.java
- core/src/test/java/org/apache/calcite/test/TypeCoercionTest.java
- core/src/test/java/org/apache/calcite/tools/PlannerTest.java
- core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
- core/src/test/resources/org/apache/calcite/test/TypeCoercionConverterTest.xml
* Add implicit type coercion to insert and update validaiton
* Change the plan according to the change
* Remove useless methods in AbstractTypeCoercion
> [CALCITE-3672] Support implicit type coercion for insert and update

- core/src/main/java/org/apache/calcite/rel/core/Correlate.java
See https://issues.apache.org/jira/browse/CALCITE-3711
> [CALCITE-3711] Correlate should override estimateRowCount

- core/src/main/java/org/apache/calcite/rex/RexBuilder.java
- core/src/main/java/org/apache/calcite/runtime/CalciteResource.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlAbstractConformance.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlConformance.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlConformanceEnum.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
- core/src/main/resources/org/apache/calcite/runtime/CalciteResource.properties
- core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-2672
> [CALCITE-2672] Qualifying the common column should not be allowed in Oracle dialect

- core/build.gradle.kts
- core/src/main/java/org/apache/calcite/rex/RexSimplify.java
- core/src/main/java/org/apache/calcite/rex/RexUtil.java
- core/src/test/java/org/apache/calcite/rex/RexLosslessCastTest.java
- core/src/test/java/org/apache/calcite/rex/RexProgramBuilderBase.java
- core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
- core/src/test/java/org/apache/calcite/rex/RexProgramTestBase.java
- core/src/test/java/org/apache/calcite/test/fuzzer/RexFuzzer.java
- core/src/test/java/org/apache/calcite/test/fuzzer/RexProgramFuzzyTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Just in case, this PR splits `RexProgramTest.java` into `RexProgramTest` and `RexProgramTestBase` so new `Rex`-related tests can be added to separate files like the added `RexLosslessCastTest`
> [CALCITE-3712] Optimize lossless casts in RexSimplify: CAST(CAST(intExpr as BIGINT) as INT) => intExpr

- core/build.gradle.kts
- core/src/main/java/org/apache/calcite/plan/RelOptTable.java
- core/src/main/java/org/apache/calcite/plan/ViewExpanders.java
- core/src/main/java/org/apache/calcite/rel/hint/HintOptionChecker.java
- core/src/main/java/org/apache/calcite/rel/hint/HintStrategyTable.java
- core/src/main/java/org/apache/calcite/rel/hint/package-info.java
- core/src/main/java/org/apache/calcite/sql/SqlUtil.java
- core/src/test/java/org/apache/calcite/test/SqlHintsConverterTest.java
validation
* Add interface HintOptionChecker to let user validate each hint's
options
* Add customizable hint error handler
> [CALCITE-3719] Add hint option checker to customize the option

- core/src/main/java/org/apache/calcite/plan/volcano/RuleQueue.java
ChunkList seems to be not required there, so we could use ArrayList for slightly better performance.
I don't expect huge gains here, but let's try it.
> Use ArrayList for RuleQueue#list

- core/src/main/java/org/apache/calcite/rel/logical/ToLogicalConverter.java
- core/src/test/java/org/apache/calcite/rel/logical/ToLogicalConverterTest.java
Support TableModify convert to Logical in ToLogicalConverter
> [CALCITE-3653] Support TableModify in ToLogicalConverter

- gradle/wrapper/gradle-wrapper.properties
See https://docs.gradle.org/6.1.1/release-notes.html#fixed-issues
> Update Gradle: 6.1 -> 6.1.1

- core/src/main/java/org/apache/calcite/rel/hint/CompositeHintStrategy.java
- core/src/main/java/org/apache/calcite/rel/hint/HintOptionChecker.java
- core/src/main/java/org/apache/calcite/rel/hint/HintStrategy.java
- core/src/main/java/org/apache/calcite/rel/hint/HintStrategyTable.java
- core/src/main/java/org/apache/calcite/rel/hint/Hintable.java
- core/src/main/java/org/apache/calcite/rel/hint/RelHint.java
- core/src/main/java/org/apache/calcite/sql/SqlUtil.java
- core/src/test/java/org/apache/calcite/test/RelBuilderTest.java
- core/src/test/java/org/apache/calcite/test/SqlHintsConverterTest.java
Add builder to RelHint so that we can construct it conveniently.
> [CALCITE-3766] Add a Builder to RelHint

- core/src/main/java/org/apache/calcite/rex/RexSimplify.java
> [CALCITE-3794] Stop simplifying using predicates if the pulled up predicates is empty

- core/src/main/java/org/apache/calcite/rex/RexSimplify.java
- core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
JIRA: https://issues.apache.org/jira/browse/CALCITE-3803
> [CALCITE-3803] Enhance RexSimplify to simplify 'a>1 or (a<3 and b)' to 'a>1 or b' if column a is not nullable

- core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-3817.
> [CALCITE-3817] VolcanoPlanner does not remove the entry in ruleNames when removing a rule

- core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java
- core/src/main/java/org/apache/calcite/rel/mutable/MutableSetOp.java
- core/src/test/java/org/apache/calcite/test/MaterializationTest.java
IntersectOnCalcsToIntersectUnifyRule is not implemented in SubstitutionVisitor, this pr try to implement it.
> [CALCITE-3634] Add IntersectOnCalcsToIntersectUnifyRule for materialized view recognition

- linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Jira ticket: [CALCITE-3829](https://issues.apache.org/jira/browse/CALCITE-3829)
`EnumerableDefaults#MergeJoinEnumerator` provides an Enumerator that performs a merge join between two sorted inputs. This sort operation can be potentially very expensive, so we should skip it if possible. Right now, merge join inputs' enumerators are created when `MergeJoinEnumerator` is constructed; however, there are some cases where we can skip the enumerator creation of one input: if the outer (i.e. left) enumerator returns no results, there is no need to access (and sort) the inner (i.e. right) enumerator. For this reason, we should delay the inner enumerator creation until the moment we are sure it is really required: when the first element of the outer enumerator is fetched.
> [CALCITE-3829] MergeJoinEnumerator should not use inputs enumerators until it is really required

- bom/build.gradle.kts
- core/build.gradle.kts
- core/src/main/java/org/apache/calcite/rel/RelWriter.java
- core/src/main/java/org/apache/calcite/rex/RexNode.java
- core/src/main/java/org/apache/calcite/rex/RexUtil.java
- core/src/main/java/org/apache/calcite/runtime/Hook.java
- core/src/main/java/org/apache/calcite/sql/SqlKind.java
- gradle.properties
- linq4j/build.gradle.kts
- linq4j/src/main/java/org/apache/calcite/linq4j/API.java
- linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Also fix the pigunit version to 0.16.0.
> [CALCITE-3871] Remove dependency of org.apiguardian:apiguardian-api

- core/src/main/java/org/apache/calcite/sql/type/SqlTypeAssignmentRule.java
https://issues.apache.org/jira/browse/CALCITE-3882
> [CALCITE-3882] Remove duplicated code from SqlTypeAssignmentRule 

- core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
- core/src/main/java/org/apache/calcite/plan/volcano/VolcanoRuleCall.java
> Following [CALCITE-3819] Prune parent RelNode when merging child RelSet with parent RelSet

- core/src/main/java/org/apache/calcite/plan/RelTraitSet.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-3891.
It takes too much time of the method, even this is a tiny portion overall.
> [CALCITE-3891] Remove use of Pair.zip in RelTraitSet

- core/src/main/java/org/apache/calcite/rex/RexAnalyzer.java
- core/src/main/java/org/apache/calcite/rex/RexSimplify.java
- core/src/test/java/org/apache/calcite/rex/RexProgramBuilderBase.java
- core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
Support simplifying expression - ( - ( x ) ) as x.
> [CALCITE-3872] Simplify expressions with unary minus

- .idea/vcs.xml
In light of https://github.com/apache/calcite/pull/1898,
> Add github pull request link in git commit messages in IDEA

- core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoin.java
- core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeJoinRule.java
- core/src/main/java/org/apache/calcite/rel/metadata/RelMdCollation.java
- core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
- core/src/test/java/org/apache/calcite/runtime/EnumerablesTest.java
- core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
- linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
Jira: [CALCITE-3833](https://issues.apache.org/jira/browse/CALCITE-3833)
> [CALCITE-3833] Support SemiJoin in EnumerableMergeJoin

- elasticsearch/src/main/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchJson.java
- elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/ElasticsearchJsonTest.java
If a property has name `type` or `properties` ES adapter doesn't correctly process the mapping structure. It doesn't correctly identify the leafs (properties) in JSON mapping.
> [CALCITE-3912] Incorrect mapping parsing when properties have same name as reserved keywords in ElasticSearch

- core/src/main/java/org/apache/calcite/rel/metadata/RelMdMinRowCount.java
- core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-3909
> [CALCITE-3909] RelMdMinRowCount doesn't take into account UNION DISTINCT

- core/src/main/java/org/apache/calcite/plan/volcano/Dumpers.java
- core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
> [CALCITE-3944] Move dumpSets and dumpGraphviz out of VolcanoPlanner

- core/src/main/java/org/apache/calcite/prepare/CalciteMaterializer.java
- core/src/main/java/org/apache/calcite/rel/RelShuttle.java
- core/src/main/java/org/apache/calcite/rel/RelShuttleImpl.java
- core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
https://issues.apache.org/jira/browse/CALCITE-3938
> [CALCITE-3938] Support LogicalCalc in RelShuttle

- core/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnOrigins.java
- core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
https://issues.apache.org/jira/browse/CALCITE-3971
> [CALCITE-3971] Support Calc in RelMdColumnOrigins 

- core/src/main/java/org/apache/calcite/plan/RelTraitSet.java
- core/src/test/java/org/apache/calcite/plan/RelTraitTest.java
> [CALCITE-3983] Add utility methods to RelTraitSet

- core/src/main/java/org/apache/calcite/sql2rel/RelFieldTrimmer.java
- core/src/test/java/org/apache/calcite/sql2rel/RelFieldTrimmerTest.java
https://issues.apache.org/jira/browse/CALCITE-3984
this pr try support exchange operator in RelFieldTrimmer.
> [CALCITE-3984] Support exchange operator in RelFieldTrimmer

- core/src/main/java/org/apache/calcite/rel/rules/CalcMergeRule.java
> Following [CALCITE-3997] Remove TransformationRule from CalcMergeRule temporarily

- core/src/main/java/org/apache/calcite/sql/SqlInsert.java
- core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
https://issues.apache.org/jira/browse/CALCITE-4019
> [CALCITE-4019] Visit SqlInsert with SqlShuttle cause NullPointerException

- core/src/main/java/org/apache/calcite/rel/rules/ProjectSortTransposeRule.java
- core/src/test/java/org/apache/calcite/test/TopDownOptTest.java
- druid/src/main/java/org/apache/calcite/adapter/druid/DruidRules.java
> [CALCITE-4023] Deprecate ProjectSortTransposeRule

- core/src/main/java/org/apache/calcite/adapter/enumerable/EnumTraitsUtils.java
- core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableCalc.java
- core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableProject.java
- core/src/test/java/org/apache/calcite/test/TopDownOptTest.java
- core/src/test/resources/org/apache/calcite/test/TopDownOptTest.xml
JIRA: https://issues.apache.org/jira/browse/CALCITE-4016
> [CALCITE-4016] Support trait propagation for EnumerableCalc

- core/src/main/java/org/apache/calcite/sql2rel/RelFieldTrimmer.java
- core/src/test/java/org/apache/calcite/sql2rel/RelFieldTrimmerTest.java
https://issues.apache.org/jira/browse/CALCITE-4020
> [CALCITE-4020] Support Calc operator in RelFieldTrimmer 

- core/src/main/java/org/apache/calcite/plan/RelOptNode.java
- core/src/main/java/org/apache/calcite/plan/hep/HepRelVertex.java
- core/src/main/java/org/apache/calcite/rel/AbstractRelNode.java
- core/src/main/java/org/apache/calcite/rel/RelNode.java
- core/src/main/java/org/apache/calcite/rel/core/Filter.java
- core/src/main/java/org/apache/calcite/rel/core/Join.java
- core/src/main/java/org/apache/calcite/rel/core/Project.java
- core/src/main/java/org/apache/calcite/rel/logical/LogicalFilter.java
- core/src/main/java/org/apache/calcite/rel/logical/LogicalJoin.java
- core/src/main/java/org/apache/calcite/rel/logical/LogicalProject.java
- core/src/main/java/org/apache/calcite/rel/type/RelDataType.java
> [CALCITE-3786] Make digestEquals and digestHash available to be overridden

- core/src/main/java/org/apache/calcite/rel/externalize/RelJson.java
- core/src/test/java/org/apache/calcite/plan/RelWriterTest.java
- core/src/test/java/org/apache/calcite/test/MockSqlOperatorTable.java
https://issues.apache.org/jira/browse/CALCITE-4062
> [CALCITE-4062] Support deserialize UDF array type from json string 

- core/src/main/java/org/apache/calcite/plan/Strong.java
- core/src/main/java/org/apache/calcite/rex/RexSimplify.java
- core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
- core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java
Jira: [CALCITE-4094](https://issues.apache.org/jira/browse/CALCITE-4094)
> [CALCITE-4094] Allow SqlOperator of SqlKind#OTHER_FUNCTION to define a Strong.Policy

- core/src/main/java/org/apache/calcite/plan/volcano/RelSubset.java
- core/src/main/java/org/apache/calcite/rel/AbstractRelNode.java
- core/src/main/java/org/apache/calcite/rel/core/Filter.java
- core/src/main/java/org/apache/calcite/rel/core/Join.java
- core/src/main/java/org/apache/calcite/rel/core/Project.java
- core/src/main/java/org/apache/calcite/rex/RexCall.java
> [CALCITE-4105] Replace Pair with Flat2List in RelDigestWriter

- core/src/main/java/org/apache/calcite/config/CalciteConnectionConfig.java
- core/src/main/java/org/apache/calcite/jdbc/ContextSqlValidator.java
- core/src/main/java/org/apache/calcite/prepare/PlannerImpl.java
- core/src/main/java/org/apache/calcite/tools/Programs.java
- core/src/test/java/org/apache/calcite/test/AbstractMaterializedViewTest.java
- core/src/test/java/org/apache/calcite/test/CalciteAssert.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/java/org/apache/calcite/tools/FrameworksTest.java
- plus/src/test/java/org/apache/calcite/materialize/TpcdsLatticeSuggesterTest.java
> [CALCITE-4112] Refine the usage of CalciteConnectionConfig in DecorrelateProgram (Jiatao Tao)

- core/src/main/java/org/apache/calcite/rel/AbstractRelNode.java
Remove final from AbstractRelNode#getRelTypeName
> [CALCITE-4127] Remove final from AbstractRelNode#getRelTypeName

- core/src/main/java/org/apache/calcite/sql/SqlSyntax.java
- core/src/main/java/org/apache/calcite/sql/SqlUtil.java
- core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
https://issues.apache.org/jira/browse/CALCITE-4022
> [CALCITE-4022] Support unparse special syntax when operator is INSERT

- core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
- core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
- core/src/test/java/org/apache/calcite/test/ReflectiveSchemaTest.java
> [CALCITE-2854] Codegen compile error when implementing unary minus function with data type BigDecimal

- core/src/main/java/org/apache/calcite/sql/SqlBinaryOperator.java
- core/src/test/java/org/apache/calcite/test/AbstractMaterializedViewTest.java
> Remove duplicate codes and fix typos (Auxten, Chunwei Lei)

- core/src/main/java/org/apache/calcite/rex/RexSimplify.java
- core/src/test/java/org/apache/calcite/rex/RexProgramBuilderBase.java
- core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
JIRA: https://issues.apache.org/jira/browse/CALCITE-4118
> [CALCITE-4118] RexSimplify might remove CAST from RexNode incorrectly

- core/src/test/java/org/apache/calcite/runtime/EnumerablesTest.java
- core/src/test/java/org/apache/calcite/test/JdbcTest.java
- core/src/test/java/org/apache/calcite/test/enumerable/EnumerableCorrelateTest.java
- core/src/test/java/org/apache/calcite/test/enumerable/EnumerableHashJoinTest.java
- core/src/test/resources/sql/blank.iq
- core/src/test/resources/sql/misc.iq
- core/src/test/resources/sql/sub-query.iq
- linq4j/src/main/java/org/apache/calcite/linq4j/EnumerableDefaults.java
[CALCITE-4113] Support LEFT join in EnumerableMergeJoin
> [CALCITE-4113] Support LEFT join in EnumerableMergeJoin

- core/src/main/java/org/apache/calcite/rel/type/RelCrossType.java
- core/src/main/java/org/apache/calcite/rel/type/RelDataTypeImpl.java
See https://issues.apache.org/jira/browse/CALCITE-4217
> [CALCITE-4217] Unlock RelCrossType#getFieldCount()

- core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java
- core/src/test/java/org/apache/calcite/test/MaterializedViewSubstitutionVisitorTest.java
Enhance the mv recognition ability of  `AggregateOnCalcToAggregateUnifyRule` when query has constant filter for missing columns in group by list. See jira [CALCITE-4182](https://issues.apache.org/jira/browse/CALCITE-4182) for details.
> [CALCITE-4182] Support mv recognition when query has constant filter for missing columns in group by list of mv

- core/src/main/java/org/apache/calcite/adapter/enumerable/EnumUtils.java
Some improvements:
1. Use ArrayDeque to replace LinkedList for the sake of efficiency.
2. Mark the list as "final".
> [CALCITE-4269] Improvement on enumerable implementation for HOP and SESSION

- core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorUtil.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
- core/src/test/java/org/apache/calcite/test/catalog/Fixture.java
> [CALCITE-4207] Validation fails for positional aggregate with current_date in 'case' expression

- core/src/main/java/org/apache/calcite/sql/SqlTumbleTableFunction.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
https://issues.apache.org/jira/browse/CALCITE-4289
> [CALCITE-4289] Fix wrong signature message in SqlTumbleWindowFunction

- site/_docs/file_adapter.md
This PR fixes adapter doc grammatical errors.
> Fix adapter doc grammatical errors

- core/src/main/java/org/apache/calcite/rel/metadata/RelMdUtil.java
- core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
CALCITE-4315: RelMdUtil#checkInputForCollationAndLimit does not check for null after calling mq.collations(input), which results in NPE.
Also add several simplifications and early returns.
> [CALCITE-4315] NPE in RelMdUtil#checkInputForCollationAndLimit

- core/src/main/codegen/default_config.fmpp
- core/src/main/codegen/templates/Parser.jj
- core/src/main/java/org/apache/calcite/sql/SqlExplain.java
- core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java
- core/src/test/java/org/apache/calcite/test/JdbcTest.java
- example/csv/src/test/java/org/apache/calcite/test/CsvTest.java
- file/src/test/java/org/apache/calcite/adapter/file/FileAdapterTest.java
- site/_docs/reference.md
See https://issues.apache.org/jira/browse/CALCITE-4260
> [CALCITE-4260] Support plan explain with dot format

- core/src/main/java/org/apache/calcite/sql2rel/RelDecorrelator.java
* Change all the members of RelDecorrelator protected scope
* Add RelDecorrelator.getVisitor to override the dispatcher visitor
* Add RelDecorrelator.getPostDecorrelateRules for post decorrelation
optimisation
> [CALCITE-4225] Make RelDecorrelator pluggable

- site/_docs/howto.md
Some changes on how-to release managing sections, after my experience as release manager.
> Update release instructions

- core/src/main/java/org/apache/calcite/rel/metadata/RelMetadataQuery.java
- core/src/main/java/org/apache/calcite/rel/rules/LoptMultiJoin.java
- core/src/main/java/org/apache/calcite/rel/rules/LoptOptimizeJoinRule.java
- core/src/main/java/org/apache/calcite/rel/rules/LoptSemiJoinOptimizer.java
- core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
- site/_docs/history.md
https://issues.apache.org/jira/projects/CALCITE/issues/CALCITE-4251?filter=recentlyviewed
> [CALCITE-4251] Get the origin column, even if it is derived (xzh)

- core/src/main/java/org/apache/calcite/rel/metadata/RelMdAllPredicates.java
- core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
https://issues.apache.org/jira/browse/CALCITE-4005
> [CALCITE-4005] Support Calc and SetOp operator in RelMdAllPredicates

- core/src/main/java/org/apache/calcite/sql/SqlCallBinding.java
Jira: https://issues.apache.org/jira/browse/CALCITE-4393
> [CALCITE-4393] ExceptionInInitializerError due to NPE in SqlCallBinding caused by circular dependency

- core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
- core/src/main/java/org/apache/calcite/runtime/Like.java
- core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlPosixRegexOperator.java
- core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
- core/src/test/java/org/apache/calcite/test/enumerable/EnumerableCalcTest.java
Jira: [CALCITE-4419](https://issues.apache.org/jira/browse/CALCITE-4419)
> [CALCITE-4419] Posix regex operators cannot be used within RelBuilder

- core/src/main/java/org/apache/calcite/sql2rel/StandardConvertletTable.java
- core/src/test/resources/sql/struct.iq
> CALCITE-4434 fix cannot implement 'CASE row WHEN row...'

- core/src/main/java/org/apache/calcite/config/CalciteSystemProperty.java
- core/src/main/java/org/apache/calcite/sql/type/CompositeOperandTypeChecker.java
- gradle.properties
- src/main/config/checkerframework/guava/Iterables.astub
See https://checkerframework.org/changelog.txt
> Bump checkerframework 3.7 -> 3.9.1

- core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
- core/src/test/java/org/apache/calcite/test/enumerable/EnumerableUncollectTest.java
See details in Jira: [CALCITE-2000](https://issues.apache.org/jira/browse/CALCITE-2000)
> [CALCITE-2000] UNNEST a collection that has a field with nested data generates an Exception

- core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java
- core/src/main/java/org/apache/calcite/rel/rules/AggregateFilterTransposeRule.java
- core/src/main/java/org/apache/calcite/rel/rules/AggregateStarTableRule.java
- core/src/main/java/org/apache/calcite/rel/rules/materialize/MaterializedViewAggregateRule.java
- core/src/main/java/org/apache/calcite/sql/SqlAggFunction.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlAnyValueAggFunction.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlCountAggFunction.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlMinMaxAggFunction.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlSingleValueAggFunction.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlSumAggFunction.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlSumEmptyIsZeroAggFunction.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Please see the discussions in https://issues.apache.org/jira/browse/CALCITE-4342
> [CALCITE-4342] More aggregate functions should be marked as splittable and ignore distinct optionality

- spark/src/main/java/org/apache/calcite/adapter/spark/SparkHandlerImpl.java
Hi @zabetak, current CI is blocked and all PRs are  failed, can you help review this PR, so that people can merge their PR?
> [CALCITE-4587] Set "spark.driver.bindAddress" explicitly to avoid "BindException" thrown by Spark (Jiatao Tao)

- core/src/main/java/org/apache/calcite/adapter/java/Array.java
- core/src/main/java/org/apache/calcite/adapter/java/Map.java
Signed-off-by: tison <wander4096@gmail.com>
straightforward
> Add generic info to Map & Array annotation

- core/src/main/java/org/apache/calcite/rel/rules/SemiJoinRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
Jira: [CALCITE-4621](https://issues.apache.org/jira/browse/CALCITE-4621)
> [CALCITE-4621] SemiJoinRule throws AssertionError on ANTI join

- core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
- core/src/test/resources/org/apache/calcite/test/TopDownOptTest.xml
See https://issues.apache.org/jira/browse/CALCITE-4638 for more details.
> [CALCITE-4638] VolcanoPlanner fails to recognize transformation rule correctly in the top-down mode (Vladimir Ozerov)

- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/java/org/apache/calcite/test/RelOptTestBase.java
- core/src/test/java/org/apache/calcite/test/TopDownOptTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Some refactoring and clean-up on RelOptRulesTest following [this suggestion](https://issues.apache.org/jira/browse/CALCITE-4621?focusedCommentId=17352671&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17352671) by @julianhyde ,
> RelOptRulesTest improvements

- core/src/main/java/org/apache/calcite/jdbc/SimpleCalciteSchema.java
- core/src/test/java/org/apache/calcite/test/JdbcTest.java
rebased original  PR #1792 from Feb2020.
> [CALCITE-3775] Implicit lookup methods in SimpleCalciteSchema ignore case sensitivity parameter (Alon Eldar)

- core/src/main/java/org/apache/calcite/plan/SubstitutionVisitor.java
- core/src/test/java/org/apache/calcite/test/MaterializedViewSubstitutionVisitorTest.java
Fix Bug as Follows
https://issues.apache.org/jira/browse/CALCITE-3935
> [CALCITE-3935] Enhance Join-Materialization, support to pull-up filters under join of left or right (xurenhe)

- babel/build.gradle.kts
- core/build.gradle.kts
- piglet/build.gradle.kts
- server/build.gradle.kts
…en disabled when build CALCITE
> [CALCITE-4851] Build gives lots of 'Execution optimizations have been disabled' warnings

- core/src/main/java/org/apache/calcite/plan/visualizer/InputExcludedRelWriter.java
- core/src/main/java/org/apache/calcite/plan/visualizer/NodeUpdateHelper.java
- core/src/main/java/org/apache/calcite/plan/visualizer/RuleMatchVisualizer.java
- core/src/main/java/org/apache/calcite/plan/visualizer/StepInfo.java
- core/src/main/java/org/apache/calcite/plan/visualizer/package-info.java
- core/src/main/resources/org/apache/calcite/plan/visualizer/viz-template.html
- core/src/test/java/org/apache/calcite/test/RelOptTestBase.java
- core/src/test/java/org/apache/calcite/test/RuleMatchVisualizerTest.java
- core/src/test/resources/org/apache/calcite/test/RuleMatchVisualizerTest.xml
An improved and refactored version of pull request https://github.com/apache/calcite/pull/2486.
> [CALCITE-4737] Add RelOptPlanner visualizer for debugging

- site/_data/contributors.yml
> Site: Add Alessandro Solimando as committer

- core/src/main/java/org/apache/calcite/rel/metadata/RelMdColumnOrigins.java
- core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
- core/src/test/resources/org/apache/calcite/rel/metadata/janino/GeneratedMetadata_ColumnOriginHandler.java
Support Snapshot in RelMdColumnOrigins
https://issues.apache.org/jira/browse/CALCITE-4977
> [CALCITE-4977] Support Snapshot in RelMdColumnOrigins

- core/src/main/java/org/apache/calcite/sql2rel/RelFieldTrimmer.java
- core/src/test/java/org/apache/calcite/sql2rel/RelFieldTrimmerTest.java
More info in [CALCITE-4995](https://issues.apache.org/jira/browse/CALCITE-4995)
> [CALCITE-4995] AssertionError caused by RelFieldTrimmer on SEMI/ANTI join

- site/_docs/tutorial.md
The code demo of [getTableMap](https://calcite.apache.org/javadocAggregate/org/apache/calcite/schema/impl/AbstractSchema.html#getTableMap()) is outdated. We can update it.
> [CALCITE-5079] Update code demo of tutorial.

- core/src/main/java/org/apache/calcite/tools/RelBuilder.java
- core/src/test/java/org/apache/calcite/test/MaterializedViewRelOptRulesTest.java
- core/src/test/java/org/apache/calcite/test/RelBuilderTest.java
See [1] and [2] for the context.
[1] https://lists.apache.org/thread/chwjcrdb760xbrgtx534008kpqoxbdvp
[2] https://issues.apache.org/jira/browse/CALCITE-5083
> [CALCITE-5083] In RelBuilder.project_, do not unwrap SARGs (Vladimir Ozerov)

- core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableMergeUnionRule.java
- core/src/test/java/org/apache/calcite/test/enumerable/EnumerableStringComparisonTest.java
[[CALCITE-5003](https://issues.apache.org/jira/browse/CALCITE-5003)] MergeUnion on types with different collators produces wrong result.
Make sure that all inputs are sorted in the same way, adding a projection in case the input's type collation is not the same as the union's.
> [CALCITE-5003] MergeUnion on types with different collators produces wrong result

- core/src/main/codegen/templates/Parser.jj
- testkit/src/main/java/org/apache/calcite/sql/parser/SqlParserTest.java
> [CALCITE-5150] Parser should parse subquery with order by inside array constructor

- README
- gradle.properties
- site/_docs/history.md
- site/_docs/howto.md
Intended to be shared with dev team to sync release notes
> Calcite 1.31 Release Preparation and Feedback

- core/src/main/java/org/apache/calcite/runtime/XmlFunctions.java
- core/src/test/java/org/apache/calcite/test/SqlXmlFunctionsTest.java
[CALCITE-5263](https://issues.apache.org/jira/browse/CALCITE-5263) Improve XmlFunctions by using an XML DocumentBuilder
> [CALCITE-5263] Improve XmlFunctions by using an XML DocumentBuilder

- testkit/src/main/java/org/apache/calcite/test/DiffRepository.java
[[CALCITE-5274](https://issues.apache.org/jira/browse/CALCITE-5274)] Improve DocumentBuilderFactory in DiffRepository test class by using secure features
> [CALCITE-5274] Improve DocumentBuilderFactory in DiffRepository test class by using secure features

- README.md
- site/_docs/howto.md
- site/develop/index.md
To be merge on 6th November 2022 at the earliest.
> [CALCITE-5353] Document new procedure for requesting JIRA accounts and becoming a contributor

- core/src/main/java/org/apache/calcite/runtime/SpatialTypeFunctions.java
- core/src/test/resources/sql/spatial.iq
- site/_docs/reference.md
This PR adds support for the following spatial measurement functions:
- ST_Area
- ST_ClosestCoordinate
- ST_ClosestPoint
- ST_FurthestCoordinate
- ST_Length
- ST_LocateAlong
- ST_LongestLine
- ST_MaxDistance
- ST_Perimeter
- ST_ProjectPoint
> [CALCITE-5362] Geometry measurement functions

- core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
RelToSqlConverter should retain the aggregation logic when Project without RexInputRef on the Aggregate.
```
LogicalProject(L_COST=[$0])
LogicalJoin(condition=[=($1, $2)], joinType=[inner])
LogicalValues(tuples=[[{ 0, 1 }]])
LogicalProject(K=[1]) 
LogicalAggregate(group=[{}], DUMMY=[COUNT()])
LogicalUnion(all=[false])
LogicalValues(tuples=[[{ 1 }]])
LogicalValues(tuples=[[{ 2 }]])
```
> [CALCITE-5506] RelToSqlConverter should retain the aggregation logic

- core/src/main/java/org/apache/calcite/rel/rules/SubQueryRemoveRule.java
- core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
- core/src/test/resources/sql/misc.iq
- core/src/test/resources/sql/sub-query.iq
> [CALCITE-5789] Query with two nested subqueries where the inner-most references the outer-most table returns wrong result

- core/src/main/codegen/default_config.fmpp
- core/src/main/codegen/templates/Parser.jj
- core/src/main/java/org/apache/calcite/sql/SqlKind.java
- core/src/main/java/org/apache/calcite/sql/SqlTruncate.java
- core/src/main/java/org/apache/calcite/sql/ddl/SqlDdlNodes.java
- core/src/main/java/org/apache/calcite/sql/ddl/SqlTruncateTable.java
- server/src/main/codegen/config.fmpp
- server/src/main/codegen/includes/parserImpls.ftl
- server/src/main/java/org/apache/calcite/server/ServerDdlExecutor.java
- server/src/test/java/org/apache/calcite/test/ServerParserTest.java
- server/src/test/java/org/apache/calcite/test/ServerTest.java
- server/src/test/resources/sql/table.iq
> [CALCITE-5688] Support TRUNCATE TABLE DDL statement in server module

- innodb/build.gradle.kts
- innodb/src/main/java/org/apache/calcite/adapter/innodb/IndexCondition.java
- innodb/src/main/java/org/apache/calcite/adapter/innodb/InnodbFilterTranslator.java
- innodb/src/main/java/org/apache/calcite/adapter/innodb/InnodbSchema.java
- innodb/src/main/java/org/apache/calcite/adapter/innodb/InnodbTableScan.java
- innodb/src/main/java/org/apache/calcite/adapter/innodb/InnodbToEnumerableConverter.java
- innodb/src/test/java/org/apache/calcite/adapter/innodb/InnodbAdapterTest.java
https://issues.apache.org/jira/browse/CALCITE-5823
remove commons-collections use in innodb
This change is a trivial rework / code cleanup. Verifying by current total cases.
> [CALCITE-5823] Remove commons-collections dependency from innodb

- core/src/test/java/org/apache/calcite/rex/RexProgramBuilderBase.java
Adjust some java docs and object references in RexProgramBuilderBase, which helps others to understand better.
> [MINOR] Adjust nullableType and java doc for RexProgramBuilderBase

- core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
> [CALCITE-5865] ClassCastException with FLOOR and CEIL on conformances that are not builtin (follow-up)

- core/src/main/java/org/apache/calcite/rel/metadata/RelMdCollation.java
- core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
- core/src/test/resources/org/apache/calcite/rel/metadata/janino/GeneratedMetadata_CollationHandler.java
> [CALCITE-5903] RelMdCollation does not define collations for EnumerableLimit

- babel/src/test/resources/sql/big-query.iq
- core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
- site/_docs/reference.md
- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
PR to contribute to https://issues.apache.org/jira/browse/CALCITE-5591
Any comments, questions, or suggestions appreciated as always!
[BigQuery docs](https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions#safe_negate)
> [CALCITE-5766] Add SAFE_NEGATE function (enabled for BigQuery library)

- core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
- core/src/test/java/org/apache/calcite/test/enumerable/EnumerableStringComparisonTest.java
Jira: CALCITE-5967
Fix regression introduced as a side effect of CALCITE-5914
> [CALCITE-5967] UnsupportedOperationException while implementing a call that requires a special collator

- testkit/src/main/java/org/apache/calcite/test/QuidemTest.java
> [CALCITE-5980] QuidemTests are not effectively executed on Windows

- core/src/main/java/org/apache/calcite/plan/RelOptRules.java
- core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java
- core/src/main/java/org/apache/calcite/rel/rules/MinusToDistinctRule.java
- core/src/test/java/org/apache/calcite/test/JdbcTest.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
1. Add MinusToDistinctRule 
2. Add unit test
More details could see:https://issues.apache.org/jira/browse/CALCITE-5889
> [CALCITE-5889] Add the RelRule that converts Minus into UNION ALL..GROUP BY...WHERE

- bom/build.gradle.kts
- gradle.properties
- mongodb/build.gradle.kts
- mongodb/src/main/java/org/apache/calcite/adapter/mongodb/MongoSchema.java
- mongodb/src/main/java/org/apache/calcite/adapter/mongodb/MongoSchemaFactory.java
- mongodb/src/test/java/org/apache/calcite/adapter/mongodb/MongoAdapterTest.java
- mongodb/src/test/java/org/apache/calcite/adapter/mongodb/MongoDatabasePolicy.java
The `mongo-java-driver` dependency was superseded by `mongodb-driver-sync`.
> [CALCITE-6004] Replace deprecated mongo-java-driver dependency

- core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-5961
> [CALCITE-5961] Type inference of ARRAY_COMPACT is incorrect

- core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java
- core/src/main/java/org/apache/calcite/rel/rules/SortRemoveRedundantRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
More details could see: https://issues.apache.org/jira/browse/CALCITE-5994
> [CALCITE-5994]  Add optimization rule to remove Sort when its input's row number is less or equal to one

- core/src/main/java/org/apache/calcite/plan/RelOptUtil.java
- core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java
- core/src/main/java/org/apache/calcite/rel/rules/SortMergeRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
1. Add the SortMergeRule
2. Add the Limit merge unit test
More details could see : [CALCITE-5940](https://issues.apache.org/jira/browse/CALCITE-5940)
> [CALCITE-5940] Add the Rule to merge Limit

- core/src/main/java/org/apache/calcite/sql/fun/SqlMapValueConstructor.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlMultisetValueConstructor.java
- core/src/test/resources/sql/misc.iq
- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-6040
> [CALCITE-6040] The operand type inference of SqlMapValueConstructor is incorrect

- core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
- core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
- core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
> [CALCITE-6013] RelBuilder should simplify plan by pruning unused measures

- core/src/main/java/org/apache/calcite/rel/externalize/RelJson.java
- core/src/test/java/org/apache/calcite/plan/RelWriterTest.java
https://issues.apache.org/jira/browse/CALCITE-5607
> [CALCITE-5607] Error when deserializing TIMESTAMP_DIFF in RelJson#toJson

- core/src/test/java/org/apache/calcite/examples/RelBuilderExample.java
> [MINOR]  Better message when no corresponding example

- core/src/test/java/org/apache/calcite/sql/type/SqlTypeUtilTest.java
https://issues.apache.org/jira/browse/CALCITE-6131
> [CALCITE-6131] There are duplicate sample tests in SqlTypeUtilTest

- example/csv/src/test/java/org/apache/calcite/test/CsvTest.java
This is not only to make sure that it works, to display all the data in this table, but also for beginners to better write their own tests based on this data.
> [MINOR] show all data on CsvTest

- core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
- core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java
- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-6127
> [CALCITE-6127] The spark array function gives NullPointerException when element is row type

- testkit/src/main/java/org/apache/calcite/sql/parser/SqlParserTest.java
According to the comments there should be no errors other than unset
> [MINOR] Delete useless comments

- core/src/main/java/org/apache/calcite/sql/SqlKind.java
- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-6165
> [CALCITE-6165] Add DATE_ADD test and DATE_DIFF test on SqlOperatorTest

- core/src/main/java/org/apache/calcite/sql/validate/implicit/AbstractTypeCoercion.java
Looks like merging an old PR broke the build. I guess some checkstyle rules have changed since that PR was checked.
Hopefully this small change should fix the build.
> [MINOR] Checkstyle to fix broken build

- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-6184
> [CALCITE-6184] Add checkNullTest on SqlOperatorTest

- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
I used @snuyanzin 's PoC PR and @julianhyde 's improvements to make this PR and have credited them in the latest commit in this chain.
I did not modify MOD and % because the syntax seemed different enough that I preferred keeping them separate.
> [CALCITE-6172] Allow aliased operators to re-use existing tests

- core/src/main/java/org/apache/calcite/sql/SqlLiteral.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
Thank you to @zstan for a very precise diagnosis of the problem location.
> [CALCITE-6190] Incorrect precision derivation for negative numeric types

- core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcUtils.java
Improve JDBC connection resource in JDBCUtils: not need multiple judge connection whether close
> [CALCITE-6207] Improve JDBC connection resource in JDBCUtils

- core/src/test/java/org/apache/calcite/util/format/FormatElementEnumTest.java
Improve FormatElementEnumTest make code clean.
https://issues.apache.org/jira/browse/CALCITE-6189
> [CALCITE-6189] Improve FormatElementEnumTest

- core/src/main/java/org/apache/calcite/sql/SqlDialect.java
- core/src/main/java/org/apache/calcite/sql/dialect/PrestoSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
This PR fix the NullCollation of Presto dialect, changed from "LOW" to "LAST"
https://issues.apache.org/jira/projects/CALCITE/issues/CALCITE-6213
> [CALCITE-6213] The default behavior of NullCollation in Presto is LAST

- core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
- site/_docs/reference.md
https://issues.apache.org/jira/browse/CALCITE-6222
> [CALCITE-6222] Mysql does not have to_char function

- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-6234
> [CALCITE-6234] Add tests on SqlOperatorTest for to_char function

- core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
- site/_docs/reference.md
- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
Add Spark as a supported library for functions that have already been implemented for other libraries.
https://issues.apache.org/jira/browse/CALCITE-6241
> [CALCITE-6241] Enable a few existing functions to Spark library

- site/_docs/howto.md
Add hints with restrictions for documents/filters to howto site
> [CALCITE-6250] Limitations of MongoDB adapter are not documented

- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-6273
> [CALCITE-6273] Add sqrt negative test in SqlOperatorTest

- core/src/main/java/org/apache/calcite/sql/SqlDialect.java
- core/src/main/java/org/apache/calcite/sql/SqlDialectFactoryImpl.java
- core/src/main/java/org/apache/calcite/sql/dialect/StarRocksSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Implementing StarRocks dialect in Calcite
https://issues.apache.org/jira/browse/CALCITE-6257
> [CALCITE-6257] StarRocks dialect implementation

- core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
- core/src/main/java/org/apache/calcite/sql/type/ArrayElementOperandTypeChecker.java
- core/src/main/java/org/apache/calcite/sql/type/NotNullOperandTypeChecker.java
- core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java
- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-5893
> [CALCITE-5893] Wrong NULL operand behavior of ARRAY_CONTAINS/ARRAY_EXCEPT/ARRAY_INTERSECT In Spark Library

- core/src/main/java/org/apache/calcite/sql/dialect/MysqlSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
> [CALCITE-6306] JDBC adapter should not generate FILTER (WHERE) in MySQL and StarRocks dialect

- core/src/main/java/org/apache/calcite/sql/SqlTimeTzLiteral.java
- core/src/main/java/org/apache/calcite/sql/SqlTimestampTzLiteral.java
The main build seems to be broken, this is an attempt to fix it.
It seems to be caused by a buggy checkStyle rule.
> Fix style check rule that breaks the build

- core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
- core/src/main/java/org/apache/calcite/rel/rules/ReduceExpressionsRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
while optimizing ARRAY_CONCAT expression
> [CALCITE-6353] Optimization CoreRules.PROJECT_REDUCE_EXPRESSIONS crashes

- .github/workflows/buildcache.yml
- .github/workflows/gradle-wrapper-validation.yml
> [CALCITE-6384] Add ASF header to buildcache.yml, gradle-wrapper-validation.yml

- site/_docs/adapter.md
- fixes typo for time window example
> [CALCITE-6428] Update adapter.md

- site/_docs/adapter.md
> [CALCITE-6428] Typo in adapter documentation

- core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
* Detect when a nested AS call is inserted and prevent it
> [CALCITE-6370] AS operator problems with USING clause

- core/src/main/java/org/apache/calcite/sql/dialect/StarRocksSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
https://issues.apache.org/jira/browse/CALCITE-6426
> [CALCITE-6426] Invalid unparse for INT and BIGINT in StarRocksDialect

- core/src/main/java/org/apache/calcite/sql2rel/StandardConvertletTable.java
@zabetak hopefully this PR will fix the problem of STDDEV requiring a higher declared precision when combined with #3733
> [CALCITE-6427] Use a higher precision for DECIMAL intermediate results for some aggregate functions like STDDEV

- core/src/main/codegen/templates/Parser.jj
- core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableWindow.java
- core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
- core/src/main/java/org/apache/calcite/adapter/enumerable/WinAggContext.java
- core/src/main/java/org/apache/calcite/rel/core/Window.java
- core/src/main/java/org/apache/calcite/rel/externalize/RelJson.java
- core/src/main/java/org/apache/calcite/rel/logical/LogicalWindow.java
- core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
- core/src/main/java/org/apache/calcite/rel/rules/ProjectWindowTransposeRule.java
- core/src/main/java/org/apache/calcite/rel/rules/ReduceExpressionsRule.java
- core/src/main/java/org/apache/calcite/rex/RexBuilder.java
- core/src/main/java/org/apache/calcite/rex/RexShuttle.java
- core/src/main/java/org/apache/calcite/rex/RexWindow.java
- core/src/main/java/org/apache/calcite/rex/RexWindowExclusion.java
- core/src/main/java/org/apache/calcite/sql/SqlWindow.java
- core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
- core/src/main/java/org/apache/calcite/tools/RelBuilder.java
- core/src/test/java/org/apache/calcite/rel/logical/ToLogicalConverterTest.java
- core/src/test/resources/sql/winagg.iq
- piglet/src/main/java/org/apache/calcite/piglet/PigRelToSqlConverter.java
- site/_docs/algebra.md
- site/_docs/reference.md
- testkit/src/main/java/org/apache/calcite/sql/parser/SqlParserTest.java
This PR adds support for frame exclusion clause in window functions.
> [CALCITE-5855] Implement frame exclusion in window functions

- babel/src/test/resources/sql/spark.iq
- core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
- core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
- core/src/main/java/org/apache/calcite/sql/SqlKind.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
- core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java
- core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
- core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java
- site/_docs/reference.md
- testkit/src/main/java/org/apache/calcite/sql/test/SqlOperatorFixture.java
- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-6446
Add Function [CONCAT_WS](https://spark.apache.org/docs/latest/api/sql/index.html#concat_ws) in Spark library.
> [CALCITE-6446] Add CONCAT_WS function (enabled in Spark library)

- core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcRules.java
- core/src/test/java/org/apache/calcite/test/JdbcAdapterTest.java
…n include IS TRUE、IS NULL、Dynamic parameter、CAST、Literal comparison
> [CALCITE-6401] JDBC adapter cannot push down JOIN with condition includes IS TRUE、IS NULL、Dynamic parameter、CAST、Literal comparison

- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
This test is to show that SortRemoveConstantKeys can optimize Order By null
> Add testSortRemoveConstantKeyWhenOrderByIsNull on RelOptRulesTest

- core/src/main/java/org/apache/calcite/sql2rel/RelDecorrelator.java
- core/src/test/java/org/apache/calcite/sql2rel/RelDecorrelatorTest.java
- core/src/test/resources/sql/sub-query.iq
> [CALCITE-6468] RelDecorrelator throws AssertionError if correlated variable is used as Aggregate group key

- core/src/main/java/org/apache/calcite/plan/volcano/VolcanoPlanner.java
Improve Javadoc [3851](https://github.com/apache/calcite/pull/3851)
> Following [CALCITE-6462] Clarify comments

- core/src/main/java/org/apache/calcite/rel/RelCollations.java
- core/src/main/java/org/apache/calcite/rel/rules/SortJoinCopyRule.java
- core/src/main/java/org/apache/calcite/rel/rules/SortJoinTransposeRule.java
- core/src/main/java/org/apache/calcite/rel/rules/SortRemoveConstantKeysRule.java
> [CALCITE-6488] Ensure collations created by RelCollations are canonized once

- Jenkinsfile
- gradle.properties
All details in the ticket, draft PR for now
> [CALCITE-6484] Sonar analysis fails intermittently due to OOM

- core/src/main/java/org/apache/calcite/sql/fun/SqlRandIntegerFunction.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
- core/src/test/java/org/apache/calcite/test/RelMdPredicatesTest.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
> [CALCITE-6507] Random functions are incorrectly considered deterministic

- core/src/main/java/org/apache/calcite/sql/SqlKind.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
- core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java
- core/src/main/java/org/apache/calcite/sql2rel/StandardConvertletTable.java
- site/_docs/reference.md
- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
https://issues.apache.org/jira/browse/CALCITE-6396
> [CALCITE-6396] Add ADD_MONTHS function (enabled in Oracle, Spark library)

- core/src/main/java/org/apache/calcite/sql/SqlStaticAggFunction.java
See more info: [CALCITE-6531](https://issues.apache.org/jira/browse/CALCITE-6531)
> [CALCITE-6531] Correct Javadoc example in SqlStaticAggFunction#constant

- core/src/main/java/org/apache/calcite/adapter/enumerable/RexToLixTranslator.java
- core/src/main/java/org/apache/calcite/rel/type/DelegatingTypeSystem.java
- core/src/main/java/org/apache/calcite/rel/type/RelDataTypeSystem.java
- core/src/main/java/org/apache/calcite/rel/type/RelDataTypeSystemImpl.java
- core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
- core/src/test/java/org/apache/calcite/test/CoreQuidemTest.java
- core/src/test/java/org/apache/calcite/test/CustomRelDataTypeSystem.java
- core/src/test/resources/sql/misc.iq
- linq4j/src/main/java/org/apache/calcite/linq4j/tree/Expressions.java
- linq4j/src/main/java/org/apache/calcite/linq4j/tree/Primitive.java
- linq4j/src/main/java/org/apache/calcite/linq4j/tree/UnaryExpression.java
…nding mode when cast an approximate numeric to int
> [CALCITE-4838] Add RoundingMode in RelDataTypeSystem to specify the rounding behavior

- core/src/main/java/org/apache/calcite/rel/metadata/janino/CacheGeneratorUtil.java
Jira ticket - https://issues.apache.org/jira/browse/CALCITE-5613
> [CALCITE-5613] Assert for number of args for metadata methods at CacheGeneratorUtil

- core/src/test/java/org/apache/calcite/test/LintTest.java
Sorry I didn't add it in [jira](https://issues.apache.org/jira/browse/CALCITE-6493)
> Add Snowflake and Redshift as constraints

- core/src/main/java/org/apache/calcite/materialize/Lattice.java
- core/src/test/java/org/apache/calcite/test/LatticeTest.java
https://issues.apache.org/jira/browse/CALCITE-6603
> [CALCITE-6603] Lattice SQL supports generation of specified dialects

- site/_docs/index.md
https://issues.apache.org/jira/browse/CALCITE-6613
> [CALCITE-6613] Make the Background code examples in Calcite official documentation clearer

- core/src/main/java/org/apache/calcite/DataContext.java
- core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
- core/src/main/java/org/apache/calcite/jdbc/CalciteConnectionImpl.java
- core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
- core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
- site/_docs/reference.md
- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
- Support Oracle SYSDATE and SYSTIMESTAMP functions
> [CALCITE-6666] Support Oracle SYSDATE and SYSTIMESTAMP functions

- arrow/src/main/java/org/apache/calcite/adapter/arrow/ArrowTranslator.java
- arrow/src/test/java/org/apache/calcite/adapter/arrow/ArrowAdapterDataTypesTest.java
- arrow/src/test/java/org/apache/calcite/adapter/arrow/ArrowAdapterTest.java
- arrow/src/test/java/org/apache/calcite/adapter/arrow/ArrowData.java
https://issues.apache.org/jira/browse/CALCITE-6668
> [CALCITE-6668] Arrow adapter should support IS FALSE Operator and IS TRUE Operator

- core/src/main/java/org/apache/calcite/plan/AbstractRelOptPlanner.java
- core/src/main/java/org/apache/calcite/plan/RelOptPlanner.java
- core/src/main/java/org/apache/calcite/sql2rel/RelDecorrelator.java
- core/src/test/java/org/apache/calcite/sql2rel/RelDecorrelatorTest.java
See https://issues.apache.org/jira/browse/CALCITE-6674
> [CALCITE-6674] Make RelDecorrelator rules configurable

- core/src/main/java/org/apache/calcite/jdbc/CalciteConnectionImpl.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlAbstractConformance.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlConformance.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlConformanceEnum.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlDelegatingConformance.java
- core/src/test/java/org/apache/calcite/test/CoreQuidemTest.java
- core/src/test/resources/sql/dummy.iq
For details: https://issues.apache.org/jira/browse/CALCITE-6678
> [CALCITE-6678] Calcite should support dual table query when db provides this feature

- core/src/main/java/org/apache/calcite/rel/metadata/RelMdUniqueKeys.java
The `RelMdUniqueKeys#getPassedThroughCols` method exists only for performing a cross product of the various mappings between input and output "pass through" columns.
The entire method can be replaced by exploiting the built-in `Linq4j#product` API and few other utility methods.
After the refactoring the code is easier to follow and potentially more efficient since the result is computed gradually and we don't have to retain the entire cross product result in memory.
> [CALCITE-6720] Refactor cross product logic in RelMdUniqueKeys#getPassedThroughCols using Linq4j#product

- core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
- core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
- core/src/test/resources/sql/functions.iq
- testkit/src/main/java/org/apache/calcite/test/CalciteAssert.java
- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
* Support MySQL BIT_COUNT with boolean and String types parameter
> [CALCITE-6700] MySQL BIT_COUNT function should return result when parameter is Boolean, String, Date, Time and Timestamp types

- core/src/main/java/org/apache/calcite/sql2rel/RelFieldTrimmer.java
- core/src/test/java/org/apache/calcite/sql2rel/RelFieldTrimmerTest.java
Before
```
LogicalAggregate(group=[{3}], SAL=[SUM($2)])
LogicalFilter(condition=[>($3, 100)])
LogicalProject(EMPNO=[$0], ENAME=[$1], SAL=[$5], DEPTNO=[$7])
LogicalTableScan(table=[[scott, EMP]])
```
After
```
LogicalAggregate(group=[{2}], SAL=[SUM($1)])
LogicalFilter(condition=[>($2, 100)])
LogicalProject(EMPNO=[$0], SAL=[$5], DEPTNO=[$7])
LogicalTableScan(table=[[scott, EMP]])
```
> [CALCITE-6734] RelFieldTrimmer should trim Aggregate's input fields which are arguments of unused aggregate functions

- site/_data/contributors.yml
> Site: Update PMC Chair

- arrow/src/main/java/org/apache/calcite/adapter/arrow/ArrowFieldTypeFactory.java
- arrow/src/main/java/org/apache/calcite/adapter/arrow/ArrowTable.java
- arrow/src/test/java/org/apache/calcite/adapter/arrow/ArrowAdapterDataTypesTest.java
- arrow/src/test/java/org/apache/calcite/adapter/arrow/ArrowAdapterTest.java
- arrow/src/test/java/org/apache/calcite/adapter/arrow/ArrowDataTest.java
reopen https://github.com/apache/calcite/pull/4092
> [CALCITE-6690] Arrow adapter support DECIMAL with precision and scale

- arrow/src/main/java/org/apache/calcite/adapter/arrow/ArrowFieldTypeFactory.java
- arrow/src/test/java/org/apache/calcite/adapter/arrow/ArrowAdapterDataTypesTest.java
- arrow/src/test/java/org/apache/calcite/adapter/arrow/ArrowAdapterTest.java
- arrow/src/test/java/org/apache/calcite/adapter/arrow/ArrowDataTest.java
https://issues.apache.org/jira/browse/CALCITE-6760
> [CALCITE-6760] Support time data type in Arrow adapter

- core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
- core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
- core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
- site/_docs/reference.md
- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
Currently calcite not support bin functions for Hive and Spark Library, need to support it.
JIRA: https://issues.apache.org/jira/browse/CALCITE-6815
> [CALCITE-6815] Support bin function for Spark and Hive Library

- core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6818
> [CALCITE-6818] Write LIMIT for fetch operations in Snowflake

- core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
- core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
- core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
- core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
- site/_docs/reference.md
- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6821
> [CALCITE-6821] Support crc32 function for Hive and Spark library

- core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
- site/_docs/reference.md
- testkit/src/main/java/org/apache/calcite/test/SqlOperatorTest.java
As describe in JIRA：https://issues.apache.org/jira/browse/CALCITE-6844
> [CALCITE-6844] Add all array spark functions which also support in Hive(enable in Hive Library)

- core/src/main/java/org/apache/calcite/rel/rules/ProjectRemoveRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
issue: https://issues.apache.org/jira/browse/CALCITE-6850
> [CALCITE-6850] ProjectRemoveRule with two Projects does not keep field names from the top one

- core/src/main/java/org/apache/calcite/sql2rel/SqlToRelConverter.java
- core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
- core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
> [CALCITE-6885] SqlToRelConverter#convertUsing should not fail if commonTypeForBinaryComparison returns null

- core/src/main/java/org/apache/calcite/sql/dialect/DerbySqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6892
> [CALCITE-6892]  CHAR_LENGTH Function is not recognized in DerbySQL

- core/src/main/java/org/apache/calcite/jdbc/CalciteSchema.java
- core/src/test/java/org/apache/calcite/test/JdbcTest.java
> [CALCITE-6903] CalciteSchema#getSubSchemaMap must consider implicit sub-schemas

- core/src/main/java/org/apache/calcite/sql/dialect/ClickHouseSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
As descrption in JIRA: https://issues.apache.org/jira/browse/CALCITE-6900
> [CALCITE-6900] Support Char type cast in ClickHouse Dialect

- mongodb/src/main/java/org/apache/calcite/adapter/mongodb/MongoFilter.java
- mongodb/src/test/java/org/apache/calcite/adapter/mongodb/MongoAdapterTest.java
see https://issues.apache.org/jira/browse/CALCITE-2109
- Support in condition with and condition
- refactor translateOr and translateAnd
> [CALCITE-2109] MongoAdapter: Support in condition with and condition

- core/src/main/java/org/apache/calcite/sql/SqlDialect.java
- core/src/main/java/org/apache/calcite/sql/SqlDialectFactoryImpl.java
- core/src/main/java/org/apache/calcite/sql/dialect/PrestoSqlDialect.java
- core/src/main/java/org/apache/calcite/sql/dialect/TrinoSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6820
> [CALCITE-6820] Trino dialect implementation

- core/src/main/java/org/apache/calcite/sql/SqlDialect.java
- core/src/main/java/org/apache/calcite/sql/SqlDialectFactoryImpl.java
- core/src/main/java/org/apache/calcite/sql/dialect/DorisSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
link: [CALCITE-6888](https://issues.apache.org/jira/browse/CALCITE-6888)
> [CALCITE-6888] Doris dialect implementation

- core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
- core/src/main/java/org/apache/calcite/rel/core/Join.java
- core/src/main/java/org/apache/calcite/rel/core/JoinInfo.java
- core/src/main/java/org/apache/calcite/rel/rules/LoptOptimizeJoinRule.java
- core/src/main/java/org/apache/calcite/rel/rules/LoptSemiJoinOptimizer.java
- core/src/main/java/org/apache/calcite/rel/rules/SortJoinTransposeRule.java
- core/src/test/java/org/apache/calcite/test/JdbcTest.java
- core/src/test/resources/sql/join.iq
Jira link: [CALCITE-6904](https://issues.apache.org/jira/browse/CALCITE-6904)
> [CALCITE-6904] IS_NOT_DISTINCT_FROM is incorrectly handled by EnumerableJoinRule

- core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java
- core/src/main/java/org/apache/calcite/rel/rules/IntersectToSemiJoinRule.java
- core/src/test/java/org/apache/calcite/test/JdbcTest.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
link: [CALCITE-6880](https://issues.apache.org/jira/browse/CALCITE-6880)
> [CALCITE-6880] Implement IntersectToSemiJoinRule

- core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6943
> [CALCITE-6943] Calcite JDBC adapter for Hive should translate APPROX_COUNT_DISTINCT to COUNT DISTINCT

- core/src/main/java/org/apache/calcite/rex/RexBuilder.java
- core/src/test/java/org/apache/calcite/rex/RexBuilderTest.java
Please see: [CALCITE-6938](https://issues.apache.org/jira/browse/CALCITE-6938)
> [CALCITE-6938] Support zero value creation of nested data types

- core/src/main/java/org/apache/calcite/sql/dialect/ClickHouseSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6941
> [CALCITE-6941] Array/Map value constructor is unparsed incorrectly in ClickHouse

- core/src/main/java/org/apache/calcite/sql/dialect/ClickHouseSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6949
> [CALCITE-6949] ClickHouse not support floor date to SECOND/MILLISECOND/MICROSECOND/NANOSECOND

- core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
- core/src/main/java/org/apache/calcite/sql/dialect/PhoenixSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6940
> [CALCITE-6940]  Hive/Phoenix Dialect should not cast to REAL type directly

- core/src/test/java/org/apache/calcite/test/LintTest.java
The main goal is to capture more invalid term usages and easier definition of new rules.
1. Use pattern based definition in term rules and allow multiple valid/golden terms
2. Use List based rule collection for faster iteration; since we iterate over all rules using Map is wasteful
3. Make existing rules case-insensitive to capture more invalid usages of DBMS terms
4. Pre-compile and instantiate patterns and rules only once
> [CALCITE-6915] Generalize terminology Linter to allow pattern based checks in commit messages

- core/src/main/java/org/apache/calcite/rel/RelShuttle.java
- core/src/main/java/org/apache/calcite/rel/RelShuttleImpl.java
- core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
As descprtion in JIRA: https://issues.apache.org/jira/browse/CALCITE-6959
> [CALCITE-6959] Support LogicalAsofJoin in RelShuttle

- core/src/main/java/org/apache/calcite/rel/RelShuttle.java
- core/src/main/java/org/apache/calcite/rel/RelShuttleImpl.java
- core/src/main/java/org/apache/calcite/rel/logical/LogicalRepeatUnion.java
- core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6961
> [CALCITE-6961] Support LogicalRepeatUnion in RelShuttle

- core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java
- core/src/main/java/org/apache/calcite/rel/rules/UnionEliminatorRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Please see: [CALCITE-6953](https://issues.apache.org/jira/browse/CALCITE-6953)
> [CALCITE-6953] Extend UnionEliminatorRule to support Intersect and Minus

- core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java
- core/src/main/java/org/apache/calcite/rel/rules/JoinExpandOrToUnionRule.java
- core/src/test/java/org/apache/calcite/test/JdbcTest.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Please see: [CALCITE-6966](https://issues.apache.org/jira/browse/CALCITE-6966)
> [CALCITE-6966] Change JoinConditionOrExpansionRule name and accept more predicates that will allow the expansion to be performed

- core/src/main/java/org/apache/calcite/sql/SqlCall.java
- testkit/src/main/java/org/apache/calcite/sql/parser/SqlParserTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6944
> [CALCITE-6944] Align toSqlString with SQL std for Table Args in PTF

- core/src/main/java/org/apache/calcite/rel/rules/MinusToAntiJoinRule.java
Please see: [CALCITE-6948](https://issues.apache.org/jira/browse/CALCITE-6948)
> Documentation Supplement for MinusToAntiJoinRule

- core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java
- core/src/main/java/org/apache/calcite/rel/rules/MinusToFilterRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Please see: [CALCITE-6973](https://issues.apache.org/jira/browse/CALCITE-6973)
> [CALCITE-6973] Add rule to convert Minus to Filter

- core/src/main/java/org/apache/calcite/sql/dialect/ClickHouseSqlDialect.java
- core/src/main/java/org/apache/calcite/sql/dialect/StarRocksSqlDialect.java
- core/src/main/java/org/apache/calcite/util/RelToSqlConverterUtil.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6979
> [CALCITE-6979] Invalid unparse for IS TRUE,IS FALSE,IS NOT TRUE and IS NOT FALSE in ClickHouseDialect

- core/src/main/java/org/apache/calcite/rel/metadata/RelMdSize.java
- core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
> [CALCITE-6594] RelMdSize does not handle ARRAY constructor calls

- core/src/main/java/org/apache/calcite/sql/SqlDialect.java
- core/src/main/java/org/apache/calcite/sql/SqlDialectFactoryImpl.java
- core/src/main/java/org/apache/calcite/sql/dialect/DuckDBSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6988
> [CALCITE-6988] DuckDB dialect implementation

- core/src/main/java/org/apache/calcite/config/CalciteSystemProperty.java
- core/src/main/java/org/apache/calcite/sql/dialect/StarRocksSqlDialect.java
- core/src/test/java/org/apache/calcite/test/JdbcAdapterTest.java
- testkit/src/main/java/org/apache/calcite/test/CalciteAssert.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6995
> [CALCITE-6995] Support FULL JOIN in StarRocks/Doris Dialect

- core/src/main/java/org/apache/calcite/rel/rules/AggregateMinMaxToLimitRule.java
- core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
- core/src/test/resources/sql/planner.iq
Please see: [CALCITE-6985](https://issues.apache.org/jira/browse/CALCITE-6985)
> [CALCITE-6985] Add rule to transform MIN/MAX with ORDER BY and LIMIT 1

- core/src/test/java/org/apache/calcite/examples/RelBuilderExample.java
This corrects the comment for `example0` to accurately describe the code's behavior. 
**Problem**:  
The original comment incorrectly stated that the code performs a table scan (`SELECT * FROM emp`). However, the code uses the `VALUES` clause to create an inline table of literal values.  
**Fix**:  
The comment has been updated to reflect the actual behavior, which is equivalent to:   `VALUES (1, TRUE), (NULL, FALSE)`.  
**Impact**:  
Developers referencing this example will now see documentation that aligns with the code’s functionality.  
Thank you for considering this improvement! 🙏
> Update documentation for example0 in RelBuilderExample

- core/src/main/java/org/apache/calcite/rel/rules/IntersectToSemiJoinRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
- core/src/test/resources/sql/planner.iq
Jira link: [CALCITE-7000](https://issues.apache.org/jira/browse/CALCITE-7000)
> [CALCITE-7000] Extend IntersectToSemiJoinRule to support n-way inputs

- core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
- core/src/test/resources/sql/join.iq
JIRA link: [CALCITE-7006](https://issues.apache.org/jira/browse/CALCITE-7006)
> [CALCITE-7006] Incorrect left join results with IS NOT DISTINCT FROM under specific plan

- core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
- core/src/main/java/org/apache/calcite/sql/dialect/PrestoSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-7005
> [CALCITE-7005] Invalid unparse for IS TRUE,IS FALSE,IS NOT TRUE and IS NOT FALSE in Hive/Presto Dialect

- core/src/main/java/org/apache/calcite/sql/SqlDialect.java
- core/src/main/java/org/apache/calcite/sql/SqlDialectFactoryImpl.java
- core/src/main/java/org/apache/calcite/sql/dialect/SqliteSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
- core/src/test/java/org/apache/calcite/test/LintTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6997
> [CALCITE-6997] SQLite dialect implementation

- core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java
- core/src/main/java/org/apache/calcite/rel/rules/MinusToFilterRule.java
- core/src/main/java/org/apache/calcite/rel/rules/SetOpToFilterRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Jira link: [CALCITE-7002](https://issues.apache.org/jira/browse/CALCITE-7002)
> [CALCITE-7002] Create an optimization rule to eliminate UNION from the same source with different filters

- core/src/main/java/org/apache/calcite/rex/RexBuilder.java
- core/src/main/java/org/apache/calcite/tools/RelBuilder.java
- core/src/test/java/org/apache/calcite/plan/RelOptUtilTest.java
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-7013
> [CALCITE-7013] Support building RexLiterals from Character values

- core/src/main/java/org/apache/calcite/rex/RexBuilder.java
- core/src/main/java/org/apache/calcite/util/TimestampWithTimeZoneString.java
- core/src/test/java/org/apache/calcite/rex/RexBuilderTest.java
- core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java
- core/src/test/resources/sql/misc.iq
honestly, this PR looks like a bit hack as for me, but we can start with it and simplify all related stuff in future
> [CALCITE-7001] Cast of malformed literal to TIMESTAMP WITH LOCAL TIME  ZONE need to throw informative error

- core/src/main/java/org/apache/calcite/rel/rules/AggregateProjectPullUpConstantsRule.java
- core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java
- core/src/main/java/org/apache/calcite/rel/rules/ExpandDisjunctionForJoinInputsRule.java
- core/src/main/java/org/apache/calcite/rel/rules/FilterJoinRule.java
- core/src/main/java/org/apache/calcite/rel/rules/FilterTableFunctionTransposeRule.java
- core/src/main/java/org/apache/calcite/rel/rules/JoinCommuteRule.java
- core/src/main/java/org/apache/calcite/rel/rules/JoinDeriveIsNotNullFilterRule.java
- core/src/main/java/org/apache/calcite/rel/rules/RuleConfig.java
- core/src/main/java/org/apache/calcite/rel/rules/SortUnionTransposeRule.java
- core/src/test/java/org/apache/calcite/test/LoadCoreRulesTest.java
- core/src/test/resources/sql/planner.iq
- testkit/src/main/java/org/apache/calcite/test/QuidemTest.java
Please see: [CALCITE-6998](https://issues.apache.org/jira/browse/CALCITE-6998)
> [CALCITE-6998] The command !set planner-rules does not support rules with multiple Config

- core/src/main/java/org/apache/calcite/sql/dialect/PostgresqlSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
https://issues.apache.org/jira/browse/CALCITE-6866
> [CALCITE-6866] PostgreSQLDialect support to unparse LISTAGG aggregate function

- core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java
- core/src/main/java/org/apache/calcite/rel/rules/MinusToAntiJoinRule.java
- core/src/test/java/org/apache/calcite/test/JdbcTest.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
- core/src/test/resources/sql/planner.iq
Jira link: [CALCITE-7008](https://issues.apache.org/jira/browse/CALCITE-7008)
> [CALCITE-7008] Extend MinusToAntiJoinRule to support n-way inputs

- core/src/main/java/org/apache/calcite/rel/rules/AggregateValuesRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
As description in JIRA: https://issues.apache.org/jira/browse/CALCITE-6887
> [CALCITE-6887] ReduceExpressionsRule applied to 'IN subquery' should make the values distinct if the subquery is a Values composed of literals

- core/src/main/java/org/apache/calcite/sql/dialect/StarRocksSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
Jira:  https://issues.apache.org/jira/browse/CALCITE-6952
> [CALCITE-6952] JDBC adapter for StarRocks generates incorrect SQL for REAL datatype

- core/src/main/java/org/apache/calcite/adapter/enumerable/EnumerableLimitSortRule.java
- core/src/test/java/org/apache/calcite/test/RelMetadataTest.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Jira: [CALCITE-7047](https://issues.apache.org/jira/browse/CALCITE-7047)
> [CALCITE-7047] Improve Volcano planner selection of sort conversion rules

- core/src/main/java/org/apache/calcite/adapter/enumerable/RexToLixTranslator.java
- core/src/test/resources/sql/cast.iq
jira: https://issues.apache.org/jira/browse/CALCITE-7054
> [CALCITE-7054] Runtime conversion of DECIMAL MULTISET to INT MULTISET or DECIMAL ARRAY to INT MULTISET fails with a ClassCastException

- core/src/main/java/org/apache/calcite/sql/SqlArrayWithAngleBracketsNameSpec.java
- core/src/main/java/org/apache/calcite/sql/dialect/StarRocksSqlDialect.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
jira: https://issues.apache.org/jira/browse/CALCITE-7055
> [CALCITE-7055] Invalid unparse for cast to array type in StarRocks

- core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
jira: https://issues.apache.org/jira/browse/CALCITE-7056
> [CALCITE-7056] Convert RelNode to Sql failed when the RelNode includes quantify operators

- core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
jira: https://issues.apache.org/jira/browse/CALCITE-7051
> [CALCITE-7051] NATURAL JOIN and JOIN with USING does not match the appropriate columns when caseSensitive is false

- core/src/main/java/org/apache/calcite/plan/RelOptUtil.java
- core/src/main/java/org/apache/calcite/sql2rel/RelFieldTrimmer.java
- core/src/main/java/org/apache/calcite/sql2rel/RexRewritingRelShuttle.java
- core/src/test/java/org/apache/calcite/plan/RelOptUtilTest.java
- core/src/test/java/org/apache/calcite/sql2rel/RelFieldTrimmerTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
- core/src/test/resources/sql/scalar.iq
https://issues.apache.org/jira/browse/CALCITE-7064
> [CALCITE-7064] Test introduced in [CALCITE-7009] breaks the build for main

- core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java
- core/src/main/java/org/apache/calcite/rel/rules/FullToLeftAndRightJoinRule.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Jira: https://issues.apache.org/jira/browse/CALCITE-7077
> [CALCITE-7077] Implement a rule to rewrite FULL JOIN as LEFT JOIN and RIGHT JOIN

- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Jira: [CALCITE-7071](https://issues.apache.org/jira/browse/CALCITE-7071)
> [CALCITE-7071] Add test for replacing JOIN node with its child node when JOIN condition is false

- core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
jira: https://issues.apache.org/jira/browse/CALCITE-7050
> [CALCITE-7050] Invalid unparse for FULL JOIN in MySQLDialect

- core/src/main/java/org/apache/calcite/sql/dialect/ClickHouseSqlDialect.java
- core/src/main/java/org/apache/calcite/util/RelToSqlConverterUtil.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
jira：https://issues.apache.org/jira/browse/CALCITE-7081
> [CALCITE-7081] Invalid unparse for cast to nested type in ClickHouse

- core/src/main/java/org/apache/calcite/rel/RelHomogeneousShuttle.java
- core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
[CALCITE-7090](https://issues.apache.org/jira/browse/CALCITE-7090)
> [CALCITE-7090] Support LogicalRepeatUnion in RelHomogeneousShuttle

- core/src/main/java/org/apache/calcite/rel/rules/AggregateFilterToCaseRule.java
- core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
- core/src/test/resources/sql/planner.iq
JIRA:[CALCITE-7086](https://issues.apache.org/jira/browse/CALCITE-7086)
> [CALCITE-7086] Implement a rule that performs the inverse operation of AggregateCaseToFilterRule

- core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
- core/src/main/java/org/apache/calcite/sql/dialect/StarRocksSqlDialect.java
- core/src/main/java/org/apache/calcite/util/RelToSqlConverterUtil.java
- core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
jira: https://issues.apache.org/jira/browse/CALCITE-7114
> [CALCIATE-7114] Invalid unparse for cast to array type in Spark

- core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java
- core/src/main/java/org/apache/calcite/rel/rules/JoinCommuteRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Jira link: https://issues.apache.org/jira/browse/CALCITE-7089
> [CALCITE-7089] Implement a rule for converting a RIGHT JOIN to a LEFT JOIN

- core/src/main/java/org/apache/calcite/sql/validate/implicit/AbstractTypeCoercion.java
- core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
- core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
- elasticsearch/src/test/java/org/apache/calcite/adapter/elasticsearch/ElasticSearchAdapterTest.java
- innodb/src/test/java/org/apache/calcite/adapter/innodb/InnodbAdapterTest.java
- mongodb/src/test/java/org/apache/calcite/adapter/mongodb/MongoAdapterTest.java
When comparing two CHAR types prefer VARCHAR
When comparing BINARY and VARBINARY prefer VARBINARY
When comparing BINARY and CHAR result is VARCHAR
> [CALCITE-7132] Inconsistency with type coercion and character types

- core/src/main/java/org/apache/calcite/rel/rules/CoreRules.java
- core/src/main/java/org/apache/calcite/rel/rules/SortRemoveDuplicateKeysRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
Jira: [CALCITE-7104](https://issues.apache.org/jira/browse/CALCITE-7104)
> [CALCITE-7104] Remove duplicate sort keys

- core/src/main/java/org/apache/calcite/rex/RexSimplify.java
- core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
jira: https://issues.apache.org/jira/browse/CALCITE-7088
> [CALCITE-7088] Multiple consecutive '%' in the string matched by LIKE should simplify to a single '%'

- core/src/main/java/org/apache/calcite/rel/metadata/RelMdUtil.java
- core/src/main/java/org/apache/calcite/rel/rules/SortJoinTransposeRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
- core/src/test/resources/sql/planner.iq
See: [CALCITE-4617](https://issues.apache.org/jira/browse/CALCITE-4617)
> [CALCITE-4617] Wrong offset when SortJoinTransposeRule pushes a Sort with an offset

- Jenkinsfile
> [CALCITE-7163] Upgrade Sonar Gradle Plugin to version 6.3.1.5724

- core/src/main/java/org/apache/calcite/rel/rules/SortRemoveRedundantRule.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
See: [CALCITE-7181](https://issues.apache.org/jira/browse/CALCITE-7181)
> [CALCITE-7181] FETCH in SortRemoveRedundantRule only supports INT

- core/src/main/java/org/apache/calcite/sql/validate/SqlAbstractConformance.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlConformance.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlConformanceEnum.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlDelegatingConformance.java
- core/src/main/java/org/apache/calcite/sql/validate/SqlValidatorImpl.java
- core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java
- core/src/test/resources/sql/agg.iq
See: [CALCITE-7189](https://issues.apache.org/jira/browse/CALCITE-7189)
> [CALCITE-7189] Support MySQL-style non-standard GROUP BY

- core/src/main/java/org/apache/calcite/rel/rules/HyperEdge.java
- core/src/test/java/org/apache/calcite/test/RelOptRulesTest.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
This fix is described in detail in the JIRA ticket, and it was created by Nirmal Govindaraj 
I have only expedited the implementation.
> [CALCITE-7191] Hypergraph creation with incorrect hyperedges

- core/src/test/resources/sql/scalar.iq
These were validated using postgres.
I don't know why the tests were disabled.
> Enable some disabled quidem tests

- core/src/main/java/org/apache/calcite/rex/RexSimplify.java
- core/src/test/java/org/apache/calcite/rex/RexProgramTest.java
Jira: [CALCITE-7215](https://issues.apache.org/jira/browse/CALCITE-7215)
> [CALCITE-7215] Simplify SEARCH operand in RexSimplify.simplifySearch

- core/src/main/java/org/apache/calcite/sql2rel/RelStructuredTypeFlattener.java
- core/src/test/resources/org/apache/calcite/test/RelOptRulesTest.xml
- core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml
[JIRA](https://issues.apache.org/jira/browse/CALCITE-7212)
> [CALCITE-7212] VariablesSet of Project is lost during RelStructuredTypeFlattener processing
